### ISSUE TITLE
Add support for scraping TikTok Comments.

### ISSUE THREAD

**Issue by Rich700000000000** [imputnet/cobalt#1000]
### Describe the feature you'd like to see

Adding support for TikTok comments would be a simple and easy upgrade. They're publicly available on any video, so there's no keys required. And while I haven't tested it, I'm pretty sure there's no rate limit either.  

### Additional context

I just tested another repository, and the functionality of it, at least, is flawless: 

[https://github.com/cubernetes/TikTokCommentScraper](https://github.com/cubernetes/TikTokCommentScraper)

It gives me a perfect xlsx, I couldn't be happier with it.

The problem is, in order to use it you have to go through an arduous process that involves first installing Chromium, and then manually copy-pasting javascript into the console. That's a nonstarter if you have any more than a few dozen videos, much less the thousands that I need to download. Fortunately, the active part of his script is under 200 lines of Javascript, so it should be an easy addition, correct? If I'm missing something, please let me know.

**Comment by dumbmoron** [comment]
this is out of scope for cobalt

**Comment by Rich700000000000** [comment]
I'm sorry, but I don't understand how. Comments falls under metadata. You paste a link, you get a xlsx file. Simple, right?
