### ISSUE TITLE
The YouTube cookie has been set, but it doesn't work

### ISSUE THREAD

**Issue by xiaosaturn** [imputnet/cobalt#1005]
### bug description

![image](https://github.com/user-attachments/assets/0874f1da-fe71-4c14-962a-b8b8e7707d5c)
![image](https://github.com/user-attachments/assets/6c74866c-bda1-4979-9214-24937dac44b5)

However, on the official website [https://cobalt.tools/](https://cobalt.tools/), downloading YouTube videos works fine. But on my self-hosted setup, it doesn't work. I followed the instructions in `configure-for-youtube.md` and tried several times, but it still doesn't work.

I would greatly appreciate it if you could help me check the issue，thank you.

### reproduction steps

1. view  `configure-for-youtube.md`
2. generate cookie and new cookies.json
3. env have set

### platform information

Chrome 131 on Windows 11

**Comment by wukko** [comment]
#942

**Comment by xiaosaturn** [comment]
So， It can't be solved? Is there any other solution?
