### ISSUE TITLE
Infamous 0kb Problem is Back

### ISSUE THREAD

**Issue by GreenwaveStudios** [imputnet/cobalt#1006]
### bug description

**I FUCKING HATE THIS!!** Everytime I try to download a video it only shits out 0kb files that don't work properly and are corrupted! I've done some digging and realized this is not the first time that's happened. Look at the top right to see what i mean. I tried various videos and browsers with no working result.

### reproduction steps

1. Copy link.
2. Press audio
3.  Watch the bullshit happen

### screenshots

![image](https://github.com/user-attachments/assets/6d788ecf-1992-4dcb-8152-de60dd515905)

### platform information

Chrome 131 on windows 11

**Comment by dumbmoron** [comment]
> ### bug description
> **I FUCKING HATE THIS!!**

<img width="457" alt="Screenshot 2024-12-18 at 16 31 15" src="https://github.com/user-attachments/assets/a465ae6b-7fd6-421b-8ba7-a88388873b69" />

**Comment by wukko** [comment]
> I FUCKING HATE THIS

> Watch the bullshit happen

why are you so aggressive? it’s not the end of the world. i’ll make a new issue because this one is immature and not informative.

**Comment by wukko** [comment]
#1007

**Comment by GreenwaveStudios** [comment]
> > I FUCKING HATE THIS
> 
> > Watch the bullshit happen
> 
> why are you so aggressive? it’s not the end of the world. i’ll make a new issue because this one is immature and not informative.

Sorry. I was getting so stressed
