### ISSUE TITLE
can't get anything from YouTube on the main instance

### ISSUE THREAD

**Issue by wukko** [imputnet/cobalt#1007]
### bug description

attempting to get anything from youtube may result in an empty (0 bytes) file or a message that says "youtube downloading is temporarily disabled due to restrictions from youtube's side."

### reproduction steps

1. paste any youtube link (such as https://www.youtube.com/watch?v=dQw4w9WgXcQ).
2. get either an empty file or an error message.

### additional context

this exact issue occurred a week ago (#992) and was fixed as soon as it was possible.

the problem is not with cobalt's codebase, but is instead caused by network restrictions from youtube's side. just like last time, our proxy instances can't access `googlevideo.com`. instead of expected content they get 403. cobalt catches the error and aborts the tunnel, causing empty files as result.

we're already looking into new ways to go around this bullshit restriction, and are doing our best to restore youtube downloading asap. we're not happy about it either and are extremely tired.

since the "problem" is with the network, eta is unknown. resolution time depends on network providers. either me or @dumbmoron will close this issue as soon as it's resolved.

as a temporary (or permanent) workaround, you can host a cobalt instance on your home network: https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md

**Comment by zig71** [comment]
Yo bro can we get a fix???

**Comment by dumbmoron** [comment]
> Yo bro can we get a fix???

@zig71 can u read the OP

**Comment by zig71** [comment]
@dumbmoron Tryna download a vid rn

**Comment by eaglehuntt** [comment]
That's interesting... I'm curious to learn about how other YT downloading tools can stay running with constant changes on YouTube's side of things. Especially the sketchy ones online

**Comment by cdarbs11** [comment]
This appears to be working! Nice job @wukko! How did you do it?

**Comment by zephiii** [comment]
Still happening to me.

**Comment by coderooo** [comment]
How can I solve this problem? I'm having this problem with my own deployed instance
