### ISSUE TITLE
Audio not included in facebook video

### ISSUE THREAD

**Issue by Aholicknight** [imputnet/cobalt#1012]
### bug description

When downloading a video from facebook, it will not contain any audio even when it does

### reproduction steps

1. Copy a link from a facebook video that has audio
2. Download the video
3. Play the video in VLC or any media player

### platform information

Windows 10 firefox

**Comment by tayfrm99** [comment]
It's working, check again

**Comment by tayfrm99** [comment]
It's working, check again

tested using firefox r128

https://github.com/user-attachments/assets/675a923d-6c30-4540-b05d-a83a4a0c5c48

**Comment by Aholicknight** [comment]
> It's working, check again

@tayfrm99 Try downloading a previous live broadcast, thats where I noticed the video without audio.

**Comment by wukko** [comment]
> Try downloading a previous live broadcast

try filling out an issue template properly, we can’t read your mind
