### ISSUE TITLE
Video and audio files from Youtube have a size of0 B

### ISSUE THREAD

**Issue by DevilEmoni** [imputnet/cobalt#1013]
### bug description

When downloading a file from cobalt.tools the filesize of audio and video files are 0 bytes. Audio and Media Player state that they are corrupt.

### reproduction steps

1. Copy a youtube link
2. Paste the link into the box on the website
3. Choose either video or audio and press >>
4. Check the filesize

### screenshots

![Screenshot 2024-12-21 163601](https://github.com/user-attachments/assets/f3600221-c17f-4ae5-9419-fe6672ee8019)

### platform information

Brave v1.73.104 on Windows 11

**Comment by dumbmoron** [comment]
can you try again now?

**Comment by DevilEmoni** [comment]
> can you try again now?

Works now!
