### ISSUE TITLE
Youtube audio downloads are truncated

### ISSUE THREAD

**Issue by jp-coetzee** [imputnet/cobalt#1015]
### bug description

I am using the website and trying to download the audio of Youtube videos but they are truncating after about 40 minutes or so.
I have tried using "tunnel files" both on and off.

### reproduction steps

1. Paste the following into http://cobalt.tools : https://www.youtube.com/watch?v=4k2boBFWHYI
   (that video is 2 hours 12 minutes long)
2. Click on "audio", wait for download to finish
3. Play audio in any music player

The downloaded MP3 is 46 minutes long.

### platform information

Windows 10 22H2, Firefox 133.0.3

**Comment by wukko** [comment]
https://cobalt.tools/settings/video#youtube-hls

**Comment by jp-coetzee** [comment]
Perfect, thank you.
I'm not interested in video so did not look at those settings, it might be a good idea to copy that one to the audio tab?
