### ISSUE TITLE
Downloading Playlists or Downloading Multiple Videos At Once?

### ISSUE THREAD

**Issue by AnxiousPleaseHelp** [imputnet/cobalt#1017]
### describe the feature you'd like to see

Hello,

I just wanted to know if it were possible to download playlists rather than downloading each individual file? For example, on DailyMotion? 

I only ask because it's such a tedious process copying each link one at a time.

More and more videos keep getting deleted before I'm able to save them which really sucks... 😭 😭 

I hope someone can help me!

**Comment by wukko** [comment]
#193
