### ISSUE TITLE
Add support for Newgrounds audio (and maybe video?)

### ISSUE THREAD

**Issue by HGStyle** [imputnet/cobalt#1027]
### service name

Newgrounds

### service description

Newgrounds is a old platform where creators can upload their content, whenether its video, audio, Flash games...

### link samples

```shell
Regular audio link: https://www.newgrounds.com/audio/listen/707843
Restricted audio link: https://www.newgrounds.com/audio/listen/1366420  [just has bad words]
```

### additional context

![image](https://github.com/user-attachments/assets/1f6cde9d-da97-4e34-afd3-c6807d567bcf)
As you can see, public audios are easy to download, as the necessary info is inside the URL (for the content's ID) and inside the meta tags of the server's response (inside og:name for the song name, og:audio for the MP3 url, and og:image for the icon of the image).

![image](https://github.com/user-attachments/assets/96930871-1241-4302-8602-b3446f59d674)
However, some audios are classified as "A" for "Adult" and need an account to be viewed. Those are very rare but can happen.

For the videos, I do not use Newgrounds for viewing videos, so I don't really know whether it can be as easy for videos, but for sure the same system for adult-restricted content is also there.

**Comment by tayfrm99** [comment]
#620

**Comment by HGStyle** [comment]
> #620

I added more details about how to technically do it, so I'm keeping this opened, but if needed will close it.

**Comment by KwiatekMiki** [comment]
> I added more details about how to technically do it

it has already been done

#682

**Comment by HGStyle** [comment]
Okay, sorry for bothering.
