### ISSUE TITLE
Missing preview image in macOS WhatsApp client

### ISSUE THREAD

**Issue by ianrobertlambert** [imputnet/cobalt#204]
**Issue Description:**

When I attempt to share an MP4 downloaded using Cobalt on WhatsApp, I notice that it lacks a video preview. I have tried downloading videos with different codecs, but the issue persists. Interestingly, when I use other download tools, the WhatsApp video preview is present. I prefer using Cobalt for my downloads, and I'm wondering if there's any way to fix this issue?

**Steps to Reproduce:**
1. Download an MP4 video using Cobalt.
2. Share the downloaded MP4 video on WhatsApp.
3. Observe that the video preview is missing.

**Expected Behavior:**
I expect the MP4 videos downloaded with Cobalt to include a video preview when shared on WhatsApp, similar to other download tools.

**Comment by wukko** [comment]
can you give me a sample link and tell me what platform this issue is present on?

**Comment by ianrobertlambert** [comment]
- Any video I attempt to download from Reddit ([example hosted on Reddit](https://www.reddit.com/r/FunnyAnimals/comments/16hac3i/hes_no_pug_hes_a_thug/)).
- Cobalt for Raycast (macOS).

**Comment by ianrobertlambert** [comment]
Thanks for taking a look at this. 🙏

1. Downloaded a YouTube video using the Cobalt for Raycast extension and the issue still persists.
2. Downloaded a YouTube video using https://cobalt.tools/ and the issue still persists.

_Note: I downloaded the same video using another tool and there is no issue. The WhatsApp video preview works._
