### ISSUE TITLE
Configurable rate limits

### ISSUE THREAD

**Issue by CoreBytee** [imputnet/cobalt#235]
Is there an option to configure rate limits on self-hosted instances?
If not, could it be added?

Thanks

**Comment by 2shiraz** [comment]
It would be really cool if that could be set from docker-compose file

**Comment by ggtylerr** [comment]
Necroposting a little, but this is definitely a must for low powered VPS's. I host my own instances and recently got one for my californian node, and downloading just one file that's audio only causes a CPU core to max out. (Out of the two that are there.) Implementing a queue or some kind of limit would definitely help mitigate this.

**Comment by KwiatekMiki** [comment]
https://github.com/imputnet/cobalt/blob/current/docs/run-an-instance.md#variables-for-api
![image](https://github.com/user-attachments/assets/9f37cb6b-534f-4885-82d5-027552554ffd)
