### ISSUE TITLE
Video scrubbing of YouTube videos does not work in outdated video players

### ISSUE THREAD

**Issue by athif23** [imputnet/cobalt#255]
Sometimes videos I downloaded from youtube aren't able to seek, it's playable but it can only be started from start, you can't forward or backward the frame at all. This is one of the link I tried, https://www.youtube.com/watch?v=yRgpAhc3WlA. 

![ApplicationFrameHost_qA7CjqqUk0](https://github.com/wukko/cobalt/assets/15215827/05a74907-049d-49f2-ab27-2c6fa18daaa6)

As you can see, the slider is disabled and can't be dragged at all.

**Comment by wukko** [comment]
i recommend using a more advanced video player, such as https://www.videolan.org/vlc/

youtube videos are rendered on-fly, cobalt can't predict the final rendered file size, so that info is missing from the header

**Comment by SKCro** [comment]
@wukko Why not determine the size when the video is finished rendering, then tack it onto the header? I'm not really sure how video file headers work, but I'm sure there must be some way to do it...

**Comment by MrCodeWeaver** [comment]
I'm running into this issue as well with the latest version (11.2401.2.0) of Windows Media Player
