### ISSUE TITLE
Instagram stories don't work

### ISSUE THREAD

**Issue by ShortyDev** [imputnet/cobalt#280]
When trying to download Instagram stories with the following links:
- https://www.instagram.com/stories/[user]/[id]/
- https://www.instagram.com/stories/[user]/

the download does not work. Instead an error appears, stating that nothing could be downloaded from that link.

I've tried with several accounts (all public) and media (photo and video), but it does not work.

**Comment by wukko** [comment]
do all accounts happen to include at least one period in the name?

**Comment by wukko** [comment]
glad it works now :D
