### ISSUE TITLE
Don't return html links in API responses

### ISSUE THREAD

**Issue by lostdusty** [imputnet/cobalt#298]
I was playing with the api while writing [gobalt](https://github.com/princessmortix/gobalt), and i saw that the api returns html code if the url provided is invalid, shown on the screenshot below: 
![image](https://github.com/wukko/cobalt/assets/47502554/eb29e5d2-7026-4fe4-a9ac-3f806a46daf3)

I believe this shouldn't happen, and the api should return only regular text on the text response body.

**Comment by ethrythedev** [comment]
it seems as though that is what defines what the cobalt website returns, the api should ideally send an error code

![image](https://github.com/wukko/cobalt/assets/58019814/fe3efd2d-3e17-467e-a478-bcd3fe136306)
