### ISSUE TITLE
Windows Media Player won't play some videos

### ISSUE THREAD

**Issue by MEESTERSoupCan** [imputnet/cobalt#345]
**bug description**
Certain videos I download from YouTube don't allow seeking, and instead shows something like a streaming icon where the full video length should be. Putting the video into an editor only imports a blank audio file, and no video.

**reproduction steps**
steps to reproduce the behavior:
1. go to youtube
2. go to https://www.youtube.com/watch?v=rf3vgTpFExU
3. download the video
4. attempt to view in player or in editing software

**screenshots**
![cobaltvideo](https://github.com/wukko/cobalt/assets/34176597/0a4d8eb6-ea65-4584-b1c7-2752ca041e8c)
![cobaltvideo2](https://github.com/wukko/cobalt/assets/34176597/93341f70-7754-430a-83fc-7f289dba2e72)

**links**
This has happened with every video I downloaded.

**platform**
- OS - Windows 11
- Browser - Opera GX
- Browser Version - 106.0.4998.61

**additional context**
Audio downloads just fine, it doesn't like videos though.
I just found that certain videos do this, while others do not. This one specifically has the issue.

**Comment by princessmortix** [comment]
This can be fixex by remuxing the video. If don't know how to do so, see it here: https://github.com/wukko/cobalt/issues/333#issuecomment-1912020947
