### ISSUE TITLE
Safari macOS : Popup is blurred on non HiDPI Screen

### ISSUE THREAD

**Issue by Write** [imputnet/cobalt#363]
**bug description**

Any .popup windows appear blurred on Safari, caused by transform: translate(-50%,-50%); in .popup.visible css declaration.
_This does not happen on firefox_

**reproduction steps**
steps to reproduce the behavior:
1. click on any links at the bottom that popup a windows
2. text is blurred

**screenshots**

With `transform: translate(-50%,-50%);` : 

![Screenshot du 2024-02-19 à 11 12 05](https://github.com/wukko/cobalt/assets/541722/13934ebc-eb30-468d-98f2-edb8f765beb8)

With `transform: translate(-50%,-50%);` in .popup.visible and `transform: translate(-50%,-48%)scale(.95);`  in .popup unticked in dev tools : 

![Screenshot du 2024-02-19 à 11 15 03](https://github.com/wukko/cobalt/assets/541722/a6114c29-7d26-4c69-8379-acaf14c0cf7c)

It still show as slightly blurred though. 

On Firefox (same platform), the result is prefect :

![Screenshot du 2024-02-19 à 11 16 16](https://github.com/wukko/cobalt/assets/541722/e71ed87a-be0a-451b-8754-654a887b07d5)

**platform**
- OS : macOS
- browser Safari /  _This does not happen on firefox_

- version : Version 17.3.1 (19617.2.4.11.12) / Sonoma 14.3.1

Note :  This issue seems to only affect external-no HiDPI screen on macOS. While Firefox handles it fine. 
I directly checked cobalt on my MBP Native screen and it renders sharply. 
Not sure if there's a workaround.

**Comment by wukko** [comment]
does this happen only when switching windows between HiDPI screen and laptop screen?

**Comment by Write** [comment]
> does this happen only when switching windows between HiDPI screen and laptop screen?

I never switch between the two because my mbp is always in clamshell mode.
So assume all my screen are not in HiDPI mode and there's no switch.

So no, it happens all the time on non-HiDPI screen with Safari.
On Firefox, like said before, works fine.

Anyway that's such a small issue… Not sure it's worth the time debugging it.

I'm still kinda surprised I couldn't find a css rule that make its render sharply on Safari, I haven't digged in too much though.

**Comment by wukko** [comment]
does it still happen? i tuned css a bit in the last month


> Not sure it's worth the time debugging it

frontend will be (eventually) rewritten in svelte, so yeah, not really

**Comment by Write** [comment]
> does it still happen? i tuned css a bit in the last month
> 
> > Not sure it's worth the time debugging it
> 
> frontend will be (eventually) rewritten in svelte, so yeah, not really

Oh yeah, popup only, everything else is crystal clear. I have watchtower so I'm using the latest build

![Screenshot du 2024-04-09 à 08 06 07](https://github.com/wukko/cobalt/assets/541722/e358e008-91a7-457a-bc33-64537795d3c9)


Rest of the UI crystal clear 👍 
![Screenshot du 2024-04-09 à 08 07 00](https://github.com/wukko/cobalt/assets/541722/b3eca82a-1f8d-4b2a-9c24-3a305b3f499e)

**Comment by wukko** [comment]
> feel free to close the issue

i'll keep it around to just in case the issue sticks
