### ISSUE TITLE
YouTube Clip downloading support

### ISSUE THREAD

**Issue by YTR76** [imputnet/cobalt#388]
**describe the feature you'd like to see**
youtube clip support

**describe alternatives you've considered**
y2down, but i wouldn't really recommend that because it has the problem that cobalt is supposed to solve
 
**additional context**
that's it tbh

**Comment by lostdusty** [comment]
Already in the works, see #350.

**Comment by protectedprofile** [comment]
A lot of mp3's I want on music.youtube.com can't be downloaded due to restriction, can only be streamed. I wish this could be solved. Try the artist Dio and share my frustration.

**Comment by PoketrainerMS** [comment]
in the meantime, id recommend the Discord bot MediaForge, though it's not always online sadly

**Comment by wclxb** [comment]
> Already in the works, see #350.

This would be different than downloading a YouTube clip. The request is support for downloading "youtube.com/clip/CLIP_ID" urls.

**Comment by dumbmoron** [comment]
duplicate of #128
