### ISSUE TITLE
music.youtube.com - Many can't be downloaded due to restriction

### ISSUE THREAD

**Issue by protectedprofile** [imputnet/cobalt#389]
A lot of mp3's on music.youtube.com can't be downloaded due to restriction, can only be streamed. I wish this could be solved. Try the artist Dio and share my frustration. Some can be downloaded, others can't.

**Comment by KwiatekMiki** [comment]
use another instance.
(like [cobalt-uk.axolotl.top](https://cobalt-uk.axolotl.top))

**Comment by dumbmoron** [comment]
this should not be a problem anymore :3

**Comment by JITZKI** [comment]
The same issue in cobalt resurfaced, I found this out today while trying to download some music for a project, every single video is restricted, and this hasn't been an issue before. Im about to go on a flight so can someone please help...

**Comment by wukko** [comment]
@JITZKI does it happen still? it seems to work fine to me rn
