### ISSUE TITLE
File length isn't shown in Google Photos app

### ISSUE THREAD

**Issue by Lassoloc** [imputnet/cobalt#483]
**bug description**
was saving a stupid 11 second meme video, however the video downloaded states a time of 00:00. it plays normally on my phone but my media picker is unsure of what to do with it when trying to share

**reproduction steps**
steps to reproduce the behavior:
1. go to 'cobalt.tools'
2. unsure if relevant, but settings used were 8k quality for maximum available resolution and h264 codec.
3. download this video: **[https://youtu.be/jTyClhN57Ic?si=mQy6c73nT-voMHQb]**
4. view mp4 file properties

**screenshots**
![file properties png](https://github.com/wukko/cobalt/assets/72823326/3baa5464-b00c-427e-b516-0e53b73801ac)

![in discord file picker png](https://github.com/wukko/cobalt/assets/72823326/bdd8cf6b-0fce-45c7-af76-2eb0d162c3fb)

**links**
[copy uploaded to discord, keeps incorrect metadata when downloaded](https://media.discordapp.net/attachments/519714050259812362/1235856219919614013/youtube_jTyClhN57Ic_1920x1080_h264.mp4)

**platform**
- device is moto g stylus 5g 2022 running android 13
- downloaded with google search app

btw, if you're curious: i was going to send the video to republican politicians

**Comment by KK-Designs** [comment]
I don't think cobalt knows how long the video is, usually running `ffmpeg -i input.mp4 -c copy output.mp4` fixes it losslessly
