### ISSUE TITLE
Migrate to Bun

### ISSUE THREAD

**Issue by lonelil** [imputnet/cobalt#489]
**describe the feature you'd like to see**
Switch from nodejs to bun

**additional context**
Bun is faster and more lightweight than nodejs

**Comment by lonelil** [comment]
i can pr this if wanted

**Comment by dumbmoron** [comment]
> Bun is faster and more lightweight than nodejs

could you make a benchmark for this, in the context of cobalt?

**Comment by lonelil** [comment]
did some testing and bun was somehow slower, the setup cli and the api was slower to start and bun would crash when requesting the stream endpoint 💀

**Comment by wukko** [comment]
> bun was somehow slower
so, is it good to close the issue as request is invalid?

**Comment by catdevnull** [comment]
if it helps with anything, i've tried bun for many use cases (including one or two scrapers) and every time i've had weird crashes or memory leaks. unless there's a specific reason to use bun, i don't see why
