### ISSUE TITLE
tiktok: api changed, can't download anything anymore

### ISSUE THREAD

**Issue by wukko** [imputnet/cobalt#497]

**Comment by wukko** [comment]
> I also get this message for all videos tried so far.

i sure do wonder why

**Comment by Trimpsuz** [comment]
According to [this](https://github.com/yt-dlp/yt-dlp/issues/9506#issuecomment-2115734300) comment on the [yt-dlp repo](https://github.com/yt-dlp/yt-dlp/), using the mobile (/feed) API which cobalt uses might now be impossible, so might have to look into an alternative approach such as the desktop webpage.

**Comment by moeinrahimi** [comment]
> > I also get this message for all videos tried so far.
> 
> i sure do wonder why

I don't get it why? that link is just a sample from my users. it doesn't look like to be nsfw
