### ISSUE TITLE
add an ability to change max video length limit

### ISSUE THREAD

**Issue by tarkodev** [imputnet/cobalt#498]
![image](https://github.com/imputnet/cobalt/assets/39101744/98fbe456-062d-47e1-b4f1-fc469b75bad2)

I have a self host cobalt session, and i don't know where is the parameter to download video longer than 180 minutes (mainly for youtube full playthrough)

If someone have the answer =) thanks

**Comment by wukko** [comment]
added in d1e8929, [check docs](https://github.com/imputnet/cobalt/blob/current/docs/run-an-instance.md#variables-for-api) for more info
