### ISSUE TITLE
Why can't a see the total file size in certains case

### ISSUE THREAD

**Issue by tarkodev** [imputnet/cobalt#499]
First of all, thank you for adding my last feature request "MAX_DURATION"!! (it was like realllyyyyy the only feature I was missing to be able to switch on Cobalt completely)

So, for example, here this video:
https://youtu.be/A_qMu9ClfC8

When i download it in 1080p, i can't see the total file size, and that's sort of annoying for large file size (like reallyyy really annoying, especially when dealing with multiple large file size, i can't really know how many time it will take to download)
![image](https://github.com/imputnet/cobalt/assets/39101744/5c5bcc65-0912-4afb-a250-ad39920c2317)

But, for some reason when the total file size is 720p, i can see the total file size and the remaining time
![image](https://github.com/imputnet/cobalt/assets/39101744/9c4cc1e6-0a99-41f3-a5ca-0370ef6cedc1)

Is it possible to fix the file size for resolution other than 720p? Thank you for taking the time to read =))

**Comment by wukko** [comment]
that’s because files are rendered on the fly and it’s impossible to predict exact final size
