### ISSUE TITLE
Can’t access API from some private business vpn

### ISSUE THREAD

**Issue by Tintin232** [imputnet/cobalt#509]
**bug description**
Whenever I try to download any YT video, I get a error message as shown in the screenshot. This has been going on for a couple of days now.
![Screenshot_20240520_182847_Chrome](https://github.com/imputnet/cobalt/assets/168626469/c250042e-d4da-4c8f-b1b5-eeaf4135b175)

**platform**
- Android 14 
- chrome 
- version [124]

**Comment by wukko** [comment]
are you using a VPN? can you reload the page and try again?

**Comment by Tintin232** [comment]
I am using a VPN, but I've been using it for the past few months and never had this problem until now. 
I have reloaded the page multiple times, I've even tried clearing the cookies for the site - didn't help 😞.

**Comment by wukko** [comment]
are you using express vpn by any chance?

**Comment by Tintin232** [comment]
Yes

**Comment by wukko** [comment]
can you open https://ipinfo.io ***with VPN enabled*** and give me ***only*** the ASN? 

<img width="245" alt="image" src="https://github.com/imputnet/cobalt/assets/71202418/6ae121bc-4616-4911-b7a2-8711d00b9907">

**Comment by Tintin232** [comment]
Here it is 
![Screenshot_20240520_235755_Chrome](https://github.com/imputnet/cobalt/assets/168626469/05ce10cb-d499-45ba-a962-24fa49f64359)

**Comment by Tintin232** [comment]
> are you using express vpn by any chance?

Oh, wait 
I just realized that you asked me if I'm using _Express VPN_
Thought you were asking just _if_ I'm using a VPN 
My bad 
I'm not actually using Express VPN; it's some other one by some private company

**Comment by Tintin232** [comment]
![Screenshot_20240521_070800_Chrome](https://github.com/imputnet/cobalt/assets/168626469/44bcdc24-f0e0-4bd2-962c-68cb4347e5af)

The other site was blocked by my VPN

**Comment by wukko** [comment]
> was blocked by my VPN
can't do anything about that unfortunately, contact your provider to unblock *.imput.net

**Comment by Tintin232** [comment]
I see. 
Thank you for your help.

**Comment by Tintin232** [comment]
You were right, I got my VPN company to unblock that website, and now downloads are working again. Thank you for your help!

**Comment by wukko** [comment]
no problem :D
