### ISSUE TITLE
add support for medal.tv

### ISSUE THREAD

**Issue by iamqw3rty** [imputnet/cobalt#512]
**describe the feature you'd like to see**
medal.tv is a game clipping app that has ZERO good downloaders

**describe alternatives you've considered**
other downloaders are slow and filled with ads, or they have garbage quality

**additional context**
https://medal.tv/

**Comment by dumbmoron** [comment]
i dont understand, can you not just download all clips from the website?

![image](https://github.com/imputnet/cobalt/assets/136796770/6e685c21-0baf-463b-a628-19bdd825d68e)

**Comment by iamqw3rty** [comment]
> i dont understand, can you not just download all clips from the website?
> 
> ![image](https://private-user-images.githubusercontent.com/136796770/332703477-6e685c21-0baf-463b-a628-19bdd825d68e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzUzMDMsIm5iZiI6MTcxNjQzNTAwMywicGF0aCI6Ii8xMzY3OTY3NzAvMzMyNzAzNDc3LTZlNjg1YzIxLTBiYWYtNDYzYi1hNjI4LTE5YmRkODI1ZDY4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMzMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmJlM2U2OWI5NzNlM2Q2NmZiODg3MzMyYWZjMTQyNDgyMGZhN2E3ZDU4NjAxOTViYTE2ZjU5YTZhNmQ2NTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BzvYMXSqTJjcj-GGTmhbnPQmEPm0EGorprLoZtXQC2M)

watermark and outro for free users, while you can do it it isn't ideal
