### ISSUE TITLE
Rendered video downloads from Reddit are broken

### ISSUE THREAD

**Issue by dumbmoron** [imputnet/cobalt#526]
**bug description**
when downloading a reddit video, you will end up with an empty stream

**reproduction steps**
1. try to download any reddit video (e.g. [link](https://www.reddit.com/r/TikTokCringe/comments/wup1fg/id_be_escaping_at_the_first_chance_i_got))

**Comment by KwiatekMiki** [comment]
happens on other instances too

**Comment by wukko** [comment]
only happens when istream is called, ffmpeg can't parse headers and throws an error, aborting the stream
