### ISSUE TITLE
bbc iplayer

### ISSUE THREAD

**Issue by demo308** [imputnet/cobalt#536]
add bbc iplayer downloader 

source code from another one https://github.com/get-iplayer/get_iplayer

**Comment by wukko** [comment]
that's piracy and access is limited to just one region, so it won't happen

**Comment by demo308** [comment]
VPN lol

**Comment by demo308** [comment]
> it unfortunately won't ever happen because:
> 
> 1. that's piracy
> 2. access to bbc player is limited to just one region, hosting it would be a huge pain in the ass

i could try and get in contact with the main dev to help you
