### ISSUE TITLE
Reddit support is disabled, fix needed

### ISSUE THREAD

**Issue by Araxeus** [imputnet/cobalt#537]
why https://github.com/imputnet/cobalt/commit/7ebd9bc0ffb8ab486fbbab650576f1324b10f78a ? which part times out exactly?

I have downloaded a few different videos locally on my pc today using FFmpeg without any problem

`ffmpeg -i "${videoUrl}" -i "${audioUrl}" -c:v copy -c:a aac -strict experimental "${postName}.mp4"`

**Comment by lostdusty** [comment]
because reddit changed something in their api and now cobalt timeouts trying to download the media

**Comment by Dee-Codez** [comment]
can i work on this?
do i need to be assigned the issue or shd I just send a PR for the same?

**Comment by lostdusty** [comment]
just send a PR
