### ISSUE TITLE
Using enter as clicking "got it" very tiny details feature

### ISSUE THREAD

**Issue by Deetschoe** [imputnet/cobalt#540]
**Small little feature that would be nice**
When i input a wrong link or it gives me this: "it seems like this service is not supported yet or your link is invalid. have you pasted the right link?"

Rather than click "got it" i would like to be able to press enter on my keyboard.
<img width="487" alt="Screenshot 2024-06-05 at 10 37 54 AM" src="https://github.com/imputnet/cobalt/assets/48701612/e9a2b12b-04f6-408c-93d6-e17492a639d5">

**Comment by lostdusty** [comment]
at wukko i know "no touch frontend until rewrite" but can i PR this one? looks a simple fix/feature for me

**Comment by alectrocute** [comment]
@wukko @lostdusty Is discussion regarding the frontend rewrite ongoing somewhere? I can't seem to find it.

I'd love to contribute.

**Comment by lostdusty** [comment]
wukko is rewriting the frontend here: https://github.com/imputnet/cobalt/tree/develop/web
it has been said few times on discord

**Comment by wukko** [comment]
that tree is outdated and will be deleted soon. i have no free time to start the proper rewrite yet.

**Comment by wukko** [comment]
added in v10!
