### ISSUE TITLE
Feature - First Focus

### ISSUE THREAD

**Issue by prafullmaru** [imputnet/cobalt#546]
**When user visits tool, text box to paste link should get auto focus**
Today when we visit tool, by default none of the control is active, making feel like on click of any button application will become active.

**Set text box with auto focus after first render**
a clear and concise description of any alternative solutions or features you've considered.

**Below is comparision**
![Comparision](https://github.com/imputnet/cobalt/assets/105120779/f312a52d-9de8-4573-8f3b-23b04cc7c6d4)

**Comment by ihatespawn** [comment]
you can click control on your keyboard to focus it for now if you don't want to use your mouse

**Comment by wukko** [comment]
cobalt already automatically focuses the input field when you press ctrl/cmd, what exactly do you want to be done differently?

**Comment by ihatespawn** [comment]
> cobalt already automatically focuses the input field when you press ctrl/cmd, what exactly do you want to be done differently?

this person wants the input field to automatically focus when you visit the page

**Comment by wukko** [comment]
> automatically focus when you visit the page

why? what's the point if it gets focused once you press ctrl/cmd to paste the link?

**Comment by ihatespawn** [comment]
> why? what's the point if it gets focused once you press ctrl/cmd to paste the link?

idk dont ask me, ask @prafullmaru

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by prafullmaru** [comment]
@wukko - In ideal, first action on site for me will be paste link. If textbox will not be focused, in that case user will have to bring textbox to active state and then paste it(when using keyboard and not UI button). So if we will have textbox focused, it will reduce one unnecessary click in textbox. Considering this as better in terms of UX.

**Comment by lostdusty** [comment]
You can just paste the link the moment you access cobalt

**Comment by ihatespawn** [comment]
> @wukko - In ideal, first action on site for me will be paste link. If textbox will not be focused, in that case user will have to bring textbox to active state and then paste it(when using keyboard and not UI button). So if we will have textbox focused, it will reduce one unnecessary click in textbox. Considering this as better in terms of UX.

IT WILL BE ACTIVE when you CLICK CTRL ON YOUR KEYBOARD AND YIOU PASTE USING **CTRL** +V!!!@!@!

**Comment by prafullmaru** [comment]
I see, hitting Ctrl brings focus.
Just give thought from perceptive of user who don't know.
Ideal case - Just hitting Ctrl should bring shortcut options and should not perform any action itself.

If agree, we have changes in PR, else we can close this issue.

**Comment by ihatespawn** [comment]
> Just hitting Ctrl should bring shortcut options

It's made to make it easy to paste, not to show shortcut options, for it could be `Ctrl` + `/` but never `Ctrl`.
