### ISSUE TITLE
Spotty issues with YouTube downloads on main instance

### ISSUE THREAD

**Issue by dumorando** [imputnet/cobalt#548]
**bug description**
no yt videos will download. all of them say "this youtube video is unavailable. it could be age or region restricted. try another one!"

**reproduction steps**
steps to reproduce the behavior:
1. go on cobalt.tools
2. download this video: any video from youtube
3. see error

**screenshots**
if applicable, add screenshots or screen recordings to help explain your problem.
![image](https://github.com/imputnet/cobalt/assets/144301348/b70138e6-277c-456f-b718-330333f7cbc6)
on https://www.youtube.com/watch?v=vclMrjci1rs for testing
same thing happens on https://www.youtube.com/watch?v=XvCMv-oP8vc
and any other youtube link
![image](https://github.com/imputnet/cobalt/assets/144301348/5c3fd474-2b00-463b-9e01-179866fa6f97)
network tab

**links**
if applicable, add links that cause the issue. more = better.

**platform**
- OS [e.g. iOS, windows] arch linux
- browser [e.g. chrome, safari, firefox] firefox
- version [e.g. 115] 126

**additional context**
add any other context about the problem here.

**Comment by lyh1028** [comment]
same error

**Comment by lostdusty** [comment]
youtube seems to be ratelimiting cobalt. try other instances in https://instances.hyper.lol

**Comment by dumorando** [comment]
oh

**Comment by wukko** [comment]
> ratelimiting cobalt

not sure if that's the case, i feel like ipv6 network is dying yet again

**Comment by prajeshElEvEn** [comment]
I couldn't agree less. Youtube is rate limiting cobalt!
I tried to download [this](https://www.youtube.com/watch?v=m9FTcLnL-L0) from [here](https://cobalt.tools/), and cobalt says that the `video is unavailable`. Hence, I tried the [one of the other instance](https://cobalt.wither.ing/) and voila, it works!

Thanks to @lostdusty for [this](https://instances.hyper.lol/).

Hereby I'm also attaching a screenshot for the same.

![Screenshot from 2024-06-07 12-44-00](https://github.com/imputnet/cobalt/assets/75523737/f6ce896b-7785-459b-b013-898dacd03e58)

**Comment by wukko** [comment]
seems like invidious is also affected: https://github.com/iv-org/invidious/issues/4734

i wonder if it affects only the web innertube client, maybe using the ios client instead could help?

**Comment by wukko** [comment]
main instance seems to be fine now, will close this issue and open it back up if google goes back to tormenting services that use innertube api

**Comment by wukko** [comment]
spoke too soon 😭
![image](https://github.com/imputnet/cobalt/assets/71202418/562551cb-5455-4dba-b029-aa84e27286f3)

**Comment by wukko** [comment]
recreated the issue with more information and no guesses: #551
