### ISSUE TITLE
Unable to download youtube live videos

### ISSUE THREAD

**Issue by Smasher-1** [imputnet/cobalt#559]
**bug description**
Whenever i try to download a youtube vod i get the "couldn't find anything to download" error, i've tried changing the link to youtu.be and youtube.com but to no success. I also tried changing the codec to h264, av1 and vp9, but that didn't work either

**reproduction steps**
steps to reproduce the behavior:
1. go to 'cobalt tools'
2. download this video: **https://www.youtube.com/live/APE-R7pCAKw?si=C_5mt53IOgCq-c9o**
3. see error

**platform**
- OS: Windows 11
- browser: Firefox
- version: 7.14.4-f3056c6 (cobalt), 126.0.1 (firefox)
**additional context**
it worked with a normal video using h264 (but not with av1)

**Comment by ihatespawn** [comment]
works for me with https://www.youtube.com/live/m-1f4j5A7Gw on default config

**Comment by Jojobinx17** [comment]
The video that you are trying to download is over cobalt's 180 minute max video length. I don't know why it was causing the weird errors though.

**Comment by wukko** [comment]
the video you've linked is indeed longer than main instance's length limit. other (recorded) live videos seem to work. use a different instance that allows longer downloads or host your own!
