### ISSUE TITLE
SoundCloud Blank Files

### ISSUE THREAD

**Issue by veeonthewall** [imputnet/cobalt#561]
**bug description**
Downloads from any SoundCloud link are blank.

**reproduction steps**
steps to reproduce the behavior:
1. Copy any soundcloud song link (ex. https://soundcloud.com/killemilmusic/green-line-ft-marina-p?in=killemilmusic/sets/green-line)
2. Go to cobalt.tools and paste the link with audio selected
3. Press the arrow enter button
4. File downloads as 0 bytes

**screenshots**
<img width="326" alt="Screenshot 2024-06-08 at 11 05 40 AM" src="https://github.com/imputnet/cobalt/assets/105337781/7f4fe12a-eaf2-4a37-aec5-ff5ace727157">

**platform**
- MacOS Ventura 13.5.2
- Brave Browser (Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) (x86_64)](https://brave.com/latest/))

**Comment by wukko** [comment]
fixed, can you try again?

**Comment by veeonthewall** [comment]
Thanks!
