### ISSUE TITLE
youtube: use opus audio format with av1 format & put it in webm container

### ISSUE THREAD

**Issue by sakurayz** [imputnet/cobalt#570]
MP4 (H264+AAC) format is used for resolutions below 1080p, and WebM (VP9/AV1+OPUS) format is used for high-resolution (4k/8k)videos. The sound quality of the AAC format on the YouTube website is lower than that of the OPUS format. av1+aac combo MP4 feels a bit strange 😜

**Comment by github-account1111** [comment]
> The sound quality of the AAC format on the YouTube website is lower than that of the OPUS format.

Citation needed.

In general, AAC is on par or slightly better than Opus for music and on par or slightly worse than Opus for speech. Being an Apple-backed format, AAC also has *far* better compatibility, about on par with that of MP3.

Given that most YouTube downloads are either music or mixed content, I think it would make the most sense to pair all three video codecs with AAC, not just H264.
