### ISSUE TITLE
Instagram API is unaccessible on many instances

### ISSUE THREAD

**Issue by lpwyz** [imputnet/cobalt#572]
Hello, we are unable to obtain the video link for Instagram

For example: 
   https://www.instagram.com/reel/C8N7FIHuENX/?igsh=Znk2azI2MHJwNnk0
   https://www.instagram.com/reel/C4vRLDmrbqq/?igsh=OWxqOXE5NTBvNGp2
   https://www.instagram.com/reel/C7HaVTsOxPp/?igsh=MWU0dWEzdDFzZmw2NA==

**Comment by prabesharyal** [comment]
I am not sure, but what my initial guess for your problem is server and location. Instagram cleverly started restricting content based on location. Like being in Europe, i was not able to download the contents from URL, it showed as `INVALID URL HASH `although it was correct. I was geo restricted. 

So, i shifted my server to San Francisco ultimately everything was working fine as hell.

**Comment by ihatespawn** [comment]
only affects the main instance from my testing, try another instance
https://instances.hyper.lol/

**Comment by wukko** [comment]
> only affects the main instance
it affects all instances with big enough traffic

**Comment by ihatespawn** [comment]
> from my testing

i didn't test every instance, just some

**Comment by wukko** [comment]
please don't reply with unproven assumptions next time

**Comment by ihatespawn** [comment]
> please don't reply with unproven assumptions next time

okay, i just didn't know. i'll be sure to not make that mistake next time

**Comment by wukko** [comment]
it's ok :3

**Comment by tediorelee** [comment]
Hi, about the ig download issue, is there any fix?

I tried to deploy cobalt api and web on my local NAS and fill the cookies.json file but X(twitter) and Instagram still getting "couldn't find any media content" or "content may be region restricted" errors

**Comment by wukko** [comment]
twitter only works for video in case you're trying to download images. you can save images from the app, this functionality isn't needed in cobalt.

there's currently no clear fix for instagram :(

**Comment by tediorelee** [comment]
> twitter only works for video in case you're trying to download images. you can save images from the app, this functionality isn't needed in cobalt.
> 
> there's currently no clear fix for instagram :(

Understood, download x videos with cobalt works fine and I didn't know it only meant for videos...

**Comment by wukko** [comment]
main instance has been mostly fine lately, we cannot do anything more to increase availability at the moment. we've implemented (essentially) all possible ways of getting post info from instagram.

i recommend adding more dummy accounts or changing server IP addresses to ones that aren't blocked by instagram.
