### ISSUE TITLE
Twitter API returns 404, downloading from it is broken

### ISSUE THREAD

**Issue by wukko** [imputnet/cobalt#573]
twitter's graphql api started returning 404 on every request from cobalt a few hours ago. **all instances are affected**.

**update:** the issue is not with request itself, *same exact request* works fine when done with curl. could be something related to fetch/undici?

**Comment by lostdusty** [comment]
instagram is not related to this; instagram also works, but cobalt can't get all links due of instagram/profile restrictions

**Comment by wukko** [comment]
turns out twitter blocked nodejs TLS client fingerprint, this is why curl worked fine while fetch got 404. now cobalt randomizes it just like chrome :)
