### ISSUE TITLE
"m.vk.com" is not a valid service

### ISSUE THREAD

**Issue by ItsYogSothoth** [imputnet/cobalt#576]
When trying to download a video from `m.vk.com` the service is not considered valid, but changing the link to `vk.com` starts video download as expected

**Comment by steffkes** [comment]
just thinking out loud, I'd assume the config 

https://github.com/imputnet/cobalt/blob/21d5b4b8d457c0bfe3dfe17029c235e115957200/src/modules/processing/servicesConfig.json#L33-L37

needs to be extended by a setting like 

https://github.com/imputnet/cobalt/blob/21d5b4b8d457c0bfe3dfe17029c235e115957200/src/modules/processing/servicesConfig.json#L11

but I didn't have a proper look at the code, not even familiar with it at all until now.

**Comment by wukko** [comment]
yeah, it's just missing the m subdomain
