### ISSUE TITLE
More descriptive /api/json response

### ISSUE THREAD

**Issue by im-trisha** [imputnet/cobalt#577]
**describe the feature you'd like to see**
1. I was thinkering with the api, and i had to do an ugly workaround to get the filename, while as far as I'm able to see it could simply be provided in the /api/json request?

2. In the same way, while thinkering with the api, i found (somewhat) difficult to understand if the downloaded media is a video, or an audio file. Couldn't it be as easy as putting a boolean?

**describe alternatives you've considered**
1. Obviously the alternative is to strip it from the content-disposition header got after the GET request to /api/stream
2. I mean, the alternative i see is just getting the file extension and elaborate from that? I'm not sure though

I hope this is not a stupid request nor has it already been asked.
Many thanks!

**Comment by lostdusty** [comment]
I have asked cobalt devs, they told me to get the file name on the http request (you can http HEAD to get the file name without needing to download the media)

**Comment by lostdusty** [comment]
some code i did to get the filename: https://github.com/lostdusty/gualto/blob/eb43cdb54e59fd3acb46c499d39aedb7081f11b8/main.go#L264-L269

**Comment by wukko** [comment]
we could totally add the filename to stream response, i see how it can be useful

**Comment by im-trisha** [comment]
@wukko and what about the api/json response? The endpoint are not as descriptive as they could get, so I'm not sure if its the correct endpoint, but I'd expect from this endpoint every info except the actual file.

And what about the file type?

**Comment by im-trisha** [comment]
@lostdusty seems wonderful! I'll use exactly that for the time being :)
