### ISSUE TITLE
Odnoklassniki (ok.ru) seems broken

### ISSUE THREAD

**Issue by hyperdefined** [imputnet/cobalt#589]
looking at the instance list, all instances fail on Odnoklassniki. something must of changed on their end.

**Comment by ihatespawn** [comment]
can confirm, doesn't work on cobalt.tools, pl.cobalt.best, co.khyernet.xyz, us.cobalt.best, cobalt.wither.ing and probably every other instance

**Comment by hyperdefined** [comment]
Adding this: https://instances.hyper.lol/service/odnoklassniki/
