### ISSUE TITLE
WAV files downloaded with cobalt appear corrupted to some programs.

### ISSUE THREAD

**Issue by inventor7777** [imputnet/cobalt#590]
Hi all! I recently discovered Cobalt and I’m extremely impressed by the fact that it works so well and is completely free! Thanks very much for this awesome tool.

Howver, I have found a bizarre issue with the WAV files that Cobalt downloads. I always add metadata to my sound files (so they show up in Plex and Apple Music correctly with no adjustment). I found the issue when I downloaded my first .WAV file with Cobalt and tried to edit the metadata with my program of choice (mp3tag Mac version) and it simply gave an error. 

<img width="1430" alt="Screenshot 2024-06-26 at 14 38 07" src="https://github.com/imputnet/cobalt/assets/142270525/354c76b4-862a-42ed-9630-53565a59e63a">

“ERROR: Unsupported format or corrupted file”. 

I tried redownloading it, same issue. I even tried a different random SoundCloud song and the same exact thing happened. (I tried with regular MP3 and it worked fine). The files do play fine in all apps.

I thought it must be that WAV was not supported by mp3tag, but on their compatibility list it says that WAV files are supported normally. (I also tried with VLC’s metadata editor, and it just corrupted the files).

So obviously something strange happens to the files when cobalt converts the .opus files to .wav. 

I looked on mp3tag’s forum and the only similar issue I found was when someone’s converter simply changed the .xxx ending and left the file the same, which caused the same error. Could that be related? I could probably convert them myself from .opus, but was hoping not to have to do that.

(My computer is a MacBook M1 (safari technology preview browser) which has always worked well with cobalt in the past. The issue is seen on all SoundCloud (and YouTube) files I have tried. The source files are usually in .opus.)

Thanks! If you need more info let me know.

**Comment by MagesticChicen** [comment]
I have this exact same problem. It's corrupted on almost all tag editing software I have. Phone music playing software too, those WAV files specifically from cobalt cannot be skipped/shuffled too, metadata is impossible to properly edit. 

This issue is definitely a cobalt problem... I hope they fix it.

**Comment by inventor7777** [comment]
@MagesticChicen I’m glad you’ve confirmed my suspicions! I was kind of afraid it was just me :)
Hopefully it can be fixed.

**Comment by wukko** [comment]
it's related to #566. we're working on a fix and it should come out along with the next version!

if it does, i'll let you know here and in #566.

**Comment by MagesticChicen** [comment]
> it's related to #566. we're working on a fix and it should come out along with the next version!
> 
> if it does, i'll let you know here and in #566.

I hugely appreciate this thank you, great stuff!

**Comment by inventor7777** [comment]
Awesome! Thanks!!

**Comment by ItsOpenSourceSoftware** [comment]
Try it on windows

**Comment by inventor7777** [comment]
Don't have any Windows computers

**Comment by MagesticChicen** [comment]
> Try it on windows

All of my testing occured on either Windows or Android so I've got that side covered so it's clearly widespread. Bear in mind this issue doesn't make the WAV file unplayable, it just makes writing any metadata a nightmare and confuses media players. The problem has already been acknowledged by (I assume) a contributor so no further action is required.
