### ISSUE TITLE
Node Start Failed

### ISSUE THREAD

**Issue by Gareryer** [imputnet/cobalt#595]
```
cobalt@usr:~/htdocs/cobalt.website.com$ npm start

> cobalt@7.14.5 start
> node src/cobalt

fatal: not a git repository (or any of the parent directories): .git
node:internal/errors:983
  const err = new Error(message);
              ^

Error: Command failed: git rev-parse --short HEAD
fatal: not a git repository (or any of the parent directories): .git

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:889:11)
    at execSync (node:child_process:961:15)
    at shortCommit (file:///home/cobalt/htdocs/cobalt.website.com/src/modules/sub/currentCommit.js:7:13)
    at file:///home/cobalt/htdocs/cobalt.website.com/src/cobalt.js:16:19
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:474:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:109:5) {
  status: 128,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(69) [Uint8Array] [
      102,  97, 116,  97, 108,  58,  32, 110, 111, 116,  32,
       97,  32, 103, 105, 116,  32, 114, 101, 112, 111, 115,
      105, 116, 111, 114, 121,  32,  40, 111, 114,  32,  97,
      110, 121,  32, 111, 102,  32, 116, 104, 101,  32, 112,
       97, 114, 101, 110, 116,  32, 100, 105, 114, 101,  99,
      116, 111, 114, 105, 101, 115,  41,  58,  32,  46, 103,
      105, 116,  10
    ]
  ],
  pid: 2773,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(69) [Uint8Array] [
    102,  97, 116,  97, 108,  58,  32, 110, 111, 116,  32,
     97,  32, 103, 105, 116,  32, 114, 101, 112, 111, 115,
    105, 116, 111, 114, 121,  32,  40, 111, 114,  32,  97,
    110, 121,  32, 111, 102,  32, 116, 104, 101,  32, 112,
     97, 114, 101, 110, 116,  32, 100, 105, 114, 101,  99,
    116, 111, 114, 105, 101, 115,  41,  58,  32,  46, 103,
    105, 116,  10
  ]
}

Node.js v22.3.0
```

I'm deploying on vps through Node 22 LTS

**Comment by wukko** [comment]
as error implies, you need the .git folder & git installed.

clone the repo [as tutorial says to do](https://github.com/imputnet/cobalt/blob/current/docs/run-an-instance.md#:~:text=clone%20the%20repo%3A%20git%20clone%20https%3A//github.com/imputnet/cobalt), or use a docker image!

**Comment by Gareryer** [comment]
> as error implies, you need the .git folder & git installed.
> 
> clone the repo [as tutorial says to do](https://github.com/imputnet/cobalt/blob/current/docs/run-an-instance.md#:~:text=clone%20the%20repo%3A%20git%20clone%20https%3A//github.com/imputnet/cobalt), or use a docker image!

This is the exact guide I followed & I think the folder is present
![Screenshot 2024-06-29 at 13-51-53 CloudPanel File Manager](https://github.com/imputnet/cobalt/assets/126243956/6d01076b-4440-4a21-b118-8bf6665a1a18)

**Comment by wukko** [comment]
it's not, there's no `.git` folder

**Comment by wukko** [comment]
consider using the docker image instead, it's easier to setup and will update itself.

**Comment by Gareryer** [comment]
> consider using the docker image instead, it's easier to setup and will update itself.

Alright, I will do that now

**Comment by ihatespawn** [comment]
> > consider using the docker image instead, it's easier to setup and will update itself.
> 
> Alright, I will do that now

did you do it? if yes, did it work?

**Comment by Gareryer** [comment]
> > > consider using the docker image instead, it's easier to setup and will update itself.
> > 
> > 
> > Alright, I will do that now
> 
> did you do it? if yes, did it work?

No, the docker method didn't work. I just wish the NodeJs can run successfully with 'npm start'

**Comment by Gareryer** [comment]
> > > > > consider using the docker image instead, it's easier to setup and will update itself.
> > > > 
> > > > 
> > > > Alright, I will do that now
> > > 
> > > 
> > > did you do it? if yes, did it work?
> > 
> > 
> > No, the docker method didn't work. I just wish the NodeJs can run successfully with 'npm start'
> 
> did you get any errors when using the docker method? it works very good for me

docker installation was successful but to bind it with domain that's where am having issue. I'm getting SSL handshake error

**Comment by wukko** [comment]
> I'm getting SSL handshake error

if you're using cloudflare, you must follow their instructions to configure SSL. this is not related to cobalt.
