### ISSUE TITLE
enable downloading of mature videos on vimeo

### ISSUE THREAD

**Issue by squeak5476** [imputnet/cobalt#596]
writing to request a feature that would allow users to download mature-rated videos on vimeo. currently, currently only supports the downloading of general content videos, but this capability does not extend to videos marked as mature. enabling this feature would greatly enhance user experience

Sample video; https://vimeo.com/958786779

**Comment by ihatespawn** [comment]
watching mature videos requires an account so that's why it doesn't work now

**Comment by wukko** [comment]
the video link no longer works, but vimeo functionality has been fixed in #612. if the issue persists, reply with a fresh link and ill reopen the issue.

**Comment by ihatespawn** [comment]
fresh link: https://vimeo.com/973212054
