### ISSUE TITLE
bilibili.tv links not working

### ISSUE THREAD

**Issue by astralblasters** [imputnet/cobalt#597]
### bug description
pasting a bilibili.tv link into cobalt gives me an error saying that it could not see anything to download at the link (screenshot below). i thought it might be because the video is not available in my area but even when i switch my vpn location it gives me the same error. it worked fine back in march even when the video was unavailable so im not sure what happened. attempted with multiple videos and none of them worked

### reproduction steps
steps to reproduce the described behavior.  
here's an example of what it could look like:
1. go to any video on bilibili.tv
2. copy video link
3. download video from bilibili.tv
4. see error

### screenshots
![Screenshot 2024-06-29 122200](https://github.com/imputnet/cobalt/assets/174201850/f06ac615-a538-4817-bc01-215d1d533069)

### links
links i was attempting to use, but also tried some videos on the bilibili.tv homepage and got the same thing
https://www.bilibili.tv/en/video/4790932516380160
https://www.bilibili.tv/en/video/4790831323283456
https://www.bilibili.tv/en/video/4790831319752192

### platform information
- OS: windows
- browser: firefox, chrome
- version: firefox 127.0.2, chrome 126.0.6478.127

**Comment by ihatespawn** [comment]
probably something related to the location of the server, an instance in poland, japan and uk downloads it normally but a server in us returns an error

**Comment by dumbmoron** [comment]
all of the links download fine for me, it's most likely a regional IP issue
