### ISSUE TITLE
Delete Closed Pull Request

### ISSUE THREAD

**Issue by ilyastahari** [imputnet/cobalt#602]
Are you able to delete the closed pull request that I made yesterday? I didn't mean to do it and would rather not have it on my profile. Would be greatly appreciated! The URL is https://github.com/imputnet/cobalt/pull/599

**Comment by wukko** [comment]
nope, you'll have to live with the fact that you forked cobalt. btw, you have to link the modified source code repo on the website.

**Comment by ilyastahari** [comment]
sounds good, i have no problem with that. i just accidentally did a pull request (first timer, i didn't know what i was doing lol) and i wanted to delete the closed pull request since it was an accident that's all. is that something you can do on your end?

**Comment by wukko** [comment]
i think github needs a very specific reason to delete a pull request (such as if it contained sensitive personal data), but it's not the case here. i'll see what i can do in a bit

**Comment by ilyastahari** [comment]
thanks i appreciate that
