### ISSUE TITLE
Vimeo no longer seems to be working

### ISSUE THREAD

**Issue by hyperdefined** [imputnet/cobalt#603]
https://instances.hyper.lol/instance/34e1cba7cf/
Main instance fails for Vimeo and has been for a few days. If you check other instances, Vimeo is failing on all.

This is the test media: https://vimeo.com/936245676. Trying it manually also fails.

**Comment by hyperdefined** [comment]
Adding this: https://instances.hyper.lol/service/vimeo/

**Comment by wukko** [comment]
closed by #612
