### ISSUE TITLE
access to the main instance API redirects to blocked.cobalt.tools from script

### ISSUE THREAD

**Issue by madkarmaa** [imputnet/cobalt#605]
Hey there, I'm the developer of [madkarmaa/youtube-downloader](https://github.com/madkarmaa/youtube-downloader), also hosted on [Greasy fork](https://greasyfork.org/scripts/479944). I've just received [an issue](https://github.com/madkarmaa/youtube-downloader/issues/9) reporting the script to be blocked by the Cobalt API and showing a message from the domain [blocked.cobalt.tools](https://blocked.cobalt.tools/). I'm here to ask why has it been blocked by you, since I'm clearly stating in the repository's GitHub README that the script uses the Cobalt API, I don't abuse it for any checks, using it for downloads only, and I also don't get any revenue out of the project. If there's anything I did wrong, I'm very happy to fix it.

**Comment by wukko** [comment]
hey! i’ve unblocked it, can you try if it works now? our security filter has accidentally misfired, sorry for the inconvenience.

**Comment by madkarmaa** [comment]
thank you very much for the insane reply speed :) it works now, thank you again, and, awesome project!

**Comment by wukko** [comment]
you’re welcome!
