### ISSUE TITLE
couldn't get this youtube video because it requires an account to view.

### ISSUE THREAD

**Issue by michelleDeko** [imputnet/cobalt#617]
Hi,

since some days I can't download YouTube Videos anymore because of following error:
```
couldn't get this youtube video because it requires an account to view.

this limitation is done by google to seemingly stop scraping, affecting all 3rd party tools and even their own clients.

try again, but if issue persists, check the or .
```

How can I fix this?

**Comment by ihatespawn** [comment]
you can't

just try another instance

https://instances.hyper.lol/service/youtube

**Comment by michelleDeko** [comment]
This error happens with every YouTube Video I tried (for example: https://youtu.be/DrE9umGiPZQ?si=gt-Wp2qXKYodYgRp)
Used it on my server dl.miichelle.moe (that's also listed on the instances list lol), country is Germany

**Comment by ihatespawn** [comment]
every video i tried worked without any problems, very weird.

**Comment by ihatespawn** [comment]
just realised the tag.
it was very late and i forgot to look at it, sorry

youtube just started blocking bost again, maybe you should try changing the ip of the server or just add cookies (this iwll probably get yiur account banned)

**Comment by michelleDeko** [comment]
I think changing the ip of the server wouldn't really work for me lol
How can I add cookies for Youtube (using a throwaway google account)?

**Comment by ihatespawn** [comment]
`node src/util/generate-youtube-tokens` with cobalt's source code open

**Comment by michelleDeko** [comment]
I did this now and added the cookies generate into cookies.json (copied over from the example files) and named it "youtube" inside the cookies.json. But it still doesn't work

**Comment by ihatespawn** [comment]
> add this cookie to the youtube_oauth array in your cookies file

"youtube_oauth" not "youtube"

**Comment by michelleDeko** [comment]
Ok, changed it, but still doesn't work :/

**Comment by wukko** [comment]
there's nothing we can do to help from our side. try updating the docker package and using a different google account, ***NOT YOUR PERSONAL ONE, IT MIGHT GET BANNED***
