### ISSUE TITLE
Getting Youtube oAuth token rate limited every 15 mins

### ISSUE THREAD

**Issue by 2shiraz** [imputnet/cobalt#622]
### problem description

I host cobalt instances on my servers. I am getting my Youtube oAuth timed out/rate limited every 15 mins. After that, I have to replace it with another account token ( currently I replace it with the previously used account token ). I'm just asking here to find out if anyone else getting this too? I saw the main cobalt instances were not affected.

Rate Limited Account : 

![image](https://github.com/imputnet/cobalt/assets/29581110/4c0904e9-4bde-4da6-931b-c55746738887)

ps: I handle around 3 million user/m traffic

**Comment by devilr33f** [comment]
you can use *multiple** youtube accounts and it'll help you to hit the youtube limits less

**Comment by 2shiraz** [comment]
> you can use **multiple** youtube accounts and it'll help you to hit the youtube limits less

I mean I am currently doing this but what I was wonder of some type of shuffle algorithm or something like that which can get first token for 10 mins, then next for the next 10 minutes and so far. Then by having 20ish account, the cooldown can be easily be reached before coming back to the first token. I'ma start building this rn ig

**Comment by wukko** [comment]
if you have several youtube tokens in the cookies file, cobalt will distribute requests between all of them evenly, reducing the probability of each specific one getting rate limited

**Comment by 2shiraz** [comment]
> if you have several youtube tokens in the cookies file, cobalt will distribute requests between all of them evenly, reducing the probability of each specific one getting rate limited

Yes, just figured it out. Didn't know that the rotation algorithm was there till I checked the code. Thanks anyways, saved my day literally!
