### ISSUE TITLE
youtube doesn't work on main instance

### ISSUE THREAD

**Issue by nikunjmishra1998** [imputnet/cobalt#623]
### bug description
Cobalt tools not working for any of the youtube video download

### reproduction steps
steps to reproduce the described behavior.  
here's an example of what it could look like:
1. go to 'cobalt.tools'
2. Paste any of Youtube video link
3. Try to download
4. see error

### screenshots
![image](https://github.com/imputnet/cobalt/assets/84068554/da411228-849a-4e41-8ab1-5a2a6fa80a2a)

**Comment by ihatespawn** [comment]
api works, only youtube doesn't work

**Comment by wukko** [comment]
i can't recreate the issue, can you try again?

**Comment by wukko** [comment]
for future reference: there’s a dedicated template for issues related to the main instance.

if the problem is fixed on your side, close this issue as completed.

**Comment by nikunjmishra1998** [comment]
for local developemt it's still throwing error as shown in attached screen shot
![image](https://github.com/imputnet/cobalt/assets/84068554/2b9afae2-fda8-4236-866c-7b7c11c01fd2)

**Comment by nikunjmishra1998** [comment]
curl --location 'http://localhost:9000/api/json' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--header 'sec-ch-ua: "Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "Windows"' \
--header 'sec-fetch-dest: empty' \
--header 'sec-fetch-mode: cors' \
--header 'sec-fetch-site: cross-site' \
--data '{
    "url": "https://youtu.be/fdhEPblKfdY",
    "aFormat": "mp3",
    "isAudioOnly": true,
    "isNoTTWatermark": true,
    "vQuality": "720"
}'

Above Curl I am using

**Comment by wukko** [comment]
does main instance work or not?

local instance may need a google account token to work

**Comment by nikunjmishra1998** [comment]
Yes, Main instance worked. 

but till before an 2 hour ago local instance also was worked

**Comment by wukko** [comment]
then youtube might have changed something regarding your ip range (i suppose?)

**Comment by nikunjmishra1998** [comment]
it should not because I tried to development today after so long. And I also not made that much amount of request to youtube

**Comment by 2shiraz** [comment]
> it should not because I tried to develop today after so long. And I also not made that much amount of request to youtube

The same happened to me too. I guess YouTube updated something recently as now without a cookie nothing work. So just use cookies ig

**Comment by nikunjmishra1998** [comment]
No, It's Youtubei.js Package update issue. They have updated their package yesterday. So Use the 10.1.0 latest version and it's working without cookie

**Comment by wukko** [comment]
we also updated cobalt to be compatible with the new version yesterday. if you’re running cobalt in a docker container with watchtower, it should’ve updated itself by now.
