### ISSUE TITLE
youtube videos corrupted (kinda)

### ISSUE THREAD

**Issue by Gabril07** [imputnet/cobalt#629]
### bug description
when download videos from youtube, it gets sort of corrupted? I can't send it to other people, it just says "file not compatible"

### reproduction steps
1. just download any youtube video link
2. try to share via whatsapp
3. see error

### screenshots
![file not compatible](https://github.com/user-attachments/assets/92695997-1b7e-42e7-8464-50c31648edb6)

### platform information
- Windows 10
- Google Chrome
- v.7.14.6-2f4e43f 

### additional context
it only happens with youtube links, other than that, it's just fine, at least for me.

**Comment by ihatespawn** [comment]
can't reproduce, everything works good

**Comment by wukko** [comment]
no info provided, may be related to #566

**Comment by aryaoffixial** [comment]
WhatsApp doesn't support any .webm format or the new h264, h265 HEVC Codec videos. It supports only normal mp4 Videos.

> Atleast on my device.

"I think by chance if the dev can enable vp9 for mp4 format videos that will be good for me, you & others too 🙂."
