### ISSUE TITLE
[short feature request description]

### ISSUE THREAD

**Issue by HansGeo** [imputnet/cobalt#630]
### Add Subtitles Support

Hi,

I just tried cobalt to download some yt videos and it works impressingly simple and fast. 
Thank you for providing the service. :))
What about **adding a feature to download subtitles?**
Having subtitles on, facilitates listening to lengthy video-talks.
I myself am not into coding. So I have to rely on cobalt coders.

Hope you think it over.
Thank you
 
best whishes
Hans

**Comment by ihatespawn** [comment]
[short response related to the issue]

**Comment by ihatespawn** [comment]
okay but actually this is a duplicate of #368
