### ISSUE TITLE
How to download at least 180 minutes of a too-long video 

### ISSUE THREAD

**Issue by Tintin232** [imputnet/cobalt#631]
### bug description
Not really a bug, but I want to know if it's possible to download the first (or middle/last) 180 minutes of a video that is otherwise too long to download the whole thing.

### screenshots
![Screenshot_20240713_163115_Chrome](https://github.com/user-attachments/assets/cf954b71-b7e4-4a74-998c-aeebc8ca664a)

### platform information
- OS Android
- browser Chrome
- version 126

**Comment by wukko** [comment]
clipping is not currently possible, see #375 feature request

**Comment by Tintin232** [comment]
I see. Thanks for the response.
