### ISSUE TITLE
"Save As" Option

### ISSUE THREAD

**Issue by yunus-cakir** [imputnet/cobalt#633]
Hi!
Is there possible to make a "Save As" toggle in the options? I know I can enable it with my browser settings but I use cobalt a lot and I need to categorize and rename what I am downloading, It would be so nice to have that!

**Comment by wukko** [comment]
if you mean filenames, then you can change the preset in settings -> other!

**Comment by yunus-cakir** [comment]
> if you mean filenames, then you can change the preset in settings -> other!
Hi Wukko! I'm categorizing all of the musics, sounds, videos, green screens with specific folders and I rename the most of it, I know its probably only for me but I'd be very happy if you bring such a feature when you have time :)

**Comment by wukko** [comment]
you're supposed to fill out the issue template, not remove it. please either copy the template into this issue and fill it out, or make a new one.
