### ISSUE TITLE
"Save As" Toggle Feature

### ISSUE THREAD

**Issue by yunus-cakir** [imputnet/cobalt#635]
### describe the feature you'd like to see
Hi! I'm downloading a lot of sound effects, videos, green screens to my "Materials" folder. I was using another downloader and I saw cobalt is much more simple and fluent but when I download any items, all files goes to the Downloads and some of the video titles can be too long and unnecessary.
So I thought It would be great to see a "Save As" pop up when I click the button on Cobalt website. I can pick any subfolder that I want and I can rename it then!

### additional context
![image](https://github.com/user-attachments/assets/74ca127d-71f1-4ea2-9e3c-a2692fc9892c)
![image](https://github.com/user-attachments/assets/79c6e26b-2b26-46df-9fb5-24e20034d5bb)
![image](https://github.com/user-attachments/assets/ef16e695-4764-4d18-9163-221ca06114f6)

**Comment by wukko** [comment]
you can change this behaviour in your browser settings!
chrome: settings -> downloads -> "ask where to save each file before downloading"
firefox: settings -> scroll down till "files and applications" -> "always ask you where to save files"

**Comment by PoketrainerMS** [comment]
the setting is here in opera, ita pretty far down in Advanced settings
![Screenshot 2024-08-16 at 3 32 44 PM](https://github.com/user-attachments/assets/a5e743b3-de71-478a-a78d-9f6b167b8cd4)
idk what browser you use so idk if this helps
but yeah its a browser thing usually

**Comment by wukko** [comment]
this is a browser setting, you can find more info by searching "how to make {browser} ask where to save each file". replace {browser} with the name of a browser you use (such as chrome, firefox, edge, etc)
