### ISSUE TITLE
Can't download audio of specific YouTube video

### ISSUE THREAD

**Issue by LubiePlackiXD234** [imputnet/cobalt#636]
### bug description
a specific link does not work on multiple devices.

### reproduction steps
1. go to (https://cobalt.tools)
2. paste the link https://www.youtube.com/watch?v=iPgKA99mumI
3. choose the audio download option if its not already chosen
4. press the double arrow button to download
5. see the error "i couldn't find anything to download with your settings. try another codec or quality in settings!"
playing with the settings does nothing.

### screenshots
![image](https://github.com/user-attachments/assets/bbe7e0cf-031b-4f18-97f9-2a662db547d3)

### links
https://cobalt.tools
https://www.youtube.com/watch?v=iPgKA99mumI

### platform information
- windows and android
- opera on windows and chrome on android

**Comment by SpiritAxolotl** [comment]
download works for me on the h264 codec. are you trying to use the other two codecs? (vp9 and av1)

**Comment by lostdusty** [comment]
they're trying to download audio, not video

**Comment by lostdusty** [comment]
I also could reproduce the issue

**Comment by wukko** [comment]
seems to be working fine now:
<img width="351" alt="image" src="https://github.com/user-attachments/assets/73a50b31-ab06-4600-816f-9721ecf72b7c">
