### ISSUE TITLE
How do I force IPv6 on my instance?

### ISSUE THREAD

**Issue by hamaadraza** [imputnet/cobalt#641]
### problem description
How do I force cobalt to use ipv6 for all it's request. I don't want use the freebind cidr which I think uses a random ip from a ipv6 subnet. i only want to use the ipv6 assinged to server. Any way to do that ?

**Comment by wukko** [comment]
this is done outside of cobalt, you can use google to search: https://www.google.com/search?q=how+to+force+ipv6+on+linux

**Comment by dumbmoron** [comment]
it's also not very practical, since a good portion of the services don't even support IPv6

**Comment by hamaadraza** [comment]
Well I have a written a script that rotates my ipv6 address within the assigned subnet to my server every 2 hours or so. I don't want lose my ipv4 connectivity of server also by disabling it. It would be really helpful if we can add an option to cobalt to use ipv6 only for requests. And yes most services don't support ipv6 but youtube does.
