### ISSUE TITLE
YouTube download is interrupted before full video is downloaded

### ISSUE THREAD

**Issue by alexz1205** [imputnet/cobalt#647]
### bug description
Basically the title. Most of the time, my downloads stop before the full video is downloaded.

### reproduction steps
I've had this issue with every link I've tried, though that isn't much.

### screenshots
![image](https://github.com/user-attachments/assets/86a4d386-04cf-44b1-be37-f10c261d951a)
These are all downloads of the same video that have stopped before the full video is downloaded. 

### platform information
- Windows Build 22631.3880
- Chrome Version 126.0.6478.182 (Official Build) (64-bit)

**Comment by ihatespawn** [comment]
https://x.com/justusecobalt/status/1814850869138985418
![image](https://github.com/user-attachments/assets/ed171794-272b-4abb-8f03-3a788129dc57)

**Comment by ai5bal** [comment]
Yep same issue here.

**Comment by Tintin232** [comment]
Any update about a fix for this issue? It's still plaguing me 😢.

**Comment by wukko** [comment]
last fix lasted for a few weeks, but i guess youtube changed something once again last evening. videos get cut off because youtube starts randomly returning 403 to streams, which is completely unpredictable from our side.

**Comment by Tintin232** [comment]
Gotcha

**Comment by arandomhooman** [comment]
You can use another downloaded for now. If you can use command line, use yt-dlp, if only website use ddownr or y2mate

**Comment by invadermoth** [comment]
> You can use another downloaded for now. If you can use command line, use yt-dlp, if only website use ddownr or y2mate

Well, issue is that I use Cobalt at school and a lot of other websites are blocked. I kind of have to use Cobalt :<

**Comment by wukko** [comment]
pretty sure that the issue got fixed by #867 and #879 🎉

if long videos still get cut off (couldn’t replicate it since the update), enabling hls should help: https://cobalt.tools/settings/video#youtube-hls

**Comment by Sainan** [comment]
Seems to be an issue again without enabling HLS, e.g. `https://www.youtube.com/watch?v=0b_1GADtPnQ` can't get past 30-40 minutes.

**Comment by TrilobiteFaye** [comment]
oh whoops i just opened an issue about exactly this same problem

**Comment by Twten** [comment]
This is still a problem

**Comment by wukko** [comment]
> if long videos still get cut off (couldn’t replicate it since the update), enabling hls should help: https://cobalt.tools/settings/video#youtube-hls

**Comment by Twten** [comment]
What about downloading a youtube video to mp3? Stops downloading early between 500kb and 16mb

**Comment by wukko** [comment]
the hls toggle applies globally, including audio too.

**Comment by Twten** [comment]
I have the hls toggle on, and it's still cutting mp3 downloads short

**Comment by wukko** [comment]
then make a new issue using an appropriate template and fill out all necessary info!

**Comment by Twten** [comment]
seems as if i'm only having this issue. i'm using firefox and tried to replicate it on chrome and it didn't happen. asked my friend who uses firefox and it didn't happen either. just a weird anomaly for me. sorry.
