### ISSUE TITLE
Add support for paginated video links from bilibili

### ISSUE THREAD

**Issue by hiker90** [imputnet/cobalt#648]
### bug description
Paginated video downloads are not supported on bilibili，no matter which link I copied, I only got to download the first video

### reproduction steps

1. open a paginated vedio on bilibili.com
2. select any vedio except the first one
3. the url is like "http://www.bilibili.com/****?p=2", which has a query of page info
4. past the url in https://cobalt.tools/, and i always got the first video

### screenshots
if applicable, add screenshots or screen recordings to support your explanation.  
if not, remove this section.

### links
if applicable, add links that cause the issue. more = better.  
if not, remove this section.

### platform information
- OS [e.g. iOS, windows]
- browser [e.g. chrome, safari, firefox]
- version [e.g. 115]

### additional context
add any other context about the problem here if applicable.  
if not, remove this section.

**Comment by KwiatekMiki** [comment]
can you give example links

**Comment by wukko** [comment]
can't work on this request without example links
