### ISSUE TITLE
Can't download videos on main instance

### ISSUE THREAD

**Issue by FireToaster** [imputnet/cobalt#655]
I tried downloading an unlisted video from YouTube, but it just doesn't work, even on all video and sound formats.

**Comment by SpiritAxolotl** [comment]
link to the video?
and if you'd rather not, what error are you getting?

**Comment by FireToaster** [comment]
I've tried multiple videos but here is one https://www.youtube.com/watch?v=b4WpE-aCR2k and it shows the traditional error, "this youtube video is unavailable. it could be visibility or region restricted. try another one!"

**Comment by SpiritAxolotl** [comment]
yeah some videos are region restricted. try downloading it with yt-dlp instead (search it on github)

**Comment by wukko** [comment]
just fixed it, go try it!
