### ISSUE TITLE
Option for self hosters to use account with Youtube

### ISSUE THREAD

**Issue by polygondev** [imputnet/cobalt#656]
### describe the feature you'd like to see
because youtube has been requiring you to sign in to download videos from some ips (including my server), there should be an option to log in an account when downloading from youtube (possibly using environment variables or using oauth, though this may be annoying to implement)

**Comment by polygondev** [comment]
nevermind, I found the solution elsewhere

**Comment by wukko** [comment]
the solution for cobalt is:
1. generating a youtube oauth token with `npm run token:youtube` (built into cobalt)
2. following instructions to add the cookie to your cookies file

**Comment by polygondev** [comment]
thanks. because it's a cookie, i assume i need to do this on every device, because i can't find where i would set it to automatically apply to every device

**Comment by wukko** [comment]
`cookies.json` file is stored exclusively on your server and never seen by anyone else
