### ISSUE TITLE
中文区支持 feature request

### ISSUE THREAD

**Issue by cxwx** [imputnet/cobalt#660]
add support to 
- [ ] 微博(china)
- [ ] 抖音(china)
- [ ] 快手(china)
- [ ] 其他...

**Comment by wukko** [comment]
we need sample links for each service. link every possible link pattern you can find

**Comment by ihatespawn** [comment]
> * [ ]  抖音(china)

已经有一个关于抖音的请求 (#332)

**Comment by ihatespawn** [comment]
@wukko would you be fine with me seperating this into 2 seperate issues for every service?

**Comment by ihatespawn** [comment]
also, you used the wrong template (you're supposed to select service request not feature request) and didn't even fill it out

**Comment by wukko** [comment]
if you want all of these services supported, please create a new issue using a proper template. we don't have any links to support in this one.
