### ISSUE TITLE
"this youtube video is unavailable" Why?

### ISSUE THREAD

**Issue by smoressy** [imputnet/cobalt#662]
### bug description
cobalt.tools gives me "this youtube video is unavailable" for youtube vods i can watch right now
### reproduction steps
steps to reproduce the described behavior.  
here's an example of what it could look like:
1. go to 'a music video'
2. click on 'copy the url'
3. download [audio] from [youtube]
4. see error

### links
if applicable, add links that cause the issue. more = better.  
if not, remove this section.
https://www.youtube.com/watch?v=vY5ZP6kIWdU

### platform information
- OS [Windows]
- browser [Chrome]
- version [Latest]

### additional context
pls add support for all youtube vids or use more proxies to get around this error

**Comment by wukko** [comment]
fixed
