### ISSUE TITLE
youtube playlist won't download 

### ISSUE THREAD

**Issue by sherif-audibene** [imputnet/cobalt#664]
### bug description
When trying to download a youtube playlist from my favourite game, it show that it needs an accoung
### reproduction steps
steps to reproduce the described behavior.  
here's an example of what it could look like:
1. go to 'home page'
2. paste this link "https://www.youtube.com/watch?v=XSMahjdpQ9k&list=PLhaCXeA_nfD0FwbRL7aF6xaXCT9JXrBi9&ab_channel=uThermal"
3. download [media type] from [youtube]
4. see error

### screenshots
if applicable, add screenshots or screen recordings to support your explanation.  
if not, remove this section.

### links
if applicable, add links that cause the issue. more = better.  
if not, remove this section.

### platform information
- OS [e.g. iOS, windows]
- browser [e.g. chrome, safari, firefox]
- version [e.g. 115]

### additional context
add any other context about the problem here if applicable.  
if not, remove this section.

**Comment by wukko** [comment]
does this happen on cobalt.tools?

**Comment by wukko** [comment]
what’s the issue? you haven’t filled out the template

**Comment by wukko** [comment]
the link you've provided works on https://cobalt.tools and i have no clue what you're talking about
