### ISSUE TITLE
Entire Youtube Video not downloading 

### ISSUE THREAD

**Issue by ai5bal** [imputnet/cobalt#665]
### bug description
I am trying to download 1hr40m of footage from youtube, but it always downloads a small portion of 15-20mins and not the entire thing.

### reproduction steps
steps to reproduce the described behavior.  
here's an example of what it could look like:
1. go to cobalt.tools
2. copy and paste the link
3. download 1080p, h264 youtube footage from cobalt.tools
4. see error: only 150-250mb gets downloaded.

### platform information
- macOS
- Chrome
- version [e.g. 115]

### additional context
This issue happened a couple of days ago as well, but was easily resolved back then by attempting to download footage again, which helped download the entire video. Now it doesn't work.

**Comment by dumbmoron** [comment]
#647
