### ISSUE TITLE
PHP Library for Cobalt API

### ISSUE THREAD

**Issue by code3-dev** [imputnet/cobalt#666]
Hello,
I have created a PHP library based on your Cobalt API. You can find it here: [ytdl-php](https://github.com/code3-dev/ytdl-php).

I believe this library can be a useful addition to the ecosystem around your project, and I'd love to get any feedback or suggestions you may have.

Thank you for your work on Cobalt!

Best regards,
Hossein Pira.

**Comment by wukko** [comment]
you have to mention that it relies on cobalt’s free api on top of readme

**Comment by wukko** [comment]
you’ve also copied parts of our docs, you have to mention sources for that, too

**Comment by code3-dev** [comment]
> you’ve also copied parts of our docs, you have to mention sources for that, too

Ok, I add all sources. thanks

**Comment by wukko** [comment]
thank you :D

**Comment by code3-dev** [comment]
and thank you very much

**Comment by wukko** [comment]
stop spamming the repo please
