### ISSUE TITLE
package.json links a git:// dependency that can't be used without authentication

### ISSUE THREAD

**Issue by sertraline** [imputnet/cobalt#667]
### bug description
This commit https://github.com/imputnet/cobalt/commit/6626d74746b88420ec80e6b707a8d7cd01a4f5d9 has linked `youtubei.js` to a commit, but the URL starts with git://.

The issue is that unauthenticated git users will be unable to run `npm install` or `yarn install`, as [Github does not allow unauthenticated users to use the 9418 port](https://github.blog/security/application-security/improving-git-protocol-security-github/).  

The solution is to replace `git://` with `https://`.

### screenshots
![image](https://github.com/user-attachments/assets/9cd76997-fd27-4988-835b-025e29661be4)

Moreover, this commit fails to build. Relevant bug report: https://github.com/LuanRT/YouTube.js/issues/716

![image](https://github.com/user-attachments/assets/4680d5ed-b087-4c5a-8766-2ae24b5c9e6b)

**Comment by wukko** [comment]
i've updated the dependency to npm package version that includes the needed commit in [50f312f](https://github.com/imputnet/cobalt/commit/50f312fc71a55e3bfbb32d39fe1f32cf938526a0), so the issue should be resolved now

**Comment by wukko** [comment]
lmk if it's actually fixed

**Comment by sertraline** [comment]
it is fixed. Thanks
