### ISSUE TITLE
Cookies & oAuth Error

### ISSUE THREAD

**Issue by hextor1** [imputnet/cobalt#677]
**cookies.json:**
{
  "youtube_oauth": [
    "access_token=xxxxxx; refresh_token=xxxxx; scope=https://www.googleapis.com/auth/youtube-paid-content https://www.googleapis.com/auth/youtube; token_type=Bearer; expiry_date=2024-08-09T08:12:07.911Z"
  ]
}

**.env**
`API_URL=https://api.mywebsitename.net/
API_PORT=9004
API_NAME=eu-nl
COOKIE_PATH=/cookies.json`

**Error I am facing** 

{
    "status": "error",
    "text": "couldn't get this youtube video because it requires an account to view.<br><br>this limitation is done by google to seemingly stop scraping, affecting all 3rd party tools and even their own clients.<br><br>try again, but if issue persists, check the <a class=\"text-backdrop link\" href=\"https://status.cobalt.tools/\" target=\"_blank\">status page</a> or <a class=\"text-backdrop link\" href=\"https://github.com/imputnet/cobalt\" target=\"_blank\">create an issue on github</a>."
}

**Comment by KwiatekMiki** [comment]
> [!] The token generated by this script is sensitive and you should not share it with anyone!

you just shared a sensitive token.

you should remove it from the comment out and remove the original version

**Comment by wukko** [comment]
***immediately*** change the google account password and revoke all sessions, why did you ignore security warnings?

**Comment by wukko** [comment]
do not ever post cookies file contents ANYWHERE

**Comment by hextor1** [comment]
bro please give me the solution now I removed my cookie

> do not EVER post contents of your cookies file ANYWHERE

**Comment by dumbmoron** [comment]
your cookies file is probably located elsewhere than `/cookies.json` on the filesystem

**Comment by hextor1** [comment]
> your cookies file is probably located elsewhere on the filesystem other than `/cookies.json`

Please see here is my file location I cannot find anything I just created cookie.json file from my side

![image](https://github.com/user-attachments/assets/40de0b96-fa76-4a4d-b564-2a3a3d77453a)

**Comment by hextor1** [comment]
> your cookies file is probably located elsewhere on the filesystem other than `/cookies.json`

Please see I am facing an error when testing an API in local server because of youtube oauth so please guide me about my cookie
![image](https://github.com/user-attachments/assets/47bcfe3e-7f45-4be3-8c40-b754533c6b7a)

**Comment by dumbmoron** [comment]
<img width="972" alt="Screenshot 2024-08-08 at 14 51 36" src="https://github.com/user-attachments/assets/4d3606bd-1879-4776-b292-2f6bbe18d545">

**Comment by KwiatekMiki** [comment]
your screenshot isn't working

**Comment by KwiatekMiki** [comment]
> Getting same error when uncomment the volumes and next line

could you send them here?

(also for the last message I forgot quoting exists)

**Comment by hextor1** [comment]
![image](https://github.com/user-attachments/assets/bb63b787-da86-4668-82e5-c27136e41d93)

Same error @dumbmoron

**Comment by hextor1** [comment]
> your screenshot isn't working

Refresh your page my screenshot is showing

**Comment by hextor1** [comment]
@wukko Hi bro i am delte my previous issue please check it here
