### ISSUE TITLE
twitter age restricted video test fails because account is private

### ISSUE THREAD

**Issue by KwiatekMiki** [imputnet/cobalt#679]
### bug description
the account @/FckyeahCharli is now private so the test will always fail

### reproduction steps
steps to reproduce the described behavior.  
here's an example of what it could look like:
1. clone cobalt
2. do `npm test`
3. wait until the 'age restricted video' twitter test fails
4. see error

### screenshots
![image](https://github.com/user-attachments/assets/874fddd5-7e60-4107-acf4-82f78f020597)

### links
https://twitter.com/FckyeahCharli/status/1650987582749065220
https://github.com/imputnet/cobalt/blob/current/src/util/tests.json#L114C8-L123C6

### platform information
- Pop!_OS
- browser and version don't matter here

**Comment by wukko** [comment]
you need to provide dummy twitter account cookies for this

**Comment by KwiatekMiki** [comment]
still fails (because i'm not following that account)

**Comment by wukko** [comment]
the account is private forever
