### ISSUE TITLE
cookie.json is not working

### ISSUE THREAD

**Issue by hextor1** [imputnet/cobalt#680]
**I am facing this issue when i am trying to download mp3/mp4 and youtube showing an oauth error** 

{
    "status": "error",
    "text": "couldn't get this youtube video because it requires an account to view.<br><br>this limitation is done by google to seemingly stop scraping, affecting all 3rd party tools and even their own clients.<br><br>try again, but if issue persists, check the <a class=\"text-backdrop link\" href=\"https://status.cobalt.tools/\" target=\"_blank\">status page</a> or <a class=\"text-backdrop link\" href=\"https://github.com/imputnet/cobalt\" target=\"_blank\">create an issue on github</a>."
}

**Here is my docker compose file code:**

version: '3.5'

services:
    cobalt-api:
        image: ghcr.io/imputnet/cobalt:7
        restart: unless-stopped
        container_name: cobalt-api

        init: true

        # if container doesn't run detached on your machine, uncomment the next line
        #tty: true

        ports:
            - 9005:9005/tcp
            # if you're using a reverse proxy, uncomment the next line and remove the one above (9000:9000/tcp):
            #- 127.0.0.1:9000:9004

        environment:
            # replace https://api.cobalt.tools/ with your instance's target url in same format
            API_URL: "https://api.sssyoutube.net/"
            API_PORT: "9005"
            # replace eu-nl with your instance's distinctive name
            API_NAME: "eu-nl"
            # if you want to use cookies when fetching data from services, uncomment the next line and the lines under volume
            COOKIE_PATH: "/cookies.json"
            # see docs/run-an-instance.md for more information
        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

        # if you want to use cookies when fetching data from services, uncomment volumes and next line
        volumes:
            - ./cookies.json:/cookies.json

    cobalt-web:
        image: ghcr.io/imputnet/cobalt:7
        restart: unless-stopped
        container_name: cobalt-web

        init: true

        # if container doesn't run detached on your machine, uncomment the next line
        #tty: true

        ports:
            - 9006:9006/tcp
            # if you're using a reverse proxy, uncomment the next line and remove the one above (9001:9001/tcp):
            #- 127.0.0.1:9001:9001

        environment:
            # replace https://cobalt.tools/ with your instance's target url in same format
            WEB_URL: "https://sssyoutube.net/"
            # replace https://api.cobalt.tools/ with preferred api instance url
            API_URL: "https://api.sssyoutube.net/"
            WEB_PORT: "9006"

        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

    # update the cobalt image automatically with watchtower
    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobalt --interval 900 --include-restarting
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            
  **Here is my cookie.json code i hide my cookie**
 {
    "youtube_oauth": [
        "xxxx"
    ]
}

![image](https://github.com/user-attachments/assets/b3a61982-2094-46ba-8e92-47e62fb2fc5d)

**Comment by wukko** [comment]
why would you delete the previous issue?

**Comment by wukko** [comment]
i will not provide further support and am locking the conversation
