### ISSUE TITLE
Resolving YouTube Video Download Errors in Cobalt: Account Cookie Required?

### ISSUE THREAD

**Issue by wenjuming** [imputnet/cobalt#683]
I deployed Cobalt on the Cobalt server to download YouTube videos, but encountered an error. The error message suggests that the video requires an account to view. Should this be resolved by using a logged-in account's cookie, or is there another solution? The error is as follows:{'status': 'error', 'text': 'couldn\'t get this youtube video because it requires an account to view.<br><br>this limitation is done by google to seemingly stop scraping, affecting all 3rd party tools and even their own clients.<br><br>try again, but if issue persists, check the <a class="text-backdrop link" href="https://status.cobalt.tools/" target="_blank">status page</a> or <a class="text-backdrop link" href="https://github.com/imputnet/cobalt" target="_blank">create an issue on github</a>.'}

**Comment by wukko** [comment]
`npm run token:youtube`

**Comment by Elite** [comment]
> `npm run token:youtube`

Will using this work on a public facing instance with thousands of downloads daily without getting the "Sign in" roadblock?

**Comment by KwiatekMiki** [comment]
> > `npm run token:youtube`
> 
> Will using this work on a public facing instance with thousands of downloads daily without getting the "Sign in" roadblock?

yes

**Comment by Elite** [comment]
> KwiatekMiki

Using a single ip or with freebind support?
