### ISSUE TITLE
In recent days YouTube downloads fail

### ISSUE THREAD

**Issue by fungja005** [imputnet/cobalt#688]
YouTube video downloads fail

![IMG_7038](https://github.com/user-attachments/assets/afc11996-c318-4f2e-aad5-2e9b0342344c)
⊙Uh.oh
an error message has occured:this api
domain is deprecated.use the https://
cobalt.tools/web app,host your own api
instance,or update the main cobalt api
domain you use.

IOS 17.0 A16 chip

**Comment by KwiatekMiki** [comment]
That's not a problem with cobalt, the shortcut you're using is using the old API. You need to change it to `api.cobalt.tools` (if you can).

**Comment by wukko** [comment]
we don’t have official cobalt shortcuts, contact whoever made it instead.
