### ISSUE TITLE
add support for youtube clips

### ISSUE THREAD

**Issue by itsjkl** [imputnet/cobalt#689]
youtube already exists, but youtube **clips**

https://youtube.com/clip/Ugkxe1Q-OcwzYohl5rB7VDBa73vec6_GzUKI?si=fKIn8-mjQSUPdDhB)

if that's possible , I would rlly like that feature, as i dont like downloading the whole video , i just want a certain clip. would save a lot of file size

**Comment by itsjkl** [comment]
(i accidentally put service request, it should be feature request)

**Comment by dumbmoron** [comment]
#128
