### ISSUE TITLE
Can't connect to service api when attempting to download a video from YouTube

### ISSUE THREAD

**Issue by hugh-jastle** [imputnet/cobalt#690]
### bug description
Trying to download a youtube video and I got hit with this error, "i couldn't connect to the service api. maybe it's down, or cobalt got blocked. try again, but if error persists, check the status page or create an issue on github."

### reproduction steps
- Copy link from youtube
- Paste link into cobalt
- Recieve error message

### screenshots
![Screenshot 2024-08-21 at 12 04 15 PM](https://github.com/user-attachments/assets/efb87bea-cbf7-4320-b87d-2ef5222a01bb)

### platform information
- macOS Sonoma Version 14.6.1 
- Chrome
- v.7.15-05ba1f0

**Comment by wukko** [comment]
this is caused by youtube suspending our dummy accounts. i'll let you know once we replace them!

**Comment by wukko** [comment]
should be resolved now

**Comment by cg505** [comment]
hitting this again just now

**Comment by wukko** [comment]
> hitting this again just now

we usually fix it within an hour, just like back then. atm it's working fine.
