### ISSUE TITLE
Enable downloading videos over 180 minutes on main instance

### ISSUE THREAD

**Issue by Tintin232** [imputnet/cobalt#691]
### service name & description
This is a very general request, but I wanted to know if downloading videos longer than 180 minutes will be possible in the near future. 

### additional context
If it's not possible with this program, can anyone suggest a good program that can do it?

**Comment by KwiatekMiki** [comment]
> I wanted to know if downloading videos longer than 180 minutes will be possible in the near future.

It's already possible, you just need to run your own instance and set the `DURATION_LIMIT` variable to a bigger number than 10800.

https://github.com/imputnet/cobalt/blob/current/docs/run-an-instance.md

**Comment by Tintin232** [comment]
Do you know if any of the other publicly available cobalt instances already support this? 
![Screenshot_20240822_155120_Chrome](https://github.com/user-attachments/assets/18878408-aa77-4d99-ab40-27662fca3b80)

**Comment by Tintin232** [comment]
Anyone know of any cobalt instance that allows downloading videos longer than 180 minutes? (Running my own instance is not within my range of experience 😔).

**Comment by wukko** [comment]
no one will handle streaming 3+ hour videos for you, it’s resource intensive and will hurt experience for everyone else. you gotta host your own api instance.
