### ISSUE TITLE
Could you tell me how to run "npm run token:youtube", Pls?

### ISSUE THREAD

**Issue by CaryLover** [imputnet/cobalt#692]
I open a YouTube web page, and open a video in this page. and then, I open a terminal command window in the Ubuntu 22.04. In the termianl window, I run the "npm run token:youtube", but can't success, could somebody give me some help: How to use the "npm run token:youtube"  command, Thank U very much!

**Comment by KwiatekMiki** [comment]
This should help you: https://github.com/imputnet/cobalt/issues/687#issuecomment-2293405845

**Comment by CaryLover** [comment]
What I mean is that after following the above steps, only a timeout message appears in the terminal window, and there is no other information. I used the Node.js installation version, not the Docker version. I would like to ask, is my operation correct? If it is correct, what could have gone wrong? If it's incorrect, could you please provide the correct steps?

**Comment by wukko** [comment]
what timeout message?
