### ISSUE TITLE
this youtube video is unavailable. it could be visibility or region restricted. try another one!

### ISSUE THREAD

**Issue by BentleyBentayga** [imputnet/cobalt#697]
### bug description
First time having this issue is when I tried to download Puzzle but it's getting the error, tried other videos to no avail GETTING THE SAME ISSUE UNTIL ITS FIX

Now getting this issue while trying to download Buddha, REGARDLESS OF THE SETTING ITS SHOWING UP THE SAME ERROR EVEN AT ALL VIDEOS, EVEN THOUGH ITS PUBLIC

### reproduction steps
steps to reproduce the described behavior.  
here's an example of what it could look like:
1. go to 'cobalt.tools'
2. put any video link from the textbox
3. click to download
4. see error _this youtube video is unavailable. it could be visibility or region restricted. try another one!_

### screenshots
![image](https://github.com/user-attachments/assets/35827d14-581d-4f30-a50a-1051b7b45f77)

### links
https://cobalt.tools/

### platform information
- OS [Windows 11]
- browser [Google Chrome]
- version [Version 128.0.6613.85 (Official Build) (64-bit)]

**Comment by wukko** [comment]
i am working on fixing it, will let you know when im done 👍

for context, youtube suspended all of cobalt's dummy accounts when both maintainers were asleep. i woke up the earliest, so i am the one handling it rn.

**Comment by wukko** [comment]
should be resolved now!
