### ISSUE TITLE
Audio normalisation: Highly dynamic audio results in audio clipping artefacts

### ISSUE THREAD

**Issue by MengLinMaker** [imputnet/cobalt#701]
### bug description
For media with highly dynamic audio like EDM, audio clipping is noticeable when played on **VLC**
Seems to be fine when played though the browser.

### reproduction steps
1. Download the example audio from [cobalt.tools](https://cobalt.tools/)
2. Listen at timestamp 0:30 - 0:40

### screenshots
Loading the audio into Audacity shows that there is indeed clipping happening:
<img width="1664" alt="image" src="https://github.com/user-attachments/assets/7d666432-c1a5-4e9d-bc9b-3508f8747721">

### links
YouTube: https://www.youtube.com/watch?v=LgOWSa7pmaY
SoundCloud: https://soundcloud.com/nor_sc/its-u-2023-ver

### platform information
I think this is irrelevant:
- OS [macos]
- browser [brave (chrome)]
- version [?]

### solution
Additional args for normalisation can be added to [src/config.json#L85](https://github.com/imputnet/cobalt/blob/afa33c404355e1a00d884a2db837233bca54f7f6/src/config.json#L85):
`-filter:a "dynaudnorm=p=0.9"`

**Comment by wukko** [comment]
i don't hear or see any clipping, what exactly do you mean?

if you want to normalize the loudness, you can do that in audacity:
<img width="475" alt="image" src="https://github.com/user-attachments/assets/fd9f8a69-7485-4ada-a754-907dbb9d2465">

are you sure volume is not at 150% in vlc?
<img width="175" alt="image" src="https://github.com/user-attachments/assets/612ad392-9ea9-4402-a498-fb065eaa372e">

**Comment by MengLinMaker** [comment]
Oh, yep my VLC is on 150%
