### ISSUE TITLE
Video codec vp09.00.51.08.01.01.01.01.00 (244) is improperly downloaded

### ISSUE THREAD

**Issue by RaymanChrome** [imputnet/cobalt#702]
### bug description
framerate is multiplied by 1000

### reproduction steps
1. Find any YouTube video with a codec of vp09.00.51.08.01.01.01.01.00 (244)
2. auto-download using cobalt.tools
3. When imported into MAGIX VEGAS Pro, it displays as 30 000,000p.

### screenshots
![Screenshot_1125](https://github.com/user-attachments/assets/ae4c1df4-6ead-4554-bca2-2927a1441bc2)

### links
Video I downloaded that has this codec: https://www.youtube.com/watch?v=y4rtYCdARZo
It appears on old videos that have been rendered with VEGAS Pro render preset "NTSC DV widescreen" (.avi)

### platform information
- Windows 8.1
- Google Chrome 109

**Comment by KwiatekMiki** [comment]
????
