### ISSUE TITLE
option to automatically rename downloaded files to video title with video code

### ISSUE THREAD

**Issue by Muatex** [imputnet/cobalt#704]
### describe the feature you'd like to see
i would like to suggest a feature where, similar to yt-dlp, cobalt automatically renames the downloaded video files to match the video title instead of using a generic or download-specific filename. additionally, including the video code (e.g., youtube video id) in square brackets at the end of the filename would be beneficial. this feature could be optional, allowing users to toggle it on or off based on their preference.

### additional context
this feature would make the downloaded files more organized and easier to identify, as the filenames would be descriptive and consistent with the video content. it also improves usability by reducing the need for manual renaming after download.

_p.s. sorry for using chat gtp ai, english is not my first language. ^-^_

**Comment by KwiatekMiki** [comment]
![image](https://github.com/user-attachments/assets/72d0a8bc-1dea-4519-9409-9b789f3617f0)
![image](https://github.com/user-attachments/assets/ae4a70a4-02a7-400c-a7f3-ff4964cc4eb2)
![image](https://github.com/user-attachments/assets/2866c347-e336-4d33-be3f-602951dfacfe)

**Comment by Muatex** [comment]
Thank you so much!!!!!!!

**Comment by KwiatekMiki** [comment]
Can you close the issue now?

**Comment by Muatex** [comment]
okay !!
just one more question
is there a way to use a custom name style? or is this the only way

**Comment by KwiatekMiki** [comment]
#228

**Comment by Muatex** [comment]
love
