### ISSUE TITLE
The videos in Ins cannot be extracted normally

### ISSUE THREAD

**Issue by lpwyz** [imputnet/cobalt#710]
Hello, I noticed that there are https://www.instagram.com/reel/C-9uRJ1xR3m This link cannot be extracted, but the video can be played normally, but other Ins can extract it. What is the reason for this

**Comment by wukko** [comment]
no sorry reading is hard

**Comment by lpwyz** [comment]
> can people start not ignoring the template

This is not a template, I found that the video links of this author cannot be extracted

> https://www.instagram.com/reel/C-9uRJ1xR3m

I noticed that some videos on Instagram cannot be downloaded, such as the following:
https://www.instagram.com/reel/C-9uRJ1xR3m/?igsh=eGI4c25qdzFuNTY=
https://www.instagram.com/reel/C_aEtKOROS-/?igsh=YjR5cDJib2RoazQ5

**Comment by wukko** [comment]
<img width="1281" alt="image" src="https://github.com/user-attachments/assets/fc6e93c7-0a9d-4d6e-936f-883f19bb107f">

**Comment by lpwyz** [comment]
> <img alt="image" width="1281" src="https://private-user-images.githubusercontent.com/71202418/363911210-fc6e93c7-0a9d-4d6e-936f-883f19bb107f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTQwMjgsIm5iZiI6MTcyNTM1MzcyOCwicGF0aCI6Ii83MTIwMjQxOC8zNjM5MTEyMTAtZmM2ZTkzYzctMGE5ZC00ZDZlLTkzNmYtODgzZjE5YmIxMDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA4NTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmN2Q1ZTE2NmE0YWM3YTdhYjUwMDIwNmE1ZWZiN2IzZjlkNDhkOTY3N2Q0ZDE0YWM0NzYxNmMwMmU0MDc4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U-GmKCpVnMzqB8_D8sgRx4f-LcCM7Gwru0PjrvZp7x0">

Okay, I understand now. Thank you. I will submit the correct template for feedback in the future

**Comment by lpwyz** [comment]
> some instagram videos may not be downloadable because instagram gatekeeps anonymous access to them
> 
> in the future, please use an appropriate issue template and FILL IT OUT

But it's strange, the two links I posted above are both videos published by the same author. Previously, this author's videos could be downloaded on Cobalt, but now they can't be downloaded

**Comment by wukko** [comment]
> instagram gatekeeps anonymous access to them

for example, i can't even view any of your links in a regular browser:
<img width="898" alt="image" src="https://github.com/user-attachments/assets/38170b4a-5ace-47d0-8fca-b7d2ef17462b">
to fix this, i'd need to log in. 

in case (and scale) of cobalt, it'd require a bunch dummy accounts. we think it's a little unreasonable at this time.

**Comment by lpwyz** [comment]
> > instagram gatekeeps anonymous access to them
> 
> for example, i can't even view any of your links in a regular browser: <img alt="image" width="898" src="https://private-user-images.githubusercontent.com/71202418/363913763-38170b4a-5ace-47d0-8fca-b7d2ef17462b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTQ0NzEsIm5iZiI6MTcyNTM1NDE3MSwicGF0aCI6Ii83MTIwMjQxOC8zNjM5MTM3NjMtMzgxNzBiNGEtNWFjZS00N2QwLThmY2EtYjdkMmVmMTc0NjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA5MDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1Yzg0NGU4N2E5ZmFiMmFjZDRlOTdjNjUzZjNiYTg3ODY1Y2FlZTkzZmY3OTBiYjk1MDM4MzViYjg0MDA0ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j1tbobh0LAw_lnkMzeCwhWUyx2lcmu2RCLSNHtS_xSk"> to fix this, i'd need to log in.
> 
> in case (and scale) of cobalt, it'd require a bunch dummy accounts. we think it's a little unreasonable at this time.

I understand what you mean, I understand. I'm curious to ask if it's because the author has set any permissions for publishing videos that led to this. I remember before, Cobalt could access information about this author, such as setting up a login account for sharing videos, or is this the default rule of Instagram

**Comment by wukko** [comment]
not a clue tbh, i don't use instagram myself
