### ISSUE TITLE
YT vid ain't downloading dawg

### ISSUE THREAD

**Issue by smoressy** [imputnet/cobalt#715]
https://www.youtube.com/watch?v=ImDa2MB_hoQ
"this youtube video is unavailable. it could be visibility or region restricted. try another one!"

**Comment by pangzheng** [comment]
youtube video all not download

**Comment by wukko** [comment]
seems to be working fine now, can you try again?

**Comment by hopeseekr** [comment]
Every video says

> couldn't get this youtube video because it requires an account to view.
>
> this limitation is done by google to seemingly stop scraping, affecting all 3rd party tools and even their own clients.
>
>try again, but if issue persists, check the  or .

It's on Hetzner, in case that matters.

**Comment by KwiatekMiki** [comment]
> It's on Hetzner, in case that matters.

So you're self-hosting it? If yes, set up cookies for YouTube. https://github.com/imputnet/cobalt/issues/687#issuecomment-2293405845

**Comment by LordByronRS** [comment]
> > It's on Hetzner, in case that matters.
> 
> So you're self-hosting it? If yes, set up cookies for YouTube. [#687 (comment)](https://github.com/imputnet/cobalt/issues/687#issuecomment-2293405845)

I tried excatly what it says in the tutorial. I got something like this:
`"access_token=ya2; refresh_token=1//; scope=https://www.googleapis.com/auth/youtube https://www.googleapis.com/auth/youtube-paid-content; token_type=Bearer; expiry_date=2024-09-08T22:58:58.080Z"`
Added that into the cookies.json (which is correctly mounted in the container) and I still get the exact same error.
