### ISSUE TITLE
Youtube just not downloading certain videos

### ISSUE THREAD

**Issue by BartoszMikMik** [imputnet/cobalt#716]
Not sure if I'm doing the whole reporting bugs thing right, apologies if I'm not
was trying to download this specific video (https://www.youtube.com/watch?v=speacW8GT_k) as audio file and couldn't help but realise it just wouldn't download?

[image](https://github.com/user-attachments/assets/4882e4b2-e828-4a32-8dbe-37fb32e0177a)

I've tried messing around with changing the settings to see if it downloads but it just doesn't and its not an issue with youtube, hell I even tried downloading it as an mp4 and that worked fine its just audio files that are an issue

**Comment by KwiatekMiki** [comment]
Can only reproduce on the main instance so the label is correct BUT THE TEMPLATE EXISTS FOR A REASON AND YOU JUST IGNORED IT

> [image](https://github.com/user-attachments/assets/4882e4b2-e828-4a32-8dbe-37fb32e0177a)

Why did you link the image?

**Comment by BartoszMikMik** [comment]
for i am stupid

im sorry

**Comment by zephiii** [comment]
wait a bit, youtube can be funky sometimes

**Comment by wukko** [comment]
seems to be downloading fine now:
<img width="328" alt="image" src="https://github.com/user-attachments/assets/53ef7a25-bc0c-45f4-a2e7-f25f0e6d38ac">
