### ISSUE TITLE
I am using docker

### ISSUE THREAD

**Issue by apurbapathak** [imputnet/cobalt#718]
my bugs on installation:

#0 514.1 npm error Exit handler never called!
#0 514.1 npm error This is an error with npm itself. Please report this error at:
#0 514.1 npm error     <https://github.com/npm/cli/issues>
#0 514.1 
#0 514.1 
#0 514.1 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-09-08T12_00_16_567Z-debug-0.log
------
Dockerfile:6
--------------------
   5 |     
   6 | >>> RUN apt-get update                                    && \
   7 | >>>     apt-get install -y git python3 build-essential    && \
   8 | >>>     npm ci                                            && \
   9 | >>>     npm cache clean --force                           && \
  10 | >>>     apt purge --autoremove -y python3 build-essential && \
  11 | >>>     rm -rf ~/.cache/ /var/lib/apt/lists/*
  12 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update                                    &&     apt-get install -y git python3 build-essential    &&     npm ci                                            &&     npm cache clean --force                           &&     apt purge --autoremove -y python3 build-essential &&     rm -rf ~/.cache/ /var/lib/apt/lists/*" did not complete successfully: exit code: 1

**Comment by dumbmoron** [comment]
please use the provided template

**Comment by KwiatekMiki** [comment]
> This is an error with npm itself. Please report this error at:
> https://github.com/npm/cli/issues
