### ISSUE TITLE
Bilibili videos do NOT download

### ISSUE THREAD

**Issue by JoePro9919** [imputnet/cobalt#721]
### bug description

It's what it says on the tin. ever since the update prior and now, bilibili videos refuse to download. When attempted, the error message states "couldn't find any media that i could download for you. are you sure you pasted the right link?" even though these exact links worked prior.

### reproduction steps

1. open cobalt
2. paste in link to bilibili video [ex: https://www.bilibili.com/video/BV1HAWLehEuw?t=7.2]
3. see it doesn't download

### screenshots

![Screen Shot 2024-09-09 at 4 10 46 PM](https://github.com/user-attachments/assets/7ef1dd34-a3fd-4fb0-aca6-49d3e2c240c8)

### platform information

firefox

**Comment by wukko** [comment]
duplicate #676
