### ISSUE TITLE
Can't download youtube audio on main instance

### ISSUE THREAD

**Issue by AstralButOnGitHub** [imputnet/cobalt#723]
### bug description

Can't download any audio, tried this link: "https://www.youtube.com/watch?v=-rfoYSmx0rk"

![image](https://github.com/user-attachments/assets/3ec8386b-15c3-4bc1-9787-356e4d09bd9c)

### reproduction steps

copy link from youtube (haven't found one that works yet)

paste into cobalt

press audio

Get error
![image](https://github.com/user-attachments/assets/3ec8386b-15c3-4bc1-9787-356e4d09bd9c)

### screenshots

![image](https://github.com/user-attachments/assets/3ec8386b-15c3-4bc1-9787-356e4d09bd9c)

### links

```shell
https://www.youtube.com/watch?v=-rfoYSmx0rk
```

### platform information

Windows 10, OperaGX

**Comment by wukko** [comment]
you've only tried youtube, haven't you?

**Comment by AstralButOnGitHub** [comment]
> you've only tried youtube, haven't you?

Yes, I assume it works with anything else? 💀

**Comment by wukko** [comment]
you're not dumb, don't call yourself that.

the issue with youtube downloading seems to be fixed on our side. can you try again and close the issue as completed if it works for you?

**Comment by wukko** [comment]
oops i accidentally closed the issue

ill reopen it if it doesn't work for you

**Comment by AstralButOnGitHub** [comment]
No it's fixed lmao

**Comment by AstralButOnGitHub** [comment]
o7 good luck with everything
