### ISSUE TITLE
option to remove non-music parts from a YouTube video

### ISSUE THREAD

**Issue by sodiboo** [imputnet/cobalt#729]
### describe the feature you'd like to see

Some YouTube videos containing music will include other parts that aren't part of the song, such as dedicating half the video to the creation of the song, or having some intermission that talks about the background of the song and what exactly this video contains. Music videos frequently contain non-music buildups that seek to set the scene that the video takes place in, or resolves it after the music ends.

It would be nice to be able to download just the music from a video. This is distinct from downloading the audio track (which cobalt already does) because downloading the music involves cutting out non-music parts.

SponsorBlock already contains a very large and extensive database of such [non-music sections](https://wiki.sponsor.ajay.app/w/Music:_Non-Music_Section), so to figure out what parts to trim, cobalt should just query SponsorBlock.

Since SponsorBlock only cares about YouTube videos, it is not reasonable for cobalt to implement similar functionality for any of its other supported services.

If the reader is confused by the name, SponsorBlock is named as such because it was originally made to skip integrated advertisements (see #311), but the technical aspect is generic enough that it has since expanded to also keep track of various other kinds of "segments" in videos that one might want to skip for one reason or another, and makes this data available freely [their API](https://wiki.sponsor.ajay.app/w/API_Docs) for projects such as cobalt to use.

**Comment by sodiboo** [comment]
> just download the audio from youtube music if you don't need the video

YouTube Music doesn't solve this issue, see for example [this song](https://music.youtube.com/watch?v=SZNvnzfiT5Q) which contains a lot of non-music even on YouTube Music.

**Comment by wukko** [comment]
i've updated the original sponsorblock support issue to cover this one, too: #311

**Comment by KwiatekMiki** [comment]
> [this song](https://music.youtube.com/watch?v=SZNvnzfiT5Q) which contains a lot of non-music even on YouTube Music.

then it's not a non-music part

**Comment by sodiboo** [comment]
> > [this song](https://music.youtube.com/watch?v=SZNvnzfiT5Q) which contains a lot of non-music even on YouTube Music.
> 
> then it's not a non-music part

your reply here sounds like you're defining {the part of the linked video where she talks about the circumstances under which the song was made} as {music} on the basis of it being on YouTube Music. this is an absurd claim, but I cannot think of any other way to parse this reply.

just to be clear, the phrase "music" in "non-music" (and all other contexts the term appears in my prior communication, except where stylized as exactly "YouTube Music") refers to entertaining sounds with a rhythm, beat, and/or melody. what it does not refer to, is any content on YouTube Music. the existence of some content on YouTube Music does not imply that the given content is music (content here used to describe any part of any video)
