### ISSUE TITLE
Add support for Bluesky

### ISSUE THREAD

**Issue by BloodDragooner2** [imputnet/cobalt#739]
### service name

Bluesky

### service description

Bluesky (bsky.app) released video yesterday to most users.

### link samples

```shell
https://bsky.app/profile/oocpokemonofficial.bsky.social/post/3l3w3s4dmil2f
```

### additional context

though it is currently not obvious how to fetch the link, as it seems embedded into a m3u8 playlist 
![image](https://github.com/user-attachments/assets/1ea49204-7108-4d62-a70f-8bb9cbc4920a)

**Comment by hyperdefined** [comment]
Bluesky is support already.

**Comment by wukko** [comment]
it's already supported! have you tried pasting that link into https://cobalt.tools?

<img width="498" alt="image" src="https://github.com/user-attachments/assets/02c48980-1735-4bf8-b079-59770f4fc75a">

**Comment by BloodDragooner2** [comment]
Hello hello, I just tested it. Works proper! Thank you, and apologies for the inconvenience

**Comment by vanontom** [comment]
Bluesky support is awesome, thanks!

Update: Worked great for a few weeks. Now it seems to be having some severe difficulties, consistently for past week. Details: Usually takes 3 or more attempts to download. Rarely works at first attempt ("couldn't find video"). Many times downloads blank video (0 bytes). Many times downloads partial video (ouch, check duration). Eventually downloads properly (requires much patience). I should file an issue...

**Comment by wukko** [comment]
can you make a new issue so we can track it? with link samples and etc?
