### ISSUE TITLE
not able to install node modules

### ISSUE THREAD

**Issue by nikunjmishra1998** [imputnet/cobalt#746]
### bug description

when we are setting up API on local environment and hit 'npm install' command then we are getting error like attached screen shot

### reproduction steps

1) clone cobalt on local system
2) Try to setup API, and run 'npm install' command for setup.

You will get the error

### screenshots

![image](https://github.com/user-attachments/assets/30ef94f0-69de-4349-b77a-3de1fca9eb54)

### platform information

Linux

**Comment by wukko** [comment]
hello! you need to install pnpm.

just updated the [local env docs](https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md), sorry for not having done this earlier. lmk if you have any other questions.
