### ISSUE TITLE
add support for OpenVK

### ISSUE THREAD

**Issue by myslivets** [imputnet/cobalt#747]
### service name

OpenVK

### service description

OpenVK is an open source social network, is an imitation of the old VK.com (until 2016)

### link samples

```shell
https://ovk.to/video1_27
https://openvk.su/video1_27
https://vepurovk.xyz/video1_1
```

### additional context

![image](https://github.com/user-attachments/assets/9a1a9d3e-2fe8-4fad-a870-3e649a2e8ecc)

![image](https://github.com/user-attachments/assets/bcf002d6-e939-4806-97de-49d3fecf86cf)

**Comment by myslivets** [comment]
**P.S: Я не Veselcraft и не являюсь его представителем/секретарём**

**Comment by KwiatekMiki** [comment]
> ### link samples
> 
> ```shell
> https://ovk.to/video2_10
> https://openvk.su/video2_10
> https://vepurovk.xyz/video1_1
> ```

why are there 3 domains for that

**Comment by wukko** [comment]
1/3 links open, the rest throw 500 and sometimes say something about limited video visibility.

<img width="527" alt="image" src="https://github.com/user-attachments/assets/e8a876db-08f6-4b55-a0cc-93f2a2bc9a3c">

![image](https://github.com/user-attachments/assets/ccb17f04-5b61-4e69-93b0-43836b3e2a00)

given the poor stability, locked down access, and that this service is extremely niche (<20 active users at time of reply), we will not be adding support for it at this time.

**Comment by veselcraft** [comment]
лох

**Comment by veselcraft** [comment]
> why are there 3 domains for that

it's different instances

**Comment by wukko** [comment]
> лох

желаю удачи с таким отношением к людям
