### ISSUE TITLE
Showcasing the file size of the video when downloading

### ISSUE THREAD

**Issue by Rashedaldahmani** [imputnet/cobalt#760]
### describe the feature you'd like to see

When downloading a video, it would be nice to see the size of the file while downloading instead of ?

**Comment by wukko** [comment]
the file size is already shown whenever possible. in cases when video is processed live, the final size is unknown, so it is not shown.

**Comment by Rashedaldahmani** [comment]
Why isn’t it possible to howcaseit live while downloading

**Comment by wukko** [comment]
because we never save anything to disk. what you see is live render. it is impossible to predict the exact final size of a render.
