### ISSUE TITLE
Infinite loading after pasting the link on iOS 15

### ISSUE THREAD

**Issue by WELCOME1200** [imputnet/cobalt#761]
### bug description

When I pasted a YouTube link on the website, it just keep on spending and will not give me any error or anything, I retry it with different YouTube links and it’s the same thing, it’s like it can’t go through the server, seems like it only happen to my iPhone because I try it on my laptops and the website works fine.

P.s
This happen after the update to v10 of cobalt before it was working normal.

iPhone 7, iOS 15.8.1, iOS 15.8.2, and iOS 15.8.3
All 3 have the same problem

### reproduction steps

Copy link, Paste Link whether by the paste button on the website or your own.

### platform information

iOS 15.8.3

**Comment by WELCOME1200** [comment]
Refresh website did not work even though status page says it’s all operating

**Comment by wukko** [comment]
can you describe the issue properly? what is “spending”? do you see any errors?

it’s better to screen record the issue you’re having

**Comment by sttlok** [comment]
I have the same issue. It was working a couple of weeks ago but won’t anymore. When clicking the “>>” after pasting a link, the wheel at the box left of the link will start spinning forever and nothing happens (This is probably what WELCOME1200 meant by “spending”). This issue happens to me in both Safari and Firefox. I am using an iPhone 11 with iOS 15.6.

**Comment by wukko** [comment]
i really wonder why that is happening but can’t reproduce it on my devices.

do you have an ability to connect your iphone to a mac to see what’s up in dev tools?

**Comment by wukko** [comment]
update: the issue is caused by usage of `AbortSignal.timeout()` in fetch requests. safari got support for it only with ios 16 for some reason. we will push a fix soon!
