### ISSUE TITLE
Regarding fetch failed

### ISSUE THREAD

**Issue by nikunjmishra1998** [imputnet/cobalt#762]
### bug description

in every few of request of same video or differrent video, we are receiving below error even if we have added RATELIMIT_MAX=192 in .env file

{
    "status": "error",
    "error": {
        "code": "error.api.fetch.fail",
        "context": {
            "service": "youtube"
        }
    }
}

### reproduction steps

1) setup API at local same as instruction
2) call API using any of the tools like postman or another
3) you will fetch error as mentioned

### screenshots

![image](https://github.com/user-attachments/assets/c6ae4bf9-2b99-4b82-89ac-189779249650)

### platform information

Linux

**Comment by KwiatekMiki** [comment]
this is nothing related to rate limiting on your instance, that's probably youtube rate limiting you.

add more account cookies
