### ISSUE TITLE
YouTube Error

### ISSUE THREAD

**Issue by BlueDome77** [imputnet/cobalt#766]
### bug description

When I try to load [this](https://www.youtube.com/watch?v=d13PIaE3BWE) YouTube video I get an error: 
> youtube didn't return anything with
your preferred codec & resolution. try
another set of settings!

When I load [Big Buck Bunny](https://www.youtube.com/watch?v=YE7VzlLtp-4) it works perfectly fine.

### reproduction steps

1. Import my settings file: [settings.json](https://github.com/user-attachments/files/17080962/settings.json)
2. Click [here](https://cobalt.tools/?u=https://www.youtube.com/watch?v=d13PIaE3BWE) to load the YouTube video into Cobalt
3. Click ">>" to download

### screenshots

![Screenshot 2024-09-20 at 4 16 43 PM](https://github.com/user-attachments/assets/6a56b3ea-5836-4b90-bb77-d6c88aa81129)

### links

```shell
https://www.youtube.com/watch?v=d13PIaE3BWE
```

### platform information

macOS Sonoma Version 14.5 - Safari Version 17.5

**Comment by wukko** [comment]
well yes, this video is not available in av1, just like cobalt says. try a different codec.
