### ISSUE TITLE
Cobalt.Tools Cobalt Animation error with "Share with a friend" QR Code Animation

### ISSUE THREAD

**Issue by smoressy** [imputnet/cobalt#770]
### bug description

There is no animation for the size-down of the QR code when you click the QR code again after its big. Since there is a size-up animation when you click on the QR code, there should also be a size-down animation, bu t there is not in this case as it was never implineted correctly.

### reproduction steps

1. Go to cobalt.tools
2. Go to donate
3. Click the QR code to activate the bigger effect
4. Click the QR code again
5. It does not size down
Usually since there is a size-up effect, there should also be a size down effect but there's not.

### screenshots

![image](https://github.com/user-attachments/assets/7229e17f-8756-4eb0-a265-fb6fa5a132a7)

### links

```shell
https://cobalt.tools/donate
```

### platform information

Chrome on ChromeOS

### additional context

If there is no size-down effect solely because it is not wanted like that, then there should not even be a size-up effect to begin with, to follow that principal.

**Comment by Ross10201** [comment]
What device?

**Comment by smoressy** [comment]
> What device?

Any device really. ios and lptop and chromebook.
