### ISSUE TITLE
All of the MP4s I download are empty

### ISSUE THREAD

**Issue by Ross10201** [imputnet/cobalt#771]
### bug description

I like this tool, but sometimes it breaks really bad. What I said in the title (all the MP4s I download are empty) By empty, I mean it has NO content and it has 0 bytes inside. It worked fine on iPadOS but on iPadOS 18 it broke. Can you troubleshoot me?

### reproduction steps

1. Get a link
2. Paste the link in the "download bar" where you put the link you want to download
3. Download it.
4. Check the file. In my case, it is empty.

### platform information

iPad 10, iPadOS 18/ iPhone 12 Pro Max, iOS 18 on Opera Browser

**Comment by wukko** [comment]
can you provide any links that don’t work for you?

**Comment by wukko** [comment]
for future reference, all questions in the issue template are there for a reason.

**Comment by Ross10201** [comment]
Also, about the links that don't work for me, every YouTube link I download
has no content

**Comment by Ross10201** [comment]
I normally use cobalt for YouTube, but on rare occasions I use it for other sites

**Comment by wukko** [comment]
can you give me the sample links that don't work for you

**Comment by Ross10201** [comment]
I'll just get some, maybe it would work for you

**Comment by Ross10201** [comment]
Or I can give a sample file

**Comment by wukko** [comment]
... can you just give me some links that don't work for you already

**Comment by Ross10201** [comment]
Never mind, it patched itself. Still, it didn't work a while ago. Feel free
to close this thread :)
