### ISSUE TITLE
long videos dont download fully

### ISSUE THREAD

**Issue by arnideus** [imputnet/cobalt#774]
### bug description

every time i try to download the audio of a long video (listed in links) the resulting file abruptly cuts off at 39 minutes and 31 seconds

### reproduction steps

1. copy link
2. download the video
3. that's it

### links

```shell
https://www.youtube.com/watch?v=_qX7c1yFs9w
```

### platform information

brave on windows 10 and google chrome on android 13

**Comment by wukko** [comment]
#647
