### ISSUE TITLE
Support with youtube music

### ISSUE THREAD

**Issue by JellyWasAvalible** [imputnet/cobalt#778]
### describe the feature you'd like to see

idk if it dose but if so its be good

**Comment by lostdusty** [comment]
already supported

**Comment by lunairekitty** [comment]
It's already supported since they're basically just Youtube videos. If you have problems downloading them I've found removing the "`music.`" from the link gets it to recognize it sometimes

**Comment by KwiatekMiki** [comment]
1. wrong template
2. it's already supported
