### ISSUE TITLE
Premium/Pro/Extra Features For Donating to Cobalt?

### ISSUE THREAD

**Issue by AnxiousPleaseHelp** [imputnet/cobalt#790]
### describe the feature you'd like to see

Hello,

I recently started using Cobalt and I'm really impressed.

It'd be great if there was an "anonymous mode" or a "no user tracking" or a "no telemetry" feature so that the videos I download are not recorded or sent to someone on the Internet?

I'm ready to donate right now if this is possible?

I hope someone can help me! 😢😢😢

**Comment by wukko** [comment]
cobalt is [already anonymous](https://cobalt.tools/about/general#privacy) and doesn’t store any user info whatsoever. 

you can read our privacy policy here: https://cobalt.tools/about/privacy

and you can donate here: https://cobalt.tools/donate
