### ISSUE TITLE
Videos don't have a length attribute

### ISSUE THREAD

**Issue by Privatech38** [imputnet/cobalt#794]
### bug description

Any video codec used doesn't provide a video length attribute.

### reproduction steps

1. go to https://cobalt.tools/
2. select auto and any of the video codecs
3. post a link from youtube or reddit
4. download video
5. video doesn't have a length property

### screenshots

![h264](https://github.com/user-attachments/assets/03efc684-7e78-429f-b517-e8af7d09bf59)
![vp9](https://github.com/user-attachments/assets/d73b4671-09f7-4198-b3a1-4b02f8e65f2d)

### platform information

Windows 10 Pro 22H2 build 19045.4894

**Comment by wukko** [comment]
remuxing fixes this issue: https://cobalt.tools/remux
