### ISSUE TITLE
some short tiktok links don't work

### ISSUE THREAD

**Issue by smoressy** [imputnet/cobalt#804]
### bug description

https://www.tiktok.com/t/ZTFykom5F/

![IMG_4249](https://github.com/user-attachments/assets/827d4077-a431-4272-85c4-297eb335be76)

### reproduction steps

download it

### platform information

iphone 11 pro

**Comment by KwiatekMiki** [comment]
click on tjat link and download the link it redirects you to

**Comment by smoressy** [comment]
> click on that link and download the link it redirects you to

I shouldnt have to do that though...

**Comment by wukko** [comment]
closed via 6ad838b6498d11934f4b70f0b368778535d75c89, thanks for reporting this issue!
