### ISSUE TITLE
error.api.header.accept on chrome browser

### ISSUE THREAD

**Issue by cleansingfire** [imputnet/cobalt#805]
### bug description

When I paste a link and try to download a youtube video I get a error.api.header.accept error on chrome browser, but it seems to download fine on Edge Browser. I tried downloading different videos and I get the same error. 

### reproduction steps

1. go to cobalt.tools
2. paste link below
3. click »  
4. website returns error.api.header accept

### screenshots

[Error](https://prnt.sc/UrNPVzWFnfh2)

### links

```shell
https://www.youtube.com/watch?v=tPEE9ZwTmy0
```

### platform information

Chrome Version 129.0.6668.90 on Windows 11

**Comment by wukko** [comment]
what extensions do you have installed?

**Comment by wukko** [comment]
could you try cobalt in an incognito (or inPrivate) window to see if issue sticks? if it works fine, try disabling extensions one by one and please tell me which one was causing the issue. i'll try to look into it and contact the developer if needed!

**Comment by wukko** [comment]
you didn't list modheader before, was is configured to change request headers in some way?
