### ISSUE TITLE
Download video from bilibili not work

### ISSUE THREAD

**Issue by celebrateyang** [imputnet/cobalt#808]
### bug description

Not able to download video from bilibili.
For example, paste this link https://www.bilibili.com/video/BV1fzxZeQEa3?t=1.0 in the input box, and then click download button,
it says: "couldn't find any media that i could download for you. are you sure you pasted the right link?"
but it's a really video link.
![bug_1](https://github.com/user-attachments/assets/3baa25bb-922f-4cd2-9ad2-b330cbaf2a3e)
![bug_2](https://github.com/user-attachments/assets/6a57e12c-1bb6-44c6-a7f5-3909d2119b57)

### reproduction steps

1. go to https://cobalt.tools/
2. paste the link in input box: https://www.bilibili.com/video/BV1fzxZeQEa3/?spm_id_from=333.999.0.0&vd_source=1d6a54d9cfcf84b367ae710036f7737b
3. error: couldn't find any media that i could download for you. are you sure you pasted the right link?

### screenshots

![image](https://github.com/user-attachments/assets/5990bc4b-12fc-40c8-85aa-9451c33394fe)

### links

```shell
https://www.bilibili.com/video/BV1fzxZeQEa3/?spm_id_from=333.999.0.0&vd_source=1d6a54d9cfcf84b367ae710036f7737b
https://www.bilibili.com/video/BV1ZK4RerECM/?spm_id_from=333.1007.tianma.5-3-17.click&vd_source=1d6a54d9cfcf84b367ae710036f7737b
https://www.bilibili.com/video/BV1ZK4RerECM/
```

### platform information

chrome on windows10

**Comment by wukko** [comment]
#676
