### ISSUE TITLE
FLAC support

### ISSUE THREAD

**Issue by DataM0del** [imputnet/cobalt#820]
### describe the feature you'd like to see

It looks like cobalt.tools only supports H264, AV1, and VP9 for video, and MP3, OGG, WAV, and OPUS.

**Comment by DataM0del** [comment]
Actually, you can just Convert It Yourself:tm:

**Comment by synzr** [comment]
BTW it's pointless anyway

what's the point of supporting the lossless format if cobalt can only get lossy audio?

**Comment by wukko** [comment]
> what's the point of supporting the lossless format if cobalt can only get lossy audio?

it could be used as a more efficient alternative to wav
