### ISSUE TITLE
Serious Problem: Unable to Donate?!?!? 

### ISSUE THREAD

**Issue by AnxiousPleaseHelp** [imputnet/cobalt#823]
### bug description

Hello,

I didn't want to create a thread, but I've spent the past couple hours trying to donate to cobalt and no matter what I try... nothing works. I just 
I'm trying to donate via Visa. 
Error is:
**_"We are unable to authenticate your payment method. Please choose a different payment method and try again."_**

Is it possible to donate via PayPal?

I hope someone can help me! 😢😢😢

### reproduction steps

**_"We are unable to authenticate your payment method. Please choose a different payment method and try again."_**

### platform information

Firefox Windows 10 Professional

**Comment by wukko** [comment]
hey! a donation via stripe may fail if your card doesn't support 3DS. it's required to prevent fraud. there may also be an issue with your browser, have you tried other browsers (such as edge)?
