### ISSUE TITLE
Instagram download not working

### ISSUE THREAD

**Issue by qingshanzaid** [imputnet/cobalt#825]
### bug description

![1728378486012](https://github.com/user-attachments/assets/1991e366-bb62-42a1-b47a-5d54ba82d6ef)
url : https://www.instagram.com/reel/C9efpXXIEsx/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==

### reproduction steps

![1728378486012](https://github.com/user-attachments/assets/4708257b-4dd0-41ee-8b21-aa87f454e0f1)

### platform information

windows

**Comment by KwiatekMiki** [comment]
#539
