### ISSUE TITLE
Using cobalt from cli

### ISSUE THREAD

**Issue by jasursadikov** [imputnet/cobalt#833]
### describe the feature you'd like to see

Hi! I would like to have an option to use Cobalt from CLI by sending url and downloading video to my `~/Downloads/` or `~/Videos` directories. Is there such thing?
Thank you!

**Comment by KwiatekMiki** [comment]
duplicate of #254, you can use https://github.com/lostdusty/cobalt

**Comment by jasursadikov** [comment]
Thank you!
