### ISSUE TITLE
api

### ISSUE THREAD

**Issue by meti7k** [imputnet/cobalt#834]
### bug description

Hi , The web service is not working, and the error is through cloudflare, which does not allow access to the domain.

### reproduction steps

Hi , The web service is not working, and the error is through cloudflare, which does not allow access to the domain.

### platform information

safari

**Comment by wukko** [comment]
the main instance api is not public at this time, but you can host your own instance if you want to use it: https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md
