### ISSUE TITLE
Downloading age restricted TikTok video fails due to "unrecognized error"

### ISSUE THREAD

**Issue by Trimpsuz** [imputnet/cobalt#835]
### bug description

Attempting to download an age restricted video from TikTok results in the `the tiktok module returned an error that i don't recognize. try again in a few seconds, but if issue sticks, let us know!` message and a `400 Bad Request` response from the api

### reproduction steps

1. Paste link of age restricted TikTok video into the input box (ex. https://www.tiktok.com/@.kyle.films/video/7415757181145877793)
2. Click download
3. Error message appears

### platform information

Windows 10 22H2, Brave 1.70.123 Chromium 129.0.6668.89, Firefox 131.0.2

**Comment by wukko** [comment]
closed via a1fa79f2f56d3c48020744fd062e4656f21c8d11, thank you for the report :3
