### ISSUE TITLE
Api It doesn't work

### ISSUE THREAD

**Issue by SekaiRP** [imputnet/cobalt#838]
### bug description

Api It hasn't been working for a few days

Due to Cloudflare's limitations
With tested disruptive IPs and devices

### reproduction steps

1. Send request to https://api.cobalt.tools/api/json
2. The Response will be returned 403
3. Cloudflare Says: Sorry, you have been blocked
You are unable to access cobalt.tools
4. This test fails on different devices and with different IPs

### screenshots

![Screenshot_2024-10-13-12-46-59-215_com android chrome](https://github.com/user-attachments/assets/bf48eda8-1437-4ef2-8de2-5eca1f087564)

### links

```shell
https://api.cobalt.tools/api/json
```

### platform information

Different Platforms, Linux server, FreeBSD Server, ubuntu 24.04 lts 64 bit, Poco x3 pro Android 13

**Comment by KwiatekMiki** [comment]
cobalt's api isn't public and the old api that you're trying to use will be removed soon.

host your own instance

https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md

**Comment by dhawansolanki** [comment]
@KwiatekMiki  What are the endpoints we should expect after hosting on our own instance? It looks like api/json isn’t functioning. I believe there have been some changes in the recent updates. Is there any specific documentation available after hosting on an instance?

**Comment by wukko** [comment]
https://github.com/imputnet/cobalt/blob/main/docs/api.md
