### ISSUE TITLE
CORS error on my end?

### ISSUE THREAD

**Issue by Solyphonous** [imputnet/cobalt#839]
### bug description

I have recently been getting these errors from my extension which utilises the cobalt api:

![image](https://github.com/user-attachments/assets/ad384c59-c274-4954-a9b8-0b58836b767f)

But I haven't altered my codebase in months - leading me to believe this may be an issue with the cobalt api itself. Has anything been recently changed in api responses that could be causing this? 

If it is simply an issue on my end, apologies for the inconvenience.

In case you need it, the extension is in a repo under my profile.

### reproduction steps

1: Send fetch request to cobalt api main instance from extension
2: CORS error :(

### platform information

Windows 10 + 11, Firefox latest version as of post

**Comment by KwiatekMiki** [comment]
cobalt's api isn't public anymore and the old one will get removed soon, host your own instance.
https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md

**Comment by Solyphonous** [comment]
I don't have the money to host my own instance. rip
