### ISSUE TITLE
Cobalt regularly downloads zero second videos that are playable on device but cannot be reuploaded.

### ISSUE THREAD

**Issue by dcard228** [imputnet/cobalt#841]
### bug description

This issue does not seem to affect Twitter videos at all

### reproduction steps

Copy link to video
Paste into Cobalt
Cobalt downloads normally 
Open gallery
Video is listed to have a zero second runtime
Video plays normally in gallery
Video not recognized by editing software or sites like Twitter or YouTube 

### platform information

Android 14

### additional context

Happens seemingly randomly

**Comment by KwiatekMiki** [comment]
https://cobalt.tools/remux
