### ISSUE TITLE
After host instance on my AWS EC2 ""code": "error.api.youtube.login""

### ISSUE THREAD

**Issue by MHemelHasan** [imputnet/cobalt#843]
### problem description

If I host cobalt on my local computer, it works fine, but when I host and use my ec2 API, it shows "error.api.youtube.login"
Do you know how I can solve this?

if possible provide me step by step guide 
Thanks 

### your instance configuration

```shell
AWS EC2 t2.micro
```

**Comment by KwiatekMiki** [comment]
set up cookies.

https://github.com/imputnet/cobalt/issues/687#issuecomment-2293405845
