### ISSUE TITLE
error.api.fetch.critical while hosting on virtual machine

### ISSUE THREAD

**Issue by dhawansolanki** [imputnet/cobalt#844]
### problem description

Issue: Unable to Download YouTube Video on Instance (Works Locally)

I'm experiencing an issue when trying to download a YouTube video using the following API call:

POST Request: http://xxx.xxx.xxx.xx:9000/
Request Body:

{
    "url": "https://youtu.be/......."
}

Everything works fine when running locally on localhost, but when I try to run the same code on my server instance, I get the following error:

Error Response::

{
    "status": "error",
    "error": {
        "code": "error.api.fetch.critical",
        "context": {
            "service": "youtube"
        }
    }
}

Any idea what might be causing this issue or how I can resolve it?

### your instance configuration

```shell
Azure Virtual Machine
```

**Comment by KwiatekMiki** [comment]
set up cookies.

https://github.com/imputnet/cobalt/issues/687#issuecomment-2293405845
