### ISSUE TITLE
error.api.header.accept

### ISSUE THREAD

**Issue by AdolphYu** [imputnet/cobalt#845]
### bug description

{
    "status": "error",
    "error": {
        "code": "error.api.header.accept"
    }
}

### reproduction steps

docker compose up -d 
post request instance
request
{
    "url":"https://www.youtube.com/watch?v=tPEE9ZwTmy0"
}

return
{
    "status": "error",
    "error": {
        "code": "error.api.header.accept"
    }
}

### platform information

docker

**Comment by AdolphYu** [comment]
How to add configuration files to compose.yml

**Comment by AdolphYu** [comment]
I used https keys.json

**Comment by KwiatekMiki** [comment]
1. this is not a main instance issue
2. change the API_URL environment variable to the same url you use to access the api, for example `http://localhost:9000/`
