### ISSUE TITLE
Not working Instagram Stories upload

### ISSUE THREAD

**Issue by otakukz17** [imputnet/cobalt#848]
### bug description

When sending a link with a story, it returns an error:  
{  
    "status": "error",  
    "error": {  
        "code": "error.api.link.unsupported",  
        "context": {  
            "service": "instagram"  
        }  
    }  
}

### reproduction steps

Sending a link to Instagram Stories

### platform information

Arc Browser

**Comment by wukko** [comment]
stories aren't supported
