### ISSUE TITLE
Also provide an option to get stream url for video and audio so that it can be played without downloading

### ISSUE THREAD

**Issue by Shashwat-CODING** [imputnet/cobalt#850]
### describe the feature you'd like to see

Also provide an option to get stream url for video and audio so that it can be played without downloading

### additional context

Also provide an option to get stream url for video and audio so that it can be played without downloading

**Comment by KwiatekMiki** [comment]
https://cobalt.tools/settings/download#saving

also because it's a stream iirc you won't be able to go forward and probably back, depends where
