### ISSUE TITLE
sometimes doesn't download the whole video

### ISSUE THREAD

**Issue by UltimateRiff** [imputnet/cobalt#853]
### bug description

I've found at least one YouTube video that consistently doesn't download the full length. doesn't seem to be a consistent length, I got anywhere from 20-40 minutes of the almost 90 minute video (first link below)

had the issue both with auto and audio mode

### reproduction steps

1. download a long video
2. see the length isn't correct

### links

```shell
https://www.youtube.com/watch?v=1qG9FcCnEYQ\

this one worked properly a few days ago, but is now having the same issue
https://www.youtube.com/watch?v=xr0at29iqxk
```

### platform information

Firefox 131.0.3 on WIndows 11

**Comment by UltimateRiff** [comment]
wasn't sure if this should go under the main instance or the codebase, but I'm having the issue on the main instance

**Comment by UltimateRiff** [comment]
submitted the ticket while still testing, the second link did download the full video today as well as a few days ago, but in audio mode it also had the same issue as the first link

the first link is having the same issue both for video and audio tho, so it could apply to both modes

**Comment by KwiatekMiki** [comment]
#647
