### ISSUE TITLE
Downloading audio only results in shortened length for long videos

### ISSUE THREAD

**Issue by mdeiana** [imputnet/cobalt#854]
### bug description

I hope I'm not doing something wrong, but setting the download option to Audio and downloading a long video, in my case [this 3h long one](https://www.youtube.com/watch?v=NWlFKrzvsm0), results in the download of a file that, when the download is completed, is of length that is variable but much much shorter than that of the video it comes from.

I've tried this twice so far, and the file lengths were of 36:01 and 45:02. I haven't tried more than twice because of spotty internet, but hopefully you can reproduce this.

Please let me know if I've done something wrong in the process or in reporting this issue.

### reproduction steps

1. Set Audio mode in main Save page
2. Insert URL: https://www.youtube.com/watch?v=NWlFKrzvsm0
3. Start the download and check the resulting audio file's length.

### links

```shell
https://www.youtube.com/watch?v=NWlFKrzvsm0
```

### platform information

Google Chrome 129.0.6668.101 (Official Build) (64-bit) (cohort: Stable)

**Comment by KwiatekMiki** [comment]
#647
