### ISSUE TITLE
cannot download youtube videos (i can't access this video. it may be restricted on youtube's side. have you pasted the right link?)

### ISSUE THREAD

**Issue by BentleyBentayga** [imputnet/cobalt#855]
### bug description

EVERY TIME I TRY TO DOWNLOAD A YOUTUBE VIDEO LIKE A VOCALOID SONG I WANTED TO DOWNLOAD IT HAPPENED LIKE THIS, IT'S NOT RESTRICTED YET EVERYTHING ASSUMED IT IS SAID FROM THIS BUG PLEASE FIX IT I WANTED TO DOWNLOAD I

### reproduction steps

1. go to cobalt and paste yt link
2. click download
3. see this error

### screenshots

![image](https://github.com/user-attachments/assets/f9ba137a-7c8b-4819-a5aa-565dace2e920)

### links

```shell
https://www.youtube.com/watch?v=VUI8v0rAAl8
```

### platform information

google chrome on windows 11

**Comment by TheWhiteRaven1** [comment]
Im having the same problem, I even tried downloading past files I had before
![IMG_2816](https://github.com/user-attachments/assets/96adea9b-b03a-4770-af61-714c3c117760)

**Comment by wukko** [comment]
hey, i'm aware of dummy accounts going bad on one of processing servers, i'll update them asap

**Comment by TheWhiteRaven1** [comment]
Thank you.

**Comment by TheWhiteRaven1** [comment]
Can you let me know when it’s fixed?

**Comment by wukko** [comment]
yep, all fixed now

**Comment by TheWhiteRaven1** [comment]
Thanks also why is it that half the time it cuts off a video at random points? Just thought I should ask.

**Comment by wukko** [comment]
#647

**Comment by BillyOwilly62** [comment]
> yep, all fixed now

yeah, real fixed now, isn't it?

**Comment by wukko** [comment]
> yeah, real fixed now, isn't it?

im in process of refreshing account cookies, don't be a dick :)

**Comment by wukko** [comment]
@BillyOwilly62 real fixed now, it is :)

**Comment by Plantdrew** [comment]
I’m also having the same issue with downloading YouTube videos now; it says the video is restricted even when it’s not. Any updates on how to resolve this?
![IMG_4476](https://github.com/user-attachments/assets/71c41495-09d5-4939-9ed7-c986af10fef5)

**Comment by Larddral** [comment]
Hi wukko, i'm having the same issue when downloading this song https://www.youtube.com/watch?v=QryAnD3kxBc

**Comment by dumbmoron** [comment]
> i'm having the same issue when downloading this song https://www.youtube.com/watch?v=QryAnD3kxBc
> Platform: Macbook Air M1

@Larddral the video is region restricted

**Comment by Larddral** [comment]
@dumbmoron It's available in the region where i live, what region do you live in?
