### ISSUE TITLE
users blocked by the api

### ISSUE THREAD

**Issue by madkarmaa** [imputnet/cobalt#857]
### bug description

hey, [it's me again](https://github.com/imputnet/cobalt/issues/605), users are reporting [the same issue](https://github.com/madkarmaa/youtube-downloader/issues/16#issuecomment-2424051393) as the last time

### reproduction steps

- click on the download button of my extension
- fetch fails

### platform information

any browser

**Comment by KwiatekMiki** [comment]
cobalt doesn't have a public api anymore, host your own instance.

https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md

**Comment by KwiatekMiki** [comment]
> download button of my extension

user scripts aren't extensions

**Comment by madkarmaa** [comment]
> cobalt doesn't have a public api anymore

why is it so? when did it change?

**Comment by madkarmaa** [comment]
> user scripts aren't extensions

my bad, typo

**Comment by KwiatekMiki** [comment]
> why is it so?

people were abusing it

**Comment by wukko** [comment]
just posted more info here: https://github.com/imputnet/cobalt/discussions/860
