### ISSUE TITLE
Lengthy videos from YouTube not downloaded

### ISSUE THREAD

**Issue by AnasDS-alt** [imputnet/cobalt#861]
### bug description

If I am downloading an audio/video of say, length, 1:50:00, Cobalt downloads only about 38 or 40 minutes. The whole audio/video is not downloaded. I tried downgrading the resolution, but it still doesnt help. Can you fix this issue?

### reproduction steps

na

### screenshots

![Cobalt2](https://github.com/user-attachments/assets/e6fe5920-e92a-4569-985e-8d79fae1f2ef)
![Cobalt1](https://github.com/user-attachments/assets/84327c08-604b-418b-8544-24b14f7b039d)

### platform information

Windows 11

**Comment by bunglegrind** [comment]
#647
