### ISSUE TITLE
"couldn't verify whether you can download this file."

### ISSUE THREAD

**Issue by RazorLeaf16** [imputnet/cobalt#865]
### bug description

I get this error when I try to download any YouTube or SoundCloud link, but then when I try to download a Twitter/X link it works perfectly fine.

### reproduction steps

1. Click download on any non-Twitter/X link
2. Get this Error

### screenshots

![error](https://github.com/user-attachments/assets/e9600259-fda8-473d-aa9a-bd4b32e89707)

### platform information

Opera GX on Windows 10 Pro

**Comment by wukko** [comment]
can you open [imput.net](https://imput.net)? does it also happen on other devices? have you tried disabling extensions?

**Comment by RazorLeaf16** [comment]
I tried disabling my adblocker and still got the same error, and when I tried downloading through my phone it gave me this.
![IMG_8622](https://github.com/user-attachments/assets/5e596b7b-0363-4e48-b466-fbd671920bec)

**Comment by wukko** [comment]
can you open imput.net on your pc though?

**Comment by RazorLeaf16** [comment]
Yes, also I figured out my issue. When I turned off my VPN it downloaded fine, so I think it might have to do with my VPN.
![Screenshot_8](https://github.com/user-attachments/assets/b8138d3a-54f3-4fa0-9ee8-53962ce6b719)

**Comment by wukko** [comment]
maybe opera vpn blocks it or something?

**Comment by RazorLeaf16** [comment]
Possibly.

**Comment by dumbmoron** [comment]
> When I turned off my VPN it downloaded fine, so I think it might have to do with my VPN.

i could not replicate this with free opera vpn, are you using any other vpn?

**Comment by RazorLeaf16** [comment]
Avast One VPN

**Comment by wukko** [comment]
please don't use that 😭

here's a good vpn if you need it for some reason (you probably don't): https://mullvad.net/
