### ISSUE TITLE
Videos are +4 hours long according to gallery

### ISSUE THREAD

**Issue by Curiousmito** [imputnet/cobalt#869]
### bug description

this is my first time using GitHub so sorry if I do it all wrong.

My videos in the gallery show the length is 00.00 and when I open the video it says it's hours long.
I can open it with capcut without a problem but YouTube doesnt recognise the videos

### reproduction steps

Go to cobalt. Download videos
(In this case billi.billi) Settings 4k av1
Download 
Gallery

### screenshots

![Screenshot_2024-10-28-22-58-36-57_29b563cd0bc4fd07bd0c105b17b28204](https://github.com/user-attachments/assets/0e4be417-1c9a-433b-9b96-10ff69008c20)

### platform information

Nord 3 google chrome

**Comment by wukko** [comment]
remuxing fixes compatibility issues with old software: https://cobalt.tools/remux
