### ISSUE TITLE
tiktok slideshows have corrupted audio

### ISSUE THREAD

**Issue by dncVinny** [imputnet/cobalt#870]
### bug description

when you use a tiktok slideshow link & attempt to download the audio, you get a 0B file.

### reproduction steps

1. find any tiktok slideshow with audio
2. try to download audio

### platform information

Win 11, Google Chrome

**Comment by dumbmoron** [comment]
> ### links
> _No response_

could you provide an example link where this happens?

**Comment by dumbmoron** [comment]
also could you [enable debug features](https://cobalt.tools/settings/advanced#debug) and copy your settings [from the debug page](https://cobalt.tools/settings/debug)?

**Comment by dncVinny** [comment]
https://www.tiktok.com/t/ZTFpqBsod/

this also doesn't work when I use my self hosted instance

`{"schemaVersion":2,"appearance":{"theme":"auto","reduceTransparency":false,"reduceMotion":false,"autoLanguage":false},"privacy":{"disableAnalytics":false,"alwaysProxy":true},"save":{"youtubeVideoCodec":"h264","videoQuality":"1080","audioFormat":"mp3","downloadMode":"auto","filenameStyle":"classic","savingMethod":"download"},"processing":{"enableCustomInstances":false},"advanced":{"debug":true}}`

**Comment by gitomatikus** [comment]
"Hey, I have the same problem and found a temporary solution. Add `"audioFormat": "best"` to the body since `"audioFormat": "mp3"` (default value) is returning an empty file."

**Comment by dncVinny** [comment]
Appreciate the insight 👍

> Hey, I have the same problem and found a temporary solution. Add `"audioFormat": "best"` to the body since `"audioFormat": "mp3"` (default value) is returning an empty file.

**Comment by wukko** [comment]
should be fixed now, thank you for the report :3
