### ISSUE TITLE
couldn't connect to the processing server. check your internet connection and try again.

### ISSUE THREAD

**Issue by BentleyBentayga** [imputnet/cobalt#871]
### bug description

i wanted to download my music i'm interested but I CAN'T AND I HAVE A PROBLEM, EVERYTIME I DOWNLOAD I GET THIS ERROR

### reproduction steps

1. go to cobalt
2. click the link in the textbox
3. try to download it
4. get this error

### screenshots

![image](https://github.com/user-attachments/assets/e4a02c7b-095d-4396-be83-70c4e7e1d992)

### links

```shell
https://youtu.be/jE65lSPst8U
```

### platform information

google chrome on windows 11

**Comment by wukko** [comment]
does it work now?

**Comment by wukko** [comment]
ill just assume it does

**Comment by hoobanger** [comment]
Always get this error on my PC, but  download normal with VPN on android.
