### ISSUE TITLE
cant download this one specific video

### ISSUE THREAD

**Issue by copylef** [imputnet/cobalt#872]
### bug description

cobalt cant download this video: https://www.youtube.com/shorts/654nhKfz5Vs 
changing "shorts" to "watch" doesnt work either. 
i can download other videos, just not that one
it's only the video part. downloading audio works just fine

### reproduction steps

put the url into cobalt, select auto or mute, and hit enter 

### screenshots

![la creatura](https://github.com/user-attachments/assets/9df10503-b19b-4d8a-9302-cbc8a3ea980b)

### links

```shell
https://www.youtube.com/shorts/654nhKfz5Vs
https://www.youtube.com/watch?v=654nhKfz5Vs
```

### platform information

windows 10 version 19045.5011 and google chrome version 130.0.6723.70 (Official Build) (64-bit)

### additional context

seriously thank you for this website i cant imagine going back to googling youtube to mp3 and praying

**Comment by wukko** [comment]
seems to work for me too, do you use any specific settings?

**Comment by wukko** [comment]
figured out why this was happening, can you try now?

**Comment by copylef** [comment]
wow you guys work fast. anyway it works thank you thank you!

the video works fine on discord and twitter, although random thing (it doesnt bother me just putting in here just cause) it works weird opening it on desktop (video format only, audio is fine).
VLC media player: lists the video's duration as 5 seconds, plays the full 9, and skipping to a specific part of the video can put you at a different part than you expect
windows media player: doesnt list the video's full duration, if you try skipping to a specific part of the video it restarts it, plays the full 9
"media player" (cool name microsoft): doesnt list the video's full duration, cannot skip period, plays the full 9
movies & tv: doesnt list the video's full duration, gives you the illusion of being able to skip but alas it doesnt work, plays the full 9

my settings are: 
appearance: theme auto, automatic selection for language
video: 360p, mp4 format, convert twitter looping videos to gif
audio: .mp3 format, 128kb/s bitrate, 
downloading: basic filename style, download saving method, 
every other slider is off

random thing i noticed while typing that: the setting for format and quality have swapped positions on the video and audio settings. maybe that was intentional that's fine i just know some people like it to be orderly

**Comment by wukko** [comment]
have you tried remuxing? https://cobalt.tools/remux

if video has a weird length or doesn’t download fully, you can try enabling hls formats: https://cobalt.tools/settings/video#youtube-hls

**Comment by copylef** [comment]
oh shit lol i had no idea it could be used for things like that. thank you very much
that is all from me for now. thank you for your quick response to my little query
