### ISSUE TITLE
Allow a way for user to download the raw info json video data from a given instance.

### ISSUE THREAD

**Issue by barkoder** [imputnet/cobalt#875]
### describe the feature you'd like to see

cobalt seems to be – at the moment at least – the only service that's able to somehow get past YT's age-restriction for *some* videos.

The problem is #647 . Downloads getting interrupted mid transmission, and ffmpeg can't switch proxies and continue muxing where it 403 errored.

This issue also happens when I use yt-dlp(for non age restricted vids), but it works when I switch to a different IP to download the file using the same info.json .

However, yt-dlp fails to download age-restricted videos at the moment.

But cobalt works.

So I was wondering if you could allow a way for the user to grab the raw info.json (`yt-dlp --write-info-json`) file that cobalt used to crawl a YT video's webpage?
This would be especially useful for age restricted vids. The user may then use `yt-dlp --load-info-json` (or some other software) to cycle through IPs and eventually successfully download the video.

Thanks!

**Comment by barkoder** [comment]
Hi, thanks for that suggestion, but I tested 7 videos. It randomly cut off 2 of them. It's inconsistent.

If I had access to the info.json , I could just download the vids straight off of YT.

**Comment by wukko** [comment]
we’re not gonna do that, there’s no “info.json” in the first place
