### ISSUE TITLE
New v10 API quality parameter not work

### ISSUE THREAD

**Issue by ShirokamiRyzen** [imputnet/cobalt#877]
### bug description

When i use [new API parameter](https://github.com/imputnet/cobalt/blob/main/docs/api.md) like videoQuality it doesn't work

With videoQuality
![image](https://github.com/user-attachments/assets/2ccc8809-2cdc-4c93-b2d0-a363b4e27fbb)

Only Url
![image](https://github.com/user-attachments/assets/43da0d52-f6d1-4873-9f9b-bddbe1aa8209)

### reproduction steps

add videoQuality to body request

### platform information

Ubuntu 22.04

**Comment by dumbmoron** [comment]
https://github.com/imputnet/cobalt/blob/c3a23860863e2597a4235f42ba4f39d21792e359/docs/api.md?plain=1#L61

**Comment by wukko** [comment]
hey, video quality is a string, as mentioned in docs. adding quotes ("720") should help

**Comment by ShirokamiRyzen** [comment]
> hey, video quality is a string, as mentioned in docs. adding quotes ("720") should help

fixed, i dont see it 😂

**Comment by lpwyz** [comment]
Hello, I have a question to consult with you. Why can the YouTube address parsed by the cobalt instance you are running be opened normally, while the cobalt instance I am running on Docker returns the following address:


http://localhost/tunnel?id=typQSv_vR -wzU4LSNfcCZ&exp=1730775031019&sig=OBSAUAG8-yiQri0n_gRWVAvurea8-p0s7HtJ0rnd7T4&sec=D7313RNEdJim4ugVmnHjqul80_GAhW1-QgoNCOFEO1Q&iv=z13HimGtJg6-GBrKC7qYvg

An address similar to this

**Comment by lpwyz** [comment]
> > 嘿，视频质量是一个字符串，如文档中所述。添加引号（“720”）应该有帮助
> 
> 已修复，我没看到😂

Hello, I have a question to consult with you. Why can the YouTube address parsed by the cobalt instance you are running be opened normally, while the cobalt instance I am running on Docker returns the following address:


http://localhost/tunnel?id=typQSv_vR -wzU4LSNfcCZ&exp=1730775031019&sig=OBSAUAG8-yiQri0n_gRWVAvurea8-p0s7HtJ0rnd7T4&sec=D7313RNEdJim4ugVmnHjqul80_GAhW1-QgoNCOFEO1Q&iv=z13HimGtJg6-GBrKC7qYvg

An address similar to this

**Comment by ShirokamiRyzen** [comment]
> Hello, I have a question to consult with you. Why can the YouTube address parsed by the cobalt instance you are running be opened normally, while the cobalt instance I am running on Docker returns the following address:
> 
> http://localhost/tunnel?id=typQSv_vR -wzU4LSNfcCZ&exp=1730775031019&sig=OBSAUAG8-yiQri0n_gRWVAvurea8-p0s7HtJ0rnd7T4&sec=D7313RNEdJim4ugVmnHjqul80_GAhW1-QgoNCOFEO1Q&iv=z13HimGtJg6-GBrKC7qYvg
> 
> An address similar to this

you need to type your domain on environment variable, otherwise you cant access the link
