### ISSUE TITLE
Enable Proxy Configuration via Environment Variables

### ISSUE THREAD

**Issue by mmahdium** [imputnet/cobalt#880]
### describe the feature you'd like to see

Enable the specification of SOCKS/HTTP/HTTPS proxies through environment variables to facilitate dynamic IP changes for the instance.

**Comment by dumbmoron** [comment]
https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md?plain=1#L58

https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md?plain=1#L64

![tenor (1)](https://github.com/user-attachments/assets/82818bef-5226-4337-83ff-a27b5cecbe4f)

**Comment by mmahdium** [comment]
Oops! My bad. I misunderstood the proxy setup—I thought you meant tunneling through another instance. Seems like I missed some crucial details in the description! :-)
