### ISSUE TITLE
Accept our cookie text file during download desired age-restricted youtube video

### ISSUE THREAD

**Issue by oti5** [imputnet/cobalt#884]
### describe the feature you'd like to see

We can export our cookie data from our browser with an cookie.txt file saver extension and via this cookie txt file (if you able watching age-restricted contents with your Google account because you passed to enable after authentication) and read Cobalt our authentication token from txt file during age-restricted video downloading (not logging our auth tokens forever). This function working in yt-dlp. 

### additional context

We cannot download age-restricted contents from youtube with Cobalt.

**Comment by wukko** [comment]
this will not happen, as it's a security risk.

**Comment by barkoder** [comment]
@wukko Why have the downloading of age restricted videos been disabled? It used to work ~5 days before?

See #884 .
