### ISSUE TITLE
Cobalt downloads all YT videos using UNWATED "StAbLe VoLuMe FeAtUrE" audio quality ruining video stream [pretty much CRITICAL]

### ISSUE THREAD

**Issue by WARUMBERG** [imputnet/cobalt#887]
### bug description

There are now TWO separate video streams for each YT video - one with regular audio, and one heavily processed and re-compressed literally unlistenable/'useless DRC audio track aka "Stable Volume enabled" one.

On YT site, you chose which one you want by enabling/disabling the "Stable Volume" in the video player options (by default it's ON), and the YT remembers the chosen setting per their site account.
Cobalt always grabs the "Stable Volume" one and I literally can't work with that. 

Make that thing go away, this service should grab videos with it always OFF since that new YT "feature" is yet another misimplemented/faulty by poor desing, as it does none of what it's advertised as, and instead completely destroys the audio quality.

I HATE THE STABLE VOLUME
I HATE THE STABLE VOLUME
I HATE THE STABLE VOLUME
I HATE THE STABLE VOLUME

### reproduction steps

Pick any YT video with "Stable Volume" toggle being present in the video player settings (the cog).
Either download locally (YT DLP?) or record the audio, one with "Stable Volume" enabled, and one with disabled.
Use Cobalt to download the same video.
Open the 3 audio tracks in any program that allows you to view the volume spectrums, and compare them... to find out that Cobalt always downloads the "Stable Volume" DRC enabled track, the bad, pure evil, guy of tracks.

### links

```shell
https://www.audiosciencereview.com/forum/index.php?threads/youtubes-new-dynamic-range-compression-drc.37326/
```

### platform information

All browsers on all platforms

**Comment by KwiatekMiki** [comment]
enable https://cobalt.tools/settings/video#youtube-hls and try downloading again

**Comment by KwiatekMiki** [comment]
also in the links section you were supposed to give video links that cause this

**Comment by wukko** [comment]
you ignored all required issue prompts, i can’t even debug this properly

**Comment by lostdusty** [comment]
isnt stable volume a premium feature

**Comment by lpwyz** [comment]
> you ignored all required issue prompts, i can’t even debug this properly

Hello, can you help me check the issue with the local cobalt instance 889 in the issues that cannot obtain YouTube cookies? I really can't figure it out and I'm really sorry to trouble you

**Comment by wukko** [comment]
@WARUMBERG create a proper issue next time or we won't be able to help you
