### ISSUE TITLE
480p download does not work

### ISSUE THREAD

**Issue by bf7041** [imputnet/cobalt#892]
### bug description

When I set the download to 480p - it downloads videso at 1080p - all other video quality options seem to work, except 480p which just defaults to 1080p.

### reproduction steps

go to settings
click on video
click on 480p
go back to save area and download video
it will download in 1080p

### platform information

windows 10 and android 14

**Comment by KwiatekMiki** [comment]
can you provide links that you are trying to download

**Comment by bf7041** [comment]
It was a YouTube link from a family funeral (so am not comfortable posting the link here)- It will download in 1080p, 720p, and 360p, but not 480p - (which is the size i was hoping for).  When choosing 480p it just downloads in 1080p.
I did try 480p with another youtube video, and it worked, so I am drawing the conclusion it is just this particular youtube video.

Would that be a fair conclusion?  In other words, is it possible that not all you tube videos can be downloaded in  all the above formats.
John

**Comment by wukko** [comment]
does it still happen? i tried several links and they all seem to work, so i'll close this issue for now.
