### ISSUE TITLE
cobalt.tools page doesn't load in Russia due to local ECH ban

### ISSUE THREAD

**Issue by mrksbgg** [imputnet/cobalt#893]
### bug description

Tried to open cobalt.tools page, but it doesn't load, probably because of blocking ECH in Russia ( https://community.cloudflare.com/t/access-issues-in-russia-unable-to-disable-ech-in-free-plan/733401 , https://community.cloudflare.com/t/cannot-access-sites-from-russia/733159 )

ISP: Beeline
City: Kazan

### reproduction steps

1. be in Russia with Russian IP
2. open cobalt.tools
3. tada

### screenshots

![image](https://github.com/user-attachments/assets/44d0767f-a531-4c57-b907-aa7507566a3a)

### platform information

Windows 11 Version 23H2 (Build 22631.4317), Chrome 130.0.6723.93

**Comment by mrksbgg** [comment]
![image](https://github.com/user-attachments/assets/e6d8d432-6499-4903-afdf-1024dc7eec7c)
![image](https://github.com/user-attachments/assets/70bdaee7-4d2d-42a8-9c3b-f0db539a7353)
Hm, it works on Kali on WSL, strange

**Comment by wukko** [comment]
unfortunately we can't do anything about it without impacting privacy & security for everyone outside of russia, you'll have to use proxy/vpn/etc to get around local restrictions
