### ISSUE TITLE
I have two very important things to consult about cobalt instances:

### ISSUE THREAD

**Issue by lpwyz** [imputnet/cobalt#896]
### problem description

I have two very important things to consult about cobalt instances:

(1) When I successfully generated youtube_oauth by running the recommended 'npm run token: YouTube' and following the steps. In my case, it also has a cookie expiration time of 1 day, which is 24 hours. Does this mean that I have to regenerate new cookies every 24 hours
(2) The format of the YouTube download link obtained by Cobalt is as follows:

{
"status": "tunnel",
"url": " https://ip/tunnel?id=dOxx&exp=xx&sig=xx7S7kVVixVuFzSnOtGbxP8&sec=xxrAFJsrpIrKkXXMJi12a47Q64UKik&iv=xxYcKefbA ",
"filename": "youtube_4sPesmcW9yM_1080x1920_h264.mp4"
}

From the URL, it appears that this video was downloaded from my own server. Does that mean that every time I download a Youtbe video, I need to use my own server's broadband and consume data from my own server

**Comment by lpwyz** [comment]
Hello, when I successfully ran the cobalt instance, www.xx.com, and exposed the hidden port using nginx, I found that entering www.xx.com to directly access the browser would result in an HTML message. Can I hide this HTML or modify the pages inside

**Comment by lpwyz** [comment]
Or can we change it to this way? When configuring nginx, www.xx.com: 9000 can access the API, and the URL returned by the API does not include the 9000 port number. You can also download tunnel videos

**Comment by dumbmoron** [comment]
i assume this is related to https://github.com/imputnet/cobalt/issues/902, so i will reiterate: if you do not wish to expose cobalt on port 9000, you need to configure a reverse proxy server (such as nginx)
