### ISSUE TITLE
Provide optional extracted data in the API response

### ISSUE THREAD

**Issue by m-ehsan** [imputnet/cobalt#900]
### describe the feature you'd like to see

Is it appropriate to provide some extra service-specific data related to the media that has been extracted in the API response? Data items like **tweet text**, Instagram post **caption** and ...

In my opinion those kind of data are still public and are tightly related to the media file that the user has requested. In addition they are already accessible in the fetched data. Having an optional field in the API response can satisfy needs of more users.

I suggest adding the field below to `tunnel`, `redirect` & `picker` response types:
| key          | type     | values                                                      |
|:-------------|:---------|:------------------------------------------------------------|
| `misc`     | `object` | **optional** extra data related to the requested media       |

And of course this `misc` field would be service-dependent and dynamic, leaving room for future changes in the returned items. Also there will be no assurance for it to contain the same set of items every time, it may even contain no items at all. It just should return any relevant item that is possible.

example value of `misc` field for Instagram service:
```
{
    "caption_text": "..."
}
```
Other accessible fields that might be relevant: `comment_count`, `like_count`, `play_count`, `taken_at`

What do you think? Is this a reasonable feature for this project?

**Comment by wukko** [comment]
cobalt is not a youtube api wrapper, it’s a downloader

plus, this info is useless unless you use the api for scraping

**Comment by dumbmoron** [comment]
from CONTRIBUTING.md:

> ## adding features or support for services
> ... the cobalt api is built to assist people **only with downloading freely accessible content**. other functionality, such as:
> ...
> - scraping unrelated information & exposing it outside of file metadata
> will not be reviewed or merged.

cobalt is a media downloader tool, not a webscraping tool
