### ISSUE TITLE
Video becomes 3 years long when I download it

### ISSUE THREAD

**Issue by Guy-real** [imputnet/cobalt#901]
### bug description

It doesn't matter what I do, the video I download will always be literally 3 years long. I have no clue why this happens and I haven't seen any one else mention it. I have tested this on google chrome and firefox and it's broken on both of those. Sorry if this has issues I have never submitted a bug report on github before.

### reproduction steps

1. download any video
2. try to trim the video
3. notice it's 3 years long and almost impossible to actually trim

### screenshots

![image](https://github.com/user-attachments/assets/343ed560-0339-402f-b8d4-0eab72d16c8b)

### platform information

Omen computer

**Comment by KwiatekMiki** [comment]
https://cobalt.tools/remux

**Comment by Guy-real** [comment]
For some reason I have to remux the video twice for it to fix
