### ISSUE TITLE
AV1/VP9 Codec Issue on YouTube Downloads?

### ISSUE THREAD

**Issue by d31220207** [imputnet/cobalt#905]
### bug description

Is there an issue on the server with **AV1 and VP9** codecs for YouTube? I've been trying, but the downloaded files keep automatically **switching to H.264.**

### reproduction steps

I've tried various instances, and the result is the same, even with version 7.

### platform information

Windows

**Comment by wukko** [comment]
why did you ignore the links section? we can’t debug it without samples. create a new issue.

also, cobalt falls back to a format that’s available if either of them is not served by youtube. it says so in the codec toggle description.
