### ISSUE TITLE
Restricted link or couldn't connect to processing server

### ISSUE THREAD

**Issue by BillyOwilly62** [imputnet/cobalt#906]
### bug description

the link isn't restricted, I'm connected home internet, and I pasted the right link and everything, every single link I try to paste and download will lead to the same errors, and I've tried to download random videos on 3 different devices, and all of them wouldn't work. Cobalt used to be the ONLY no bullshit, ad free, web,  multi-platform video downloader, and now it is broken as shit, and it has a new bug every time I check back. I might have to just leave cobalt and wait an eternity for a new no bullshit video downloader.

### reproduction steps

1. Go to Cobalt on anything 2. Paste any link 3. Get one of the two errors

### screenshots

![20241112_000325](https://github.com/user-attachments/assets/ed5c5153-8ef4-4ba7-9bbe-5ca27780cb9a)

### links

```shell
literally any link
```

### platform information

windows 10, opera gx, Google Chrome. Samsung internet

**Comment by BillyOwilly62** [comment]
wow, ain't this guy handsome?

**Comment by wukko** [comment]
does it work now? there are no issues from our side.

**Comment by wukko** [comment]
closed as you're clearly not in the right mindset and i can't replicate it

**Comment by dumbmoron** [comment]
>  I might have to just leave cobalt and wait an eternity for a new no bullshit video downloader.

![](https://media1.tenor.com/m/pqZjTzbdglwAAAAd/okay-tyler-the-creator.gif)

**Comment by yorunoken** [comment]
gotta love entitled people who complain free & open source projects not working when they can't even write 0.005% of the codebase
