### ISSUE TITLE
download failed (account error, verification error)

### ISSUE THREAD

**Issue by maple-underscore** [imputnet/cobalt#913]
### bug description

this happens every time i try to download a youtube video now. even across edge and chrome.
also, status page says all operational.

### reproduction steps

cobalt.tools
4k or 1440p, hls enable or disable

### screenshots

![Screenshot 2024-11-13 121810](https://github.com/user-attachments/assets/7e387091-8a18-41ea-985a-a366bb25ec2a)
![Screenshot 2024-11-13 121832](https://github.com/user-attachments/assets/c15326b1-0c29-4e76-b9f7-3c7edf39c8ed)

### links

```shell
https://www.youtube.com/watch?v=1uOE3Uj0sWc
```

### platform information

windows 11

### additional context

lenovo computer, microsoft edge and google chrome

**Comment by dumbmoron** [comment]
hi, i can't reproduce this issue as of right now. could you try again? (can you also check that you are using the main instance in [settings](https://cobalt.tools/settings/instances)?)
