### ISSUE TITLE
Cannot automatically update YouTube's cookie expiration date

### ISSUE THREAD

**Issue by lpwyz** [imputnet/cobalt#914]
### problem description

Hello, I used Docker to build the Cobalt project and successfully created a cookie file with 5 tokens. However, I found that today is the third day of the project running, and when I called the API to request YouTube, it surprisingly returned:
{
"status": "error",
"error": {
"code": "error.api.youtube.token_expired"
}
}

Do I remember that the Cobalt project does not automatically update the expiration date of cookies? The default validity period is one day? If it cannot be automatically updated, I wouldn't need to manually update cookies every day, would I

**Comment by wukko** [comment]
cookies update automatically, your google account probably got banned
