### ISSUE TITLE
Running Cobalt with Docker, Instagram and Facebook link requests are failing.

### ISSUE THREAD

**Issue by coderooo** [imputnet/cobalt#919]
### problem description

`{
    "status": "error",
    "error": {
        "code": "error.api.fetch.fail",
        "context": {
            "service": "facebook"
        }
    }
}`

I don't know how to obtain these cookies. Are there any related tutorials?

![image](https://github.com/user-attachments/assets/45a8f355-64f5-41a5-b959-44852b8fc844)

**Comment by swaehwdp** [comment]
+1

**Comment by KwiatekMiki** [comment]
> { "status": "error", "error": { "code": "error.api.fetch.fail", "context": { "service": "facebook" } } }

With what links does this happen?

---

> I don't know how to obtain these cookies. Are there any related tutorials?
> 
> <img src="https://private-user-images.githubusercontent.com/24584714/386425017-45a8f355-64f5-41a5-b959-44852b8fc844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzQzNTksIm5iZiI6MTczMjM3NDA1OSwicGF0aCI6Ii8yNDU4NDcxNC8zODY0MjUwMTctNDVhOGYzNTUtNjRmNS00MWE1LWI5NTktNDQ4NTJiOGZjODQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE1MDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZTg3MDVmNmI2ZjBkYzAzMzQ0MjRiYmQ0MmI1ZmM1ZDFjNjQwNGMxMmQ1NmMxMDdjZWEwYTIyNmFjY2RiZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.joMj7wgHrYfA4LGqznIkuvNt0yxGyB060S0B4axPLXs" width="300">

They are unrelated (they're for Instagram, not Facebook), but here's a tutorial in case someone needs it:

**"instagram" cookies**
1. Open inspect element (using `CTRL+SHIFT+I` or `F12`)
2. Go to the “Application” tab and then expand “Cookies”
3. Click on “https://www.instagram.com" below “Cookies”
4. Copy the contents of mid, ig_did, csrftoken. ds_user_id and sessionid cookies content and paste them in place of `<replace/with/your/own/cookies>`.

**"instagram_bearer" cookies**
idk how to get these
