### ISSUE TITLE
youtube使用

### ISSUE THREAD

**Issue by swaehwdp** [imputnet/cobalt#920]
### problem description

![Screenshot_2024-11-15-10-37-46-959](https://github.com/user-attachments/assets/453c993e-d253-4462-a84d-f28339ed6c48)
![Screenshot_2024-11-15-10-38-22-242](https://github.com/user-attachments/assets/1b840df6-8e9e-4951-9b5f-815590e27317)
这个怎么才能用

**Comment by wukko** [comment]
youtube is probably blocked on your network, you have to use a proxy

**Comment by dave2nian** [comment]
用这个，https://cobalt.tools/  ，问题有1-2周。 webpage 能移掉了。

**Comment by swaehwdp** [comment]
> 用这个，https://cobalt.tools/ ，问题有1-2周。webpage 能移掉了。

就启动了api，api能用。就是添加不了cookie，

**Comment by dave2nian** [comment]
我的是在 qnap Nas 上的docker 运行，api没弄明白。如果只是下载ytb, 有个命令行工具 yt-dlp, 给他加个web壳，不用敲命令行

**Comment by wukko** [comment]
please talk in english, translators misinterpret some words :(

**Comment by dave2nian** [comment]
Hi wukko, I will do it  next relays.

**Comment by KwiatekMiki** [comment]
did you do it?
