### ISSUE TITLE
Cannot Access YT videos... Error Message Shown Below

### ISSUE THREAD

**Issue by asafa77** [imputnet/cobalt#921]
### service name

cobalt

### service description

Hello. I am getting the below error message when trying to download videos from YouTube. I have downloaded countless videos and only now am I getting this message. Thank you. 

"i can't access this video. it may be restricted on youtube's side. have you pasted the right link?"

### link samples

```shell
https://www.youtube.com/watch?v=pduPYF3mNCU&t=5s
```

**Comment by wukko** [comment]
should be all good now!

**Comment by asafa77** [comment]
Thank you for the quick fix! Is there something I can do to prevent this
from occurring again?
