### ISSUE TITLE
Unable to download from Youtube, suspected expired dummy Youtube accounts

### ISSUE THREAD

**Issue by keannyooi** [imputnet/cobalt#922]
### bug description

hi, i'm currently trying to download audio from youtube, however it seems like downloading from any youtube link returns the same error message: "i can't access this video. it may be restricted on youtube's side. have you pasted the right link?"

i did a little bit of research and it seems like this issue has something to do with dummy youtube accounts that cobalt relies on to run, could refreshing them solve this issue? [#759 ]

### reproduction steps

1. Go to youtube.com
2. Copy any video link from Youtube
3. Go to cobalt.tools
4. Paste link from Youtube
5. An error message should pop up saying "i can't access this video. it may be restricted on youtube's side. have you pasted the right link?"

### screenshots

![Screenshot 2024-11-15 114951](https://github.com/user-attachments/assets/bd0ee99b-08e6-4d23-88bc-77121d0a7d0d)

### platform information

Mozilla Firefox 132.0.2 on Windows 11

**Comment by Manmademan360** [comment]
I've been having the same problem, and it seems like this happened beg re so they should be able to fix it.

**Comment by wukko** [comment]
@keannyooi @Manmademan360 should be fixed now
