### ISSUE TITLE
Unable to Download Video: “Couldn’t connect to the processing server” Error

### ISSUE THREAD

**Issue by vstar37** [imputnet/cobalt#926]
### problem description

##Description:
I deployed the Cobalt API and Watchtower using docker-compose. After deployment, I verified the following:
	1.	Services Running Normally: Both cobalt-api and watchtower are running without issues.
	2.	API Accessibility: Curling the API at port 9000 (e.g., curl http://myipv4:9000) returns a normal JSON response, confirming the service is operational.

However, when setting up the instance address in the Cobalt settings page (https://cobalt.tools/settings/instances) to http://myipv4:9000 and attempting to download a video, such as:

https://youtu.be/Xtzvoyx2H3I?si=KrZkweBzQ4jBqFcQ

I encounter the following error message:
"Couldn't connect to the processing server. Check your internet connection and try again."

##Steps to Reproduce:
	1.	Deploy Cobalt API and Watchtower using Docker Compose.
	2.	Verify services are running (docker-compose ps and curl test on port 9000).
	3.	Set the instance address in https://cobalt.tools/settings/instances to http://myipv4:9000.
	4.	Attempt to download a video from YouTube via the provided Cobalt interface.

##Expected Behavior:
The video should download successfully without errors.

### your instance configuration

```shell
services:
    cobalt-api:
        image: ghcr.io/imputnet/cobalt:10

        init: true
        read_only: true
        restart: unless-stopped
        container_name: cobalt-api

        ports:
            - 9000:9000/tcp
            # if you use a reverse proxy (such as nginx),
            # uncomment the next line and remove the one above (9000:9000/tcp):
            # - 127.0.0.1:9000:9000

        environment:
            # replace https://api.url.example/ with your instance's url
            # or else tunneling functionality won't work properly
            API_URL: "http://myipv4:9000/"

            # if you want to use cookies for fetching data from services,
            # uncomment the next line & volumes section
            # COOKIE_PATH: "/cookies.json"

            # it's recommended to configure bot protection or api keys if the instance is public,
            # see /docs/protect-an-instance.md for more info

            # see /docs/run-an-instance.md for more variables that you can use here

        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

        # uncomment only if you use the COOKIE_PATH variable
        # volumes:
            # - ./cookies.json:/cookies.json

    # watchtower updates the cobalt image automatically
    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobalt --interval 900 --include-restarting
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by wukko** [comment]
can you open the :9000 url in your browser at all?

**Comment by vstar37** [comment]
> can you open the :9000 url in your browser at all?

yeah, here is the information after desensitization:: {
  "cobalt": {
    "version": "10.3.2",
    "url": "http://<REDACTED_IP>:9000/",
    "startTime": "1731732117254",
    "durationLimit": 10800,
    "services": [
      "bilibili", "bluesky", "dailymotion", "facebook", "instagram", "loom",
      "ok", "pinterest", "reddit", "rutube", "snapchat", "soundcloud",
      "streamable", "tiktok", "tumblr", "twitch", "twitter", "vimeo", "vk", "youtube"
    ]
  },
  "git": {
    "branch": "main",
    "commit": "<REDACTED_COMMIT_HASH>",
    "remote": "<REDACTED_REMOTE>"
  }
}

**Comment by KwiatekMiki** [comment]
works for me with the same docker compose file (but localhost instead of myipv4)

> "commit": "<REDACTED_COMMIT_HASH>",

you didn't have to redact it, [it's public information](https://github.com/imputnet/cobalt/commits/main/) and can be useful sometimes.

**Comment by wukko** [comment]
your browser might be blocking unsecured connections. try chrome without enforced https.
