### ISSUE TITLE
raycast tools

### ISSUE THREAD

**Issue by bigansh** [imputnet/cobalt#927]
### bug description

raycast extension not working

### reproduction steps

paste any link and try to download

### links

```shell
https://github.com/raycast/extensions/blob/c3d0f8559ef29c3e9c012ccef60b4e12b0f5694d/extensions/cobalt/README.md
```

### platform information

raycast 1.85.2

**Comment by wukko** [comment]
we don't provide raycast support, but this might be related to v7 api shutdown: https://github.com/imputnet/cobalt/discussions/860

if not, then i recommend making an issue in the raycast repo.

**Comment by bigansh** [comment]
yup, it is due to the api being shut. what's the solution?
