### ISSUE TITLE
Add option to switch languages in settings

### ISSUE THREAD

**Issue by kresimirko** [imputnet/cobalt#93]
I can't seem to find an option to switch languages in the settings and the process of switching languages appears to be entirely bound to the system locale. An option to manually pick a language would be nice.

**Comment by kresimirko** [comment]
I could possibly implement this myself and create a pull request.

**Comment by kresimirko** [comment]
alright, I'll try to make my first ever contribution to open source software :)

**Comment by ihatespawn** [comment]
this exists in the [svelte rewrite](https://github.com/imputnet/cobalt/tree/svelte)
https://github.com/imputnet/cobalt/blob/svelte/web/src/components/settings/LanguageDropdown.svelte
