### ISSUE TITLE
region locked videos from rutube aren't downloadable on the main instance

### ISSUE THREAD

**Issue by SoundBoomer** [imputnet/cobalt#930]
### bug description

I was trying to download an episode of a show, but cobalt tells me that there is no media in the links that i pasted in. Any other videos work, but specifically the ones I attached do not.

### reproduction steps

1. Copy a video link from the section below
2. Paste them into cobalt
3. You will receive an error that there is no media in the link, even though the link is valid

### links

```shell
https://rutube.ru/video/e7ac82708cc22bd068a3bf6a7004d1b1/
https://rutube.ru/video/4c229882ff2179df0ba602af00249e7a/
https://rutube.ru/video/c721dbeb0ffcf996a27d6b3b3b89e649/
https://rutube.ru/video/8e047c0a8b43e2115a25c6af47bce334/
https://rutube.ru/video/b4646da4e095b0287081f9086c80323f/
```

### platform information

Windows 10 2004 (19041.388), Firefox 132.0.2

**Comment by wukko** [comment]
all of them are region locked:

<img width="987" alt="image" src="https://github.com/user-attachments/assets/97a13868-f9cf-4131-a941-ecc737342f62">

**Comment by wukko** [comment]
this
