### ISSUE TITLE
add support for cobalt wont let me download

### ISSUE THREAD

**Issue by pobrec1to** [imputnet/cobalt#933]
### service name

colbalt help

### service description

i need help and i dont know where to ask for help! it says on the cobalt website to ask fro support on discord but i wasnt sure where to because i didnt see that channel. colbalt wont let me download. the circle keeps spinning... pls help 

### link samples

```shell
https://cobalt.tools/
```

**Comment by wukko** [comment]
bffr

**Comment by pobrec1to** [comment]
i just want help..

**Comment by pobrec1to** [comment]
where can ask for help like actually im sorry !! i just want to use cobalt.. i got a new laptop so i think its blocked like it says.. can i pls just get directed somewhere i can get help
![Screenshot 2024-11-20 133055](https://github.com/user-attachments/assets/2ec3cff5-8d4e-474c-8396-d50463fc06cd)

**Comment by wukko** [comment]
as for the cf turnstile error, you could try clearing cookies, disabling extensions, or using a vpn (or disabling it if you use it)

we don't control it, so there's not much we can do

**Comment by pobrec1to** [comment]
ohhhh okay… sorry for the confusion and thank u for ur help!
