### ISSUE TITLE
 Can the API support returning video file size information?

### ISSUE THREAD

**Issue by coderooo** [imputnet/cobalt#935]
### describe the feature you'd like to see

Used to calculate download progress

**Comment by KwiatekMiki** [comment]
https://github.com/imputnet/cobalt/issues/760#issuecomment-2358184016

**Comment by lostdusty** [comment]
if its possible to know the download size, it will be in headers, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length
