### ISSUE TITLE
something went wrong when fetching info from youtube

### ISSUE THREAD

**Issue by BentleyBentayga** [imputnet/cobalt#936]
### bug description

trying to upload something but i found an error saying inside the photo shown in this post

### reproduction steps

1. go to cobalt
2. paste link
3. try to download
4. get error

### screenshots

![image](https://github.com/user-attachments/assets/1a5ae969-ee89-42be-b345-e45a7000b6e1)

### platform information

google chrome on windows 11

**Comment by wukko** [comment]
hey! can you try again to see if it still happens? i just did, didn't get any errors

**Comment by BentleyBentayga** [comment]
still working fine tho
