### ISSUE TITLE
TikTok module is down or can’t download anything due to new (?) share links.

### ISSUE THREAD

**Issue by caner-cetin** [imputnet/cobalt#937]
### bug description

Hi. Whenever I click “copy link” when sharing from tiktok, I get a link like this

https://vt.tiktok.com/ZSj9VwD1o/
Bu gönderi TikTok üzerinden paylaşılır. Daha fazla gönderi için TikTok'u indirin: https://vt.tiktok.com/ZSj9VWdDE/

and of course, out of reflex, i just copy paste whatever the output i get from that share button from tiktok. and. it doesnt work.

if i copy paste the link itself manually, again, i get “tiktok module returned unrecognized error” message. 

### reproduction steps

link is provided, settings are default

### platform information

latest safari on ios 15

**Comment by KwiatekMiki** [comment]
![image](https://github.com/user-attachments/assets/537605a9-dd74-4ab0-94cc-ac12b071d104)
cobalt can't download age restricted videos since they require logging in
