### ISSUE TITLE
I keep getting a "couldn't verify whether you can download this file". How do I fix this?

### ISSUE THREAD

**Issue by i-just-exist** [imputnet/cobalt#938]
### bug description

I'm trying to download a video, but it won't download, and I continuously get this error that says "couldn't verify whether you can download this file". What does this mean and how do I fix it?

### reproduction steps

1. go to the site
2. paste like, _any_ link into the box (I've encountered this error with bluesky and youtube links)
3. if you get a message that says "couldn't verify whether you can download this file", then that's the error I'm experiencing.

### platform information

Google Chrome ver. 130.0.6723.126 on ChromeOS, same ver number

### additional context

Sorry if I didn't provide enough details, I'm doing my best.

**Comment by i-just-exist** [comment]
the link takes me to the GitHub page, and I cant even open incognito.

**Comment by wukko** [comment]
it's supposed to take you to github.

does cobalt work fine in incognito (without any extensions)? if it does, then try disabling some extensions in regular mode.

**Comment by dumbmoron** [comment]
do you have any extensions installed? can you check?

**Comment by i-just-exist** [comment]
yes, I do

**Comment by i-just-exist** [comment]
four of them I'm unable to turn off

**Comment by i-just-exist** [comment]
I forgot to mention I'm using a school Chromebook. :flushed: :sob:

**Comment by i-just-exist** [comment]
Oh well. I tried.

**Comment by lostdusty** [comment]
If possible, try using another browser. Can you install 3rd party apps by any chance?

**Comment by i-just-exist** [comment]
the website is blocked now fml
![image](https://github.com/user-attachments/assets/5783f82d-3fc4-4325-83da-34e580ed078b)
