### ISSUE TITLE
YouTube download has bugged time

### ISSUE THREAD

**Issue by 6ojo** [imputnet/cobalt#94]
downloaded a 31 second video. time shown in screenshot
video was unlisted
![Screenshot_20230310-004540.png](https://user-images.githubusercontent.com/106943170/224254603-f86963e6-52a3-4f12-8181-c2a9e9aaba2b.png)

**Comment by 6ojo** [comment]
downloaded a public video- same issue

**Comment by wukko** [comment]
hey! this issue can be fixed via simple ffmpeg command: 
`ffmpeg -i inputvideohere.mp4 -c copy outputvideohere.mp4` 

this issue is well-known and im working on an easier solution for this.

it's caused by live rendering, since cobalt can't predict what final file size will be **exactly**.

**Comment by SKCro** [comment]
Correct me if I'm wrong (I'm not really sure how ffmpeg works), but can't you count the duration after it's finished rendering or something?

**Comment by wukko** [comment]
> can't you count the duration after it's finished rendering or something

how do you expect me to edit the header that's already been sent AFTER the render is done? that's literally impossible
