### ISSUE TITLE
"restricted on youtube's side" is back

### ISSUE THREAD

**Issue by TommyTonka** [imputnet/cobalt#941]
### bug description

For no reason, the "restricted on YouTube's side" is back, forcing me to use a different YouTube downloader, all because I was gonna download a FREAKING KOFFEE KAT SHORT!!!!

### reproduction steps

1. Go to youtube.com
2. Copy any link from the site
3. Go to cobalt.tools
4. Paste link from Youtube
5. See error that says "i can't access this video. it may be restricted on youtube's side. have you pasted the right link?"

### screenshots

![Screenshot 2024-11-25 000410](https://github.com/user-attachments/assets/8ae033f6-6347-4aee-8bd5-83ee61318e9e)

### links

```shell
https://www.youtube.com/shorts/IDmexyqfAt4
```

### platform information

Google Chrome on a Windows 11 PC

**Comment by RedrcknRbn** [comment]
Appearing for me too

**Comment by wukko** [comment]
@TommyTonka @RedrcknRbn seems to work fine now, can you try again?

**Comment by RedrcknRbn** [comment]
Works fine now

**Comment by TommyTonka** [comment]
I swear why does it keep coming back

**Comment by TechnologyFuturesInstitute** [comment]
It's happening here as well. If it's restricted, then YouTube doesn't work?
