### ISSUE TITLE
Cannot download this link specifically 

### ISSUE THREAD

**Issue by IndisciplineRoy** [imputnet/cobalt#945]
### problem description

Got the message "i can't access this video. it may be restricted on youtube's side. try a different link!".  This is the video I wanted download. Somehow I cannot download this one specifically for the last few months.
https://youtu.be/QwzDK0dg4Iw?si=W_LdDAbw9Z8hm2VF

### your instance configuration

```shell
https://youtu.be/QwzDK0dg4Iw?si=W_LdDAbw9Z8hm2VF
```

**Comment by wukko** [comment]
this video is from youtube music, it's heavily region locked. your instance may have wrong geoip or hosted in a country where youtube music isn't available.
