### ISSUE TITLE
Youtube API update won't allow download of particular video

### ISSUE THREAD

**Issue by dj-enby** [imputnet/cobalt#946]
### bug description

two videos tonight give the error "youtube updated something about its api and i couldn't get any info about this video. try again in a few seconds, but if this issue sticks, please report it!" so now i'm reporting it because it's been a few minutes and it hasn't worked!

### reproduction steps

1. go to cobalt.tools
2. paste these links "https://www.youtube.com/watch?v=WTHZPh-IJF0" or "https://www.youtube.com/watch?v=Dmh1YMfev50"
3. observe error

### links

```shell
https://www.youtube.com/watch?v=WTHZPh-IJF0
https://www.youtube.com/watch?v=Dmh1YMfev50
```

### platform information

firefox 132.0.2 on windows 10

**Comment by Max-9632** [comment]
im having the same issue i think its due to the new dash thats been added into the newer links

**Comment by wukko** [comment]
here's why it's happening: https://github.com/imputnet/cobalt/issues/942#issuecomment-2500486937

**Comment by jjsa145** [comment]
I think it has spread beyond new YouTube users. My account is from the beginning of time and yet I can no longer download videos using cobalt.tools as of today. Has anyone found any workarounds?

**Comment by wukko** [comment]
seems to work fine now on my side
