### ISSUE TITLE
Can't download Youtube videos or convert to audio

### ISSUE THREAD

**Issue by cobblesteve01** [imputnet/cobalt#952]
### bug description

When I click the >>, it just says that YT updated their API. I waited some time but the issue persists.

### reproduction steps

1. Go to cobalt
2. Paste in Youtube link
3. Click >>
4. Error pops up

### screenshots

![image](https://github.com/user-attachments/assets/aeec5471-aa11-4749-a527-d6a858a4c692)

### platform information

Chrome Dev Edition (Version 133.0.6847.2 (Official Build) dev (64-bit)), Windows 11 Home 24H2 ( Version 10.0.26100 Build 26100)

**Comment by jjsa145** [comment]
I've been using cobalt.tools since September but this has now spread to every video I try to download as of today. Any idea of a work around for the time being?

**Comment by cobblesteve01** [comment]
No idea, sorry. It's been working fine ever since today.

**Comment by cyfam** [comment]
having same problem rn with youtube links on firefox

**Comment by cobblesteve01** [comment]
It's definitely something with the API, so until they fix/update it, the issue isn't going away I think.

**Comment by kamuridesu** [comment]
would be nice to have some logs on the cobalt api to see what youtube is returning when it gives an error

**Comment by cobblesteve01** [comment]
Works now! I guess it was just a yesterday problem.
