### ISSUE TITLE
error.api.auth.not_configured

### ISSUE THREAD

**Issue by MC-shark** [imputnet/cobalt#953]
### bug description

When I request /session api, Response {
    "status": "error",
    "error": {
        "code": "error.api.auth.not_configured"
    }
}

### reproduction steps

My docker-compose.yml 
<img width="580" alt="image" src="https://github.com/user-attachments/assets/a591f482-db42-49ba-8326-6bbf3d7843fd">

### platform information

postman

**Comment by wukko** [comment]
let’s take a wild guess and try to figure out what “auth not configured” error means.

_(you don’t need session if turnstile is not enabled, https://github.com/imputnet/cobalt/blob/main/docs/api.md)_

**Comment by MC-shark** [comment]
But I Request POST
curl --location --request POST 'http://ip:9000/' \
--header 'Content-Type: application/json' \
--data-raw '{
"url": "https://www.youtube.com/watch?v=rIyRrUAsaok",
"downloadMode": "audio"
} '

Response:
{
"status": "error",
"error": {
"code": "error.api.header.accept"
}
}
