### ISSUE TITLE
error.api.auth.not_configured

### ISSUE THREAD

**Issue by MC-shark** [imputnet/cobalt#954]
### bug description

Request /session
Resonse 
{
    "status": "error",
    "error": {
        "code": "error.api.auth.not_configured"
    }
}

### reproduction steps

<img width="602" alt="image" src="https://github.com/user-attachments/assets/476a8d7c-6c11-42f1-bc07-4371d16692f1">

### platform information

postman

**Comment by MC-shark** [comment]
But I Request POST
curl --location --request POST 'http://ip:9000/' \
--header 'Content-Type: application/json' \
--data-raw '{
"url": "https://www.youtube.com/watch?v=rIyRrUAsaok",
"downloadMode": "audio"
} '

Response:
{
"status": "error",
"error": {
"code": "error.api.header.accept"
}
}

**Comment by dumbmoron** [comment]
the api is working as intended. please do not open duplicate issues

**Comment by MC-shark** [comment]
Why Response “code”：“error.api.header.accept”, Do I need to configure anything？

**Comment by dumbmoron** [comment]
yes, please read the api documentation for the `/` endpoint

**Comment by hextor1** [comment]
From my side i have facing an same issue error.api
