### ISSUE TITLE
The spinner is taking AN ETERNITY

### ISSUE THREAD

**Issue by TommyTonka** [imputnet/cobalt#958]
### bug description

I was gonna download ANOTHER Koffee Kat short, but the spinner kept on going forever and ever and ever and ever! Please fix this! I don’t wanna use a different YouTube downloader!

### reproduction steps

1. Go to youtube.com
2. Copy any link from the site
3. Go to cobalt.tools
4. Paste link from Youtube
5. See error that says "cloudflare turnstile is still checking if you're not a bot. if it takes too long, you can try: disabling weird browser extensions, changing networks, using a different browser, or checking your device for malware."

### screenshots

![IMG_5561](https://github.com/user-attachments/assets/6f00ede5-0914-4330-a799-231eefc4f8c4)
![IMG_5562](https://github.com/user-attachments/assets/e6de69d4-a8b8-4007-8dcf-c18eada0278a)

### links

```shell
https://m.youtube.com/shorts/_32EyDyhGrg
```

### platform information

Safari on a iPhone 11 Pro

**Comment by 27theo** [comment]
Did you try the steps suggested?

**Comment by wukko** [comment]
not an issue related to cobalt, check your network and extensions, just like cobalt says

**Comment by mrshmllow** [comment]
@wukko can you aliterate on what "check your network" means?
