### ISSUE TITLE
Unable to seek backward or forward downloaded vedio

### ISSUE THREAD

**Issue by Deepalwije123** [imputnet/cobalt#959]
### bug description

After downloading the vedio ( vp9 or av1) using “https://cobalt.tools/ “ unable to seek forward or backward using any kind of vedio player app.
Iam use “ https://cobalt.tools/” on both IOS 18.1 and ipad os 18.1 
Player app: Infuce / vlc player/ senplayer/
Pls resolve this matter ASAP 

i

### reproduction steps

1. Go to link https://cobalt.tools/
2. Under settings change vedio to vp 9 or av1
3. Sound set to “ Best”
4. Past youtube vedio link
5. Download the vedio to iphone ( 15 pro max)or ipad( ipad pro m4)
6. Play the vedio using infuse , vlc player or senplayer
7. Unable to seek forward or backward use app seek bar

### platform information

Ios 18.1.1 and ipad os 18.1.1

**Comment by wukko** [comment]
https://cobalt.tools/remux
