### ISSUE TITLE
Can’t download auto-generated music videos from YouTube Music on the main instance

### ISSUE THREAD

**Issue by warboi98** [imputnet/cobalt#961]
### bug description

when you paste a link of a youtube song this shows up

### reproduction steps

Open https://cobalt.tools/
Change video settings to MP3 and 320kb/s
Put following URL , https://www.youtube.com/watch?v=oVW6wJ7MYDM&ab_channel=TheBeatles-Topic
it didn't work???

### screenshots

![image_2024-11-27_211632641](https://github.com/user-attachments/assets/c3368464-73a4-4664-938e-02a1f7f098f1)

### platform information

windows 11

### additional context

the song is not age restricted btw

**Comment by wukko** [comment]
seems to be resolved now!
