### ISSUE TITLE
"code": "error.api.invalid_body"

### ISSUE THREAD

**Issue by hextor1** [imputnet/cobalt#962]
### bug description

When i use v7 /ap/json end point then status code is 200 and i received stream url. 
Like this

{
    "status": "stream",
    "url": "https://abc.com/api/stream?id=U-YCJ3wHXum7JqW9Bs1O_&exp=1732770211874&sig=wGhJvXSFIlUHQaH14xDiY3mbBIIt1V04td-Hs1DWX1w&sec=kGNuz-FUk_fOY8Gk4PxAtXyyIOJXuWGKUGwO55gtPSI&iv=5NLNb8HP8DVn92FtTLfhdQ"
}

When i update my v7 to v10 cobalt verion then fetch this endpoint / its give me error like this 

{
    "status": "error",
    "error": {
        "code": "error.api.invalid_body"
    }
}

Whats changes we need to do please anybody tell me?

### reproduction steps

1. go to postman and hit your local url 
2. upload your payload in body like thi s
3. {
    "url": "https://www.youtube.com/watch?v=I1Llz8075MA",
    "isAudioOnly": "true",
    "aFormat": "mp3"
}

### screenshots

![image](https://github.com/user-attachments/assets/20d21284-d075-4869-a6f0-1f7f75aa3e8f)

### links

```shell
http://localhost:9000/
```

### platform information

Chrome

**Comment by wukko** [comment]
rtfm https://github.com/imputnet/cobalt/blob/main/docs/api.md#request-body

**Comment by hextor1** [comment]
@wukko  Please check now it got this error please tell me  whats an error where i am doing an mistakes 
![image](https://github.com/user-attachments/assets/acebe5f4-a98c-4bbf-b34f-3202f9fedb22)
