### ISSUE TITLE
Hello, I found that the cookies on YouTube in the instance of Cobalt are not working, but I noticed that the official website of Cobalt can parse them. Is there any other better way to obtain YouTube videos

### ISSUE THREAD

**Issue by lpwyz** [imputnet/cobalt#971]
### problem description

Hello, I found that the cookies on YouTube in the instance of Cobalt are not working, but I noticed that the official website of Cobalt can parse them. Is there any other better way to obtain YouTube videos

**Comment by wukko** [comment]
#942
