### ISSUE TITLE
Cobalt only downloading a small portion of a youtube video

### ISSUE THREAD

**Issue by TrilobiteFaye** [imputnet/cobalt#973]
### bug description

hello! i primarily use Cobalt on Safari on my cell phone and i’ve been running into a kind of frequent issue where Cobalt will only download a small portion of the youtube video i’ve selected, like just 10 minutes of an hour long video, for example. sometimes the site works perfectly fine but this issue has been happening semi-regularly for a little while! i’m not sure what could be causing it, it’s not a storage space issue or anything like that.

### reproduction steps

1. go to cobalt.tools on Safari
2. paste a YouTube link into the URL bar and download it
3. check downloads tab
i’ve been having the problem both with directly downloading it to my files and with the camera roll shortcut, so either of those could possibly reproduce the issue.

### platform information

Safari 17.4.1 on iOS 18.1.1

**Comment by wukko** [comment]
enable the hls option: https://cobalt.tools/settings/video#youtube-hls
