### ISSUE TITLE
Can't download youtube videos

### ISSUE THREAD

**Issue by Sheepaleepz** [imputnet/cobalt#974]
### bug description

Hi! I can't seem to download youtube videos without getting an error message. From looking at other threads it seems like it's a recurring thing? So I figured I'd let you know!

### reproduction steps

1. go to cobalt and paste in a youtube link
2. click download
3. error shown below shows up

### screenshots

![image](https://github.com/user-attachments/assets/743286cb-199f-486a-a983-c60d3fc62a79)

### links

```shell
https://www.youtube.com/watch?v=ldY0LriMc6U
```

### platform information

Firefox

**Comment by wukko** [comment]
this is a youtube music video, we already have a thread for that: #961
