### ISSUE TITLE
Can not download full audio file with Soundcloud

### ISSUE THREAD

**Issue by nguyenquy96** [imputnet/cobalt#975]
### bug description

I can't download full file with Soundcloud service. With sound 1 hours can download 30 second but not full 

### reproduction steps

1. go to Cobalt.tool
2. Add Soundcloud link 
3. Download
4. Not have full file

### platform information

Version 131.0.6778.86 (Official Build) (64-bit) on Windows 10

**Comment by wukko** [comment]
can’t debug this without a test link. fill out the entire issue template next time.
