### ISSUE TITLE
Video is being cut in half (roughly) and only the first half is being downloaded

### ISSUE THREAD

**Issue by rods012** [imputnet/cobalt#978]
### bug description

I attempted to download a video at 1080p with both the h264 and av1 codecs. The full length of the video is 22:04 minutes long but with the h264 codec the resulting video file was 13:18 minutes long. On my second pass with the h264 codec, the video file was 9:06 in length. With the av1 codec the video file was 10:57 minutes long. The videos simply cut off at the end.

### reproduction steps

Cobalt setting variations tested (video max resolution is 1080p so higher settings in cobalt properly lowered to 1080p):

- 4K video quality, h264 encoder 
- 1080p video quality, h264 encoder 
- 4K video quality, h264 encoder 
- 1080p video quality, h264 encoder 

Video used: https://www.youtube.com/watch?v=FAERbvDbAKY

On the main cobalt page, I had the option set to "Auto" to get a video file, and I manually pasted the URL ( I did not use the paste button). Once the website finished checking my authenticity, I pressed the double arrows to download the video. The process of it actually downloading the video seemed normal and without any apparent issues.

I am using Firefox latest ESR browser version (1.28.5.1esr) 64-bit.
I am located in Brazil. 

### links

```shell
Video used: https://www.youtube.com/watch?v=FAERbvDbAKY
```

### platform information

Firefox ESR version 128.5.1esr on Windows 11 23H2

**Comment by wukko** [comment]
does enabling hls help? https://cobalt.tools/settings/video#youtube-hls

**Comment by rods012** [comment]
Yes, it does. Thank you! I must have missed that feature.
