### ISSUE TITLE
Infinite video length

### ISSUE THREAD

**Issue by zydiaa** [imputnet/cobalt#979]
### bug description

hey everyone!

I always have this bug, that I can't see the length of the video, cant go back or go forward in the video.
How can I fix this?

### reproduction steps

Every downloaded video

### screenshots

![image](https://github.com/user-attachments/assets/20bdcf07-d63c-43fc-8551-a0200fbe6846)

### platform information

Windows 11

**Comment by KwiatekMiki** [comment]
https://cobalt.tools/remux
