### ISSUE TITLE
May I ask, what is the issue of returning "error. api. content. too-long" when downloading YouTube through API? 

### ISSUE THREAD

**Issue by tuoxiebushuijiao** [imputnet/cobalt#980]
### bug description

![image](https://github.com/user-attachments/assets/58488d07-2f7e-49a4-a33c-9d6b06ea8829)

### reproduction steps

Request API "POST:/" through Postman

### screenshots

![image](https://github.com/user-attachments/assets/48ef3b51-014c-45ec-8cdf-8dff6609df94)

![image](https://github.com/user-attachments/assets/b15200ea-5e27-4dd8-a76b-19272eda0fcc)

### platform information

windows 11  Google Chrome

**Comment by wukko** [comment]
it means that content is too long. you can change the limit via `DURATION_LIMIT` env variable. you can [read more in docs](https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md#:~:text=limit%20window%20duration.-,DURATION_LIMIT,-10800)

**Comment by tuoxiebushuijiao** [comment]
Thank you.
