### ISSUE TITLE
"Couldn't find any media..."

### ISSUE THREAD

**Issue by EvilCheeseWhiz** [imputnet/cobalt#982]
### bug description

I keep finding random videos which, no matter how I share/send/save links, simply refuse to be recognized as having content, but when followed via browser play just fine.  Apologies if this has already been reported, but I am new to this type of service and learning as I go.  

One such example is the following (all to same vid):
https://fb.watch/wmOA7pFWRE/
https://www.facebook.com/share/v/1BQnbWYn2g/
https://www.facebook.com/share/v/1CjbcDpSTX/
https://www.facebook.com/watch/?v=598737626058634
https://fb.watch/wmNYZ-F2nD/

Note:
I WAS able to get a working link by jumping through hoops.
https://www.facebook.com/DailyRomanUpdates/videos/598737626058634/

Fix:
Track video to original post.
Click "..." at upper right hand corner of post.
Click "Embed"
Click "Advanced Settings" hyperlink
Copy the link labeled under "URL of video"

Result:
https://kityune.imput.net/tunnel?id=5fflRrRgNJXDiEj0LXYuT&exp=1733759368953&sig=sXNPqaZFsb2JYKbVqZqzgjKPtw10M5bhYage8YbZK1s&sec=oR28eQ5A1gUrAVEmgbjoRI7CucS3qYiIErAdBJHbsaI&iv=5tDXvQfFzBh0PxGjxDt4Fg

### reproduction steps

Issue:
Use any above link @cobalt, they fail.
Follow a link to try to get a different format/address, fails.
Sent to messenger, etc, fails.

### links

```shell
https://fb.watch/wmOA7pFWRE/
https://www.facebook.com/share/v/1BQnbWYn2g/
https://www.facebook.com/share/v/1CjbcDpSTX/
https://www.facebook.com/watch/?v=598737626058634
https://fb.watch/wmNYZ-F2nD/

https://www.facebook.com/DailyRomanUpdates  |  November 23 at 2:31 PM
https://www.facebook.com/DailyRomanUpdates/videos/598737626058634/
```

### platform information

Browser:Firefox 133.0 (64-bit), OS:Windows 11 home - 23H2 build 22631.4541

### additional context

Fix:
Track video to original post.
Click "..." at upper right hand corner of post.
Click "Embed"
Click "Advanced Settings" hyperlink
Copy the link labeled under "URL of video"

**Comment by KwiatekMiki** [comment]
#917
