### ISSUE TITLE
If I click the button it doesn't auto download, I have to do control+v in a new tab

### ISSUE THREAD

**Issue by MrRorls12** [imputnet/cobalt#984]
### bug description

Basically when I press the download button (for lack of a better term) it doesn't download and I have to paste a link into a different tab to download it.

### reproduction steps

Basically with every file

### platform information

Microsoft Edge on Windows 11

**Comment by MrRorls12** [comment]
> can you screen record what's happening?

Will do

**Comment by MrRorls12** [comment]
> can you screen record what's happening?


Uploading 8mb.video-mj9-dnTZ7tbs.mp4…

**Comment by wukko** [comment]
i can’t see that video cuz you sent the comment before it finished uploading

**Comment by MrRorls12** [comment]
> i can’t see that video cuz you sent the comment before it finished uploading

Ohhh my bad

https://github.com/user-attachments/assets/a4db027c-7c59-4259-ad1b-08d9bcec0f72

**Comment by MrRorls12** [comment]
Damn it the download list ain't showing

**Comment by wukko** [comment]
do you have an extension that blocks popup windows? if so, disable it

what saving method do you have here? https://cobalt.tools/settings/download#saving

**Comment by MrRorls12** [comment]
> do you have an extension that blocks popup windows? if so, disable it
> 
> what saving method do you have here? https://cobalt.tools/settings/download#saving

Okay will do thanks for your time buddy
