### ISSUE TITLE
Issue with downloading daily motion video

### ISSUE THREAD

**Issue by tsuname4** [imputnet/cobalt#985]
### bug description

The website did not check then I pasted the link to my video(https://dai.ly/x9a4cu4) but it doesn't download it and the message about an issue with fetching daily motion video and that I should report it. That's it basically 

### reproduction steps

go to cobalt.tools
wait for bot check to finish
paste the link https://dai.ly/x9a4cu4
click on arrows to proceed
issue window pop-up

### links

```shell
https://dai.ly/x9a4cu4
```

### platform information

Chrome 131.0.6778.81, Android 14; T442M Build/UP1A.231005.007

**Comment by KwiatekMiki** [comment]
the video is private

![image](https://github.com/user-attachments/assets/814e7ed7-a613-4277-88d3-bf27c04b1fa8)

**Comment by wukko** [comment]
cobalt can't download anything that isn't accessible via a link, such as this video. it may be missing an access key or something similar.

**Comment by tsuname4** [comment]
Thank you for reply, I get it. For some reason before putting the video
link into cobalt I was able to watch it, but afterwards it became private
