### ISSUE TITLE
Progressive Download And Not Expected Streaming [Windows]

### ISSUE THREAD

**Issue by tt-j2** [imputnet/cobalt#986]
### bug description

Hello,

It's my first use of cobalt web and I have downloaded some videos to test. Take this as example: [https://www.youtube.com/watch?v=z19HM7ANZlo](https://www.youtube.com/watch?v=z19HM7ANZlo)

I noted it progressively downloads the video, I don't know if this is the correct way:

https://github.com/user-attachments/assets/6ad34109-9c91-40d0-8c46-57ac0294721c

With others tools we can see the final file size:

https://github.com/user-attachments/assets/3758af0f-db11-41d7-b2c9-23b8bdfcc66d

After downloading with cobalt and opening with Movies & TV the video cannot be fast-forwarded or changed its current time:

https://github.com/user-attachments/assets/18130f42-92bf-4fe2-87a8-29cd94b6f317

With other tool there are no problems:

https://github.com/user-attachments/assets/8499d13f-7909-48ac-994e-69e7e227d82c

If I open the cobalt video with VLC, we can note some pixelating and freezing frames in a short period of time when changed the current time:

https://github.com/user-attachments/assets/ec29b523-0283-495d-ad87-1e3f65a19074

Is this the normal behaviour of the downloaded file? What am I missing?

### reproduction steps

1. Go to cobalt.tools
2. Paste any youtube link
3. Default settings (also tried with youtube hls mode on and same problem)
4. The download process is progressive instead of showing entire file size
    - Open the downloaded video with Movies & TV
        * Fast-forward the video is not working
    - Open the downloaded video with VLC
        * Fast-forward causes some pixelating and freezing frames in a short period of time after the current time is changed

### platform information

Windows, Google Chrome Version 131.0.6778.109 (Official build) (64 bits)

**Comment by wukko** [comment]
progressive downloading is normal and is caused by how cobalt works, you can read more about it either in the about tab in cobalt or the readme on github.

remuxing should fix unknown length in old players (movies & tv) and pixelization when rapidly jumping between parts of the video: https://cobalt.tools/remux

**Comment by tt-j2** [comment]
@wukko I believe this issue should be reopened because my problem has not been resolved and no useful information has been provided to help. Here are the details of the ongoing problem:

> progressive downloading is normal and is caused by how cobalt works, you can read more about it either in the about tab in cobalt or the readme on github.

Could you specify exactly where is that info?

I read both texts and couldn't find any of "progressive downloading".

> remuxing should fix unknown length in old players (movies & tv)

Could you specify what do you mean by "old player"?

Moves & TV is the native app for reproducing videos on Windows 10 and, as far as I know, Windows 11. So I don't think it is an "old player". I never had those problems with any of the videos downloaded from the internet. In some cases due to lack of codecs, that's why I installed VLC but otherwise I didn't need it. And I don't think VLC is an "old player" either. If someone searches "most used video player for windows" most of the websites says it's VLC.

> and pixelization when rapidly jumping between parts of the video: https://cobalt.tools/remux

Could you specify what do you mean by "rapidly jumping between parts of the video"?

I jump quickly on many videos played on many players on many computers the same way I did on the video and I never had any freezing problems. So if you can clarify all of these points I could understand better.

If you need more details about the platform, let me know and I will be happy to provide it because cobalt is the only reliable tool available nowdays and I want to solve these problems I have.

Thank you!
