### ISSUE TITLE
[Minor Bug Maybe] Selecting light mode on auto while my firefox settings are dark already 

### ISSUE THREAD

**Issue by Greatz08** [imputnet/cobalt#987]
### bug description

When i loaded the main website i was stunned with light mode (too much sudden light :-(( )  , my whole system is in dark mode , idk why this web app detected it as light mode , altho i do know it is small thing and i can fix it already by forcing it to dark mode still if possible do look in to this and see maybe if you can find what cause that issue and fix it  

### reproduction steps

i just have my hardened arken fox firefox and normally opened the main website , thats all i can say 

### screenshots

![image](https://github.com/user-attachments/assets/b4f0a7f3-1a45-4341-92bc-e28e70a7705e)

Can see my firefox settings below : 
![image](https://github.com/user-attachments/assets/b429e5e3-5c91-4d82-87ee-4823aa281853)
 

### platform information

firefox 128

### additional context

i had dark reader addon with me still somehow it didnt forced it to dark mode idk why , css styling looking sus :-)) generally dark reader does switch to dark mode for websites which dont support it or have light mode default and have issues in detecting with auto mode

**Comment by wukko** [comment]
> hardened firefox

things like this usually hide the preferred theme from websites for sake of “privacy”. try looking up this issue for your browser. cobalt works as intended in regular firefox and other browsers.

**Comment by wukko** [comment]
just because there’s ui for selection doesn’t mean that the preference is actually used. disable darkreader and open a website that has an auto dark theme. if it’s still white, then the issue is in the browser.

i think cobalt is in darkreader’s exceptions cuz it already has a dark theme
