### ISSUE TITLE
Can't acces any youtube video

### ISSUE THREAD

**Issue by westrenen** [imputnet/cobalt#988]
### bug description

Hi, i've used Cobalt for quite some time now, but all of a sudden cobalt can't acces youtube links anymore.

### reproduction steps

1. Go to youtube.com
2. Copy any link from the site
3. Go to cobalt.tools
4. Paste link from Youtube
5. ''Can't access this video. it may be restricted on youtube's side"

### screenshots

![98](https://github.com/user-attachments/assets/14ddfbe5-e091-441a-9d6e-d2717f541123)

### platform information

Windows 11

**Comment by TommyTonka** [comment]
Seems like it just keeps returning for no reason each time

**Comment by wukko** [comment]
this specific issue doesn't seem to happen anymore, though #992 is now present
