### ISSUE TITLE
support for videos longer than 180 mins?

### ISSUE THREAD

**Issue by TrilobiteFaye** [imputnet/cobalt#989]
### describe the feature you'd like to see

i’m not sure if anyone has suggested this before or if it’s already in development (or if it’s just not possible, in which case i’m sorry for suggesting it) but it would be great to see support for downloading videos longer than 180 minutes, like the name says.

**Comment by wukko** [comment]
??? the main instance already has no limit, you can learn how to change it on your own by reading the “host an instance” doc

**Comment by TrilobiteFaye** [comment]
oh! i could’ve sworn i saw "Cobalt doesn’t support videos longer than 180 minutes" at some point. huh

**Comment by wukko** [comment]
maybe you should’ve checked before making a new issue?
