### ISSUE TITLE
Cloudflare Turnstile blocked me for no reason

### ISSUE THREAD

**Issue by ItsOpenSourceSoftware** [imputnet/cobalt#990]
### bug description

I wanted to download a .mp3 file from a youtube link but Cloudflare Turnstile blocked me for no reason i cleared the cookies but that did not work i guess its a ip address ban. and also when you get unblocked you get a 0 bytes .mp3 file

### reproduction steps

1. download the file as .mp3
2. get blocked by cloudflare turnstile for no reason
3. when you get unblocked you get a 0 bytes .mp3 file
4. you get blocked again

### screenshots

![image](https://github.com/user-attachments/assets/7dc2985e-07b1-4795-9c23-b6228a9ce2fe)
![image](https://github.com/user-attachments/assets/43d884fa-f357-4314-b694-142b0a51a490)

### platform information

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0

**Comment by XXXXPro** [comment]
I have the same problem! 
In developer console I see that I get error 401 for many times when accessing to https://challenges.cloudflare.com/cdn-cgi/challenge-platform/*. Tried to disable uBlock Lite, but it didn't help anyway. 
My platform is SRWare Iron version 129.0.6550.0 (64 bit official build for Linux).

**Comment by ItsOpenSourceSoftware** [comment]
when i download a youtube mp3 file i get a 0 bytes .mp3 file

**Comment by caohuan99** [comment]
I have the same problem!

**Comment by wukko** [comment]
the issue with 0 bytes is not related to turnstile and can be tracked here: #992. turnstile only affects initial access, not downloading.

we unfortunately can't help you with turnstile taking a bit longer than you'd like it to, as we have no control over it. try doing what cobalt suggested you to do.
