### ISSUE TITLE
Can't download stuff from YouTube, cobalt says it's disabled or returns 0 byte files

### ISSUE THREAD

**Issue by bridgetpenpen** [imputnet/cobalt#992]
### bug description

every time i download any video the bytes are 0 off youtube

### reproduction steps

1 go to youtube
2 copy and paste link into cobalt
3 hit the arrows to download
4 see that the files have 0 bytes on them

### screenshots

![Screenshot (3)](https://github.com/user-attachments/assets/f91ff837-da07-4cdc-a61c-f0b901beaa69)

### platform information

window 10 on chrome/google on ios

**Comment by hamidb80** [comment]
same here

**Comment by ogohogo** [comment]
beside ip blocking they send abuse messages, be careful :)

![image](https://github.com/user-attachments/assets/ccdb39f4-ff02-4176-a972-669078c995d2)

**Comment by wukko** [comment]
> beside ip blocking they send abuse messages, be careful

i'm soooo scared of a baseless threat by google
_(thank you for the warning though)_

**Comment by Sainan** [comment]
Might it be possible to setup Mullvad on the processing servers to bypass the IP blocks? I know a VPN is a bit tricky on servers due to incoming traffic, but not impossible.

**Comment by VerityIncorporated** [comment]
@Sainan I actually have Gluetun setup in a docker container which uses Mullvad, I then connect it to the Cobalt API instance that is also running in a docker container. This worked for me but not for very long, the IP's eventually get blocked (pretty quickily too).

**Comment by Sainan** [comment]
Set it up to automatically switch Mullvad servers every hour. 🙈

**Comment by VerityIncorporated** [comment]
> Set it up to automatically switch Mullvad servers every hour. 🙈

I assume you're joking, but if not, rotating proxies might actually be a better solution than a VPN.

**Comment by Sainan** [comment]
I'm not joking. It's what we did for checking a certain anti-cheat provider for information about bans. (They did not like that we were providing transparency into their business.)

**Comment by VerityIncorporated** [comment]
Wouldn't you eventually run out of servers to use on Mullvad? Plus, YouTube could end up blocking their ASN altogether. A rotating proxy might be a more sustainable solution for something like this.

**Comment by Sainan** [comment]
The idea is that legit users still use Mullvad, so blocking them outright might be less ideal.

**Comment by VerityIncorporated** [comment]
I think you're right in that they wouldn't block them outright. Still a possiblity since it is Google we're talking about. Regardless I think running a VPN over the entire instance would be slow, potentially cause issues with other services and be somewhat useless since the time it takes YouTube to block the IP is inconsistent, so changing server every 1 hour wouldn't be a solution.

**Comment by tayfrm99** [comment]
> The idea is that legit users still use Mullvad, so blocking them outright might be less ideal.

true, they also move their servers around quite often

**Comment by WorriedArrow** [comment]
Seems to work now..?

**Comment by vergiliusmaximus** [comment]
Working now 👍 thanks a lot. Imma donate when I can

**Comment by vergiliusmaximus** [comment]
> Seems to work now..? 

yup working now

**Comment by Axis4s** [comment]
6:16pm, dec14,  its broken again 😔

**Comment by SleepyPeko** [comment]
still getting 0b over here. ig youtube links are still broken

**Comment by SleepyPeko** [comment]
> still getting 0b over here. ig youtube links are still broken

anyways, ight imma go selfhost cobalt

**Comment by ieatwaffle** [comment]
Hello! i created an account just to say that issue is still persistent with YouTube links. I was able to download SoundCloud links but YouTube doesn't seem to be working at the moment again.

**Comment by wukko** [comment]
fixed again, it happened deep at night, almost intentionally

**Comment by leemkh1010** [comment]
> I'm not joking. It's what we did for checking a certain anti-cheat provider for information about bans. They did not like that we were providing transparency into their business. After deploying this Mullvad approach, they seemed to stop bothering.

@wukko Did you deploy this solution? Can you please share with us how you fixed it? Thank you so much!

**Comment by marco-lee-datax** [comment]
> Wouldn't you eventually run out of servers to use on Mullvad? Plus, YouTube could end up blocking their ASN altogether. A rotating proxy might be a more sustainable solution for something like this.

@wukko Did you deploy this solution? Can you please share with us how you fixed it? Thank you so much!

**Comment by Chonkblonk** [comment]
I appear to be experiencing an issue like this, I am getting a 0 byte file, but most peculiarly, what I am being provided is a 0 byte .txt file, for whatever reason.

![Image](https://github.com/user-attachments/assets/1bf4dc58-9d8e-4211-9878-4a48d63b29e2)

Now, I want to be clear also that I have not somehow managed to change anything on my end to make my computer think that .mp3 files are to be opened with Notepad.exe, because that is not what is happening on my end. It seems that either Cobalt or Firefox interprets the file in question as being a .txt file.

**Comment by wukko** [comment]
> I appear to be experiencing an issue like this

@Chonkblonk can you try again?

**Comment by Cattrag** [comment]
![Image](https://github.com/user-attachments/assets/1855f5e2-c09d-41b7-8e24-ead061ac23bf)
now im getting it too...

**Comment by Chonkblonk** [comment]
The funniest thing, is that just a few minutes after sending this, I tried again, and then suddenly it worked.
Sorry, should have replied back sooner.
